Add SiteKit admin URLs for Analytics links on dashboard.
google/site-kit-wp pull request #1956
Opened 2020-08-26 18:39 UTC by tofumatt

## Summary

Addresses issue #1922.

## Relevant technical choices

When running locally I was oddly getting **`"".concat` is not a function** errors when using template strings for the `siteURL + link` concat. Unsure why, but it's why I didn't use string concatenation in this proof-of-concept.

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-09-08 16:25 UTC, eugene-manuilov commented
@googlebot I consent.

2020-09-09 18:44 UTC, felixarntz requested changes
Technically LGTM, but this is missing the similar change required for the WordPress dashboard widget per the ACs.

2020-09-09 23:18 UTC, felixarntz approved these changes
Great!

2020-09-10 00:02 UTC, felixarntz approved these changes

2020-09-10 00:43 UTC, merged