Enhancement/317 add date filters for adsense
google/site-kit-wp pull request #1971
Opened 2020-08-28 20:52 UTC by ryanwelcher

## Summary

Addresses issue #317

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-09-28 20:48 UTC, felixarntz requested changes
Overall this is looking good visually, but there are a few things missing, and I think the implementation is overly complex and partially different from the IB.

2020-09-28 20:48 UTC, felixarntz commented on assets/js/modules/adsense/components/dashboard/AdSenseDashboardWidget.js
> +								headerCtaLabel={ __( 'Advanced Settings', 'google-site-kit' ) }
This is also different from the ACs.

2020-09-28 20:48 UTC, felixarntz commented on assets/js/modules/adsense/components/dashboard/AdSensePerformanceWidget.js
> +function AdSensePerformanceWidget( ) {
Regarding my above comment, the problem _may_ only be here: This component used to rely on `withData`, which is how the `handleDataSuccess` and `handleDataError` (which are not a great approach but are what is used right now) worked before. Now that that is gone, it causes the problem I mentioned above, where the `AdSenseDashboardZeroData` component is no longer showing. Let's either reverse the refactoring or can you suggest an alternative implementation based on what you have here that works?

2020-10-06 15:39 UTC, ryanwelcher commented
Closing this PR in favor of #2135

2020-10-06 15:39 UTC, closed without merging