Normaize URLs and test.
google/site-kit-wp pull request #2144
Opened 2020-10-07 21:10 UTC by adamsilverstein

## Summary

Addresses issue #

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-10-08 21:02 UTC, felixarntz requested changes
Looks solid for the most part, but there are a few things to fix.

2020-10-08 21:02 UTC, felixarntz commented on tests/phpunit/integration/Core/Util/Google_URL_Matcher_TraitTest.php
> +	public function test_url_normalizer( $domain, $compare, $expected ) {
This entire `Google_URL_Normalizer`-specific test code should go into a separate test class, there should always be one test class per class to test. In other words this should go into `Google\Site_Kit\Tests\Core\Util\Google_URL_NormalizerTest`.

2020-10-08 21:02 UTC, felixarntz commented on tests/phpunit/integration/Core/Util/Google_URL_Matcher_TraitTest.php
> +			),
See above, the trailing slash parts should be removed from here too.

2020-10-08 21:43 UTC, felixarntz approved these changes
@adamsilverstein I've quickly added the remaining code changes. Can you take care of QAing this, since you have most context and have some test sites? Would be great to provide some info and screenshots on your issue comment similar like Cole does usually.

2020-10-08 22:14 UTC, merged

2020-10-09 16:37 UTC, adamsilverstein commented
Thanks for taking care of those final changes @felixarntz - I'll give this a test.