Add extra ESLint rules.
google/site-kit-wp pull request #2226
Opened 2020-10-21 18:46 UTC by tofumatt

## Summary

Addresses issue #2154.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-11-12 21:18 UTC, aaemnnosttv commented
@tofumatt lint is failing, can you take a look?

2020-11-16 16:29 UTC, aaemnnosttv requested changes
Looking good @tofumatt! It seems there are still a few kinks to work out but it's much better. I left a few comments mostly around the tests.

Also, I noticed some strange behavior around some of the errors for the `@since` tags. It's currently adding 1 error per `@since` tag even when only one of them is invalid.

This block has 3 `@since` tags – all of which are valid, only the new line between them.
![image](https://user-images.githubusercontent.com/1621608/99278975-62744a00-2838-11eb-9d70-c24ac386272c.png)
After duplicating the last line
![image](https://user-images.githubusercontent.com/1621608/99278993-6738fe00-2838-11eb-82da-bcb373265065.png)

One (probably unrelated) observation is how a missing return triggers two different lint errors that mention different tags
![image](https://user-images.githubusercontent.com/1621608/99279663-268db480-2839-11eb-8646-5059f8220d62.png)

All around, nice work 👍

2020-11-16 16:29 UTC, aaemnnosttv commented on packages/eslint-plugin/rules/jsdoc-tag-order.test.js
> +}
Again, this seems much more verbose than necessary and mostly adds noise to the test.
Does ESLint complain when things aren't used here as well? Is it checking the given code with all of our rules or just the one? It's at least using undefined functions so we could always do something like `dummyFunction( paramA, paramB, paramC )` if needed.

2020-11-18 22:49 UTC, tofumatt commented on packages/eslint-plugin/rules/jsdoc-capitalization.test.js
> +export function WithTestRegistry( props ) {
That's a good call. I think I started with this whilst testing and then never bothered replacing the code, but all that makes sense. Changed! 👍🏻

2020-11-18 22:51 UTC, tofumatt commented on packages/eslint-plugin/rules/jsdoc-requires-since.js
> +		return [ 'since' ].includes( tag );
Totally, this is just copied from other filters and I didn't bother to simplify it. 👍🏻

2020-11-18 22:51 UTC, tofumatt commented on packages/eslint-plugin/rules/jsdoc-requires-since.js
> +				message: 'All @since tags after the first one require a description.',
I like the second, it's a bit clearer to me. 👍🏻

2020-11-18 23:15 UTC, tofumatt commented on packages/eslint-plugin/rules/jsdoc-tag-grouping.test.js
> +						'The @private tag should be followed by an empty line, and then by the @param tag.',
Good catch, that was actually broken before. Fixed it 😄

2020-11-19 00:12 UTC, tofumatt commented
Good catch on the double-reporting of the `@since` tag. That was due to it being a default "previous" tag in the code—a holdover I think from some testing that seemed largely work but not quite.

I've fixed that, and I think all other issues, including checking the order of version numbers for `@since` tags and ensuring only one `@since` tag exists for each version.

Should be good for another set of 👀 now 🙂

2020-11-19 10:11 UTC, aaemnnosttv commented
@tofumatt the lint job is failing now 😄  – do you want me to review before or after?

2020-11-20 12:31 UTC, tofumatt commented
Argh, sorry about that. One was a bug (fixed!) but another was since tags needing updates that I missed.

Ready now!

2020-11-23 10:12 UTC, aaemnnosttv reviewed
Almost there, just one thing left to fix.

2020-11-23 10:12 UTC, aaemnnosttv commented
@googlebot I consent.

2020-11-23 10:15 UTC, aaemnnosttv submitted a review, later dismissed
All good now, thanks!

2020-11-23 11:27 UTC, aaemnnosttv approved these changes
Should be all good now :) 

@tofumatt I also updated the tests for `@since` tags to remove remaining unnecessary bits and reword the descriptions to better describe the tests. We can iterate on this more as we add more tests with ESLint but this should be good for now. Thanks!

2020-11-23 11:39 UTC, tofumatt reviewed
Looks good, let's 🚢

2020-11-23 11:42 UTC, merged