Refactor Modal component.
google/site-kit-wp pull request #2321
Opened 2020-11-04 16:34 UTC by kostyalmm

## Summary

Addresses issue #2193

## Relevant technical choices

Refactors Modal component to be functional component.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-11-04 21:14 UTC, felixarntz requested changes
@kostyalmm Pretty much LGTM, just the old file still needs to be removed.

Also, can you add a QA Brief to the issue please?

2020-11-04 21:14 UTC, felixarntz commented on assets/js/components/modal.js
> +import { createPortal, useEffect, useState } from '@wordpress/element';
I think this file was accidentally kept. It should be removed in favor of `Modal.js`.

2020-11-04 21:14 UTC, felixarntz commented on assets/js/components/Modal.js
> +	}, [] );
This looks good as far as I can tell. @tofumatt Would be great to get your review here as well.

2020-11-09 16:48 UTC, eugene-manuilov approved these changes

2020-11-10 00:48 UTC, felixarntz approved these changes
Great!

2020-11-10 02:07 UTC, merged