Remove publisher wins. Proof-of-concept.
google/site-kit-wp pull request #2417
Opened 2020-11-24 00:06 UTC by tofumatt

## Summary

Addresses issue #2285.

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-12-07 19:30 UTC, kostyalmm commented
@tofumatt I am not quite sure what else to do with this PR 🤔 
Seems that all the tasks mentioned in the IB are already done. I removed the story as it was remaining. We can't remove the CSS yet as it is used in other win notifications.

What else would you like me to do in this?

2020-12-09 21:59 UTC, tofumatt commented
@kostyalmm I think you're right and that's it—the story seems to be the only thing left out of the PR that I can tell from a quick look.

I don't think there's much else to do on this PR, so assigning it to @felixarntz, @aaemnnosttv, or @eugene-manuilov for review is all that's needed. Writing the IB on this one meant finding a lot of the code to remove and ended up warranting the draft PR. I guess there's less left to do here than expected. 🙂

2020-12-10 15:49 UTC, eugene-manuilov commented
@googlebot I consent.

2020-12-10 15:55 UTC, kostyalmm commented
@tofumatt can you please consent 😄

2020-12-11 19:07 UTC, tofumatt commented
@googlebot I consent.

2020-12-11 19:08 UTC, tofumatt commented
@kostyalmm I think you need to consent; it's a bit confusing, but I think the idea is the author of the PR is assumed to be okay, but since you added commits to a PR I started you need to consent. 🙂

2020-12-12 07:15 UTC, kostyalmm commented
@googlebot I consent.

2020-12-15 19:11 UTC, eugene-manuilov requested changes
Thanks, @tofumatt! Overall it looks good but I think there are a few more things to delete or update:

* [WinsWithData](https://github.com/google/site-kit-wp/blob/publisher-wins-2285/assets/js/components/legacy-notifications/wins-withdata.js) class is not needed anymore
* Comments [here](https://github.com/google/site-kit-wp/blob/publisher-wins-2285/assets/js/components/legacy-notifications/util.js#L38) and [here](https://github.com/google/site-kit-wp/blob/publisher-wins-2285/assets/js/components/data/index.js#L85) need to be updated.

2020-12-16 20:12 UTC, eugene-manuilov approved these changes
LGTM!

2020-12-22 01:30 UTC, felixarntz requested changes

2020-12-22 01:30 UTC, felixarntz commented on stories/notifications.stories.js
>  	.add( 'Total Stats', () => (
There are a few more stories to remove here. Most of the ones below here are also publisher wins - they basically replicate the UI the publisher wins code removed would have resulted in. (Probably the production logic was too complicated to rely on for Storybook - good to get that removed finally. 😆)

2020-12-22 03:06 UTC, felixarntz approved these changes
LGTM! So much red 😍

2020-12-22 03:06 UTC, merged