Update webpack config
google/site-kit-wp pull request #2523
Opened 2020-12-11 08:24 UTC by asvinb

## Summary

Addresses issue #2344 

## Relevant technical choices
- Add hash only when in production mode

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-12-11 16:32 UTC, tofumatt approved these changes

2020-12-14 22:44 UTC, felixarntz requested changes
I think this PR misses one specific instance, which is the `googlesitekit-vendor` file which currently still receives the hash in a development build (see the `googlesitekit-vendor.[contenthash].js` in the Webpack config).

We'll need to add a similar change there so that the hash is only added for production.

2020-12-15 10:04 UTC, asvinb commented
> I think this PR misses one specific instance, which is the `googlesitekit-vendor` file which currently still receives the hash in a development build (see the `googlesitekit-vendor.[contenthash].js` in the Webpack config).
> 
> We'll need to add a similar change there so that the hash is only added for production.

Updated @felixarntz

2021-01-11 21:52 UTC, felixarntz approved these changes
Great!

2021-01-11 21:52 UTC, merged