Implement DimensionTabs component.
google/site-kit-wp pull request #2530
Opened 2020-12-15 11:50 UTC by kostyalmm

## Summary

Addresses issue #2424

## Relevant technical choices

* Implement DimensionTabs component.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-12-15 12:37 UTC, eugene-manuilov requested changes
Thanks, @kostyalmm! Mostly looks good to me, just added a few minor comments to address. Could you please check it?

2020-12-15 12:37 UTC, eugene-manuilov commented on assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/DimensionTabs.js
> +import TabBar from '@material/react-tab-bar';
Let's put external dependencies to be above wp dependencies:

```suggestion
/**
 * External dependencies
 */
import Tab from '@material/react-tab';
import TabBar from '@material/react-tab-bar';

/**
 * WordPress dependencies
 */
import { useCallback } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
```

2020-12-15 12:37 UTC, eugene-manuilov commented on assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/DimensionTabs.js
> +	const dimensionName = useSelect( ( select ) => select( CORE_FORMS ).getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionName' ) || 'ga:channelGrouping' );
@kostyalmm this is not mentioned in the IB but let's get the `dimensionName` variable from the parent component which also pulls it from the datastore. Let's do it like it's done for `TotalUserCount` and `UserCountGraph` components.

2020-12-15 12:37 UTC, eugene-manuilov commented on assets/sass/widgets/_googlesitekit-widget-analyticsAllTrafficV2.scss
> + * Site Kit by Google, Copyright 2019 Google LLC
```suggestion
 * Site Kit by Google, Copyright 2020 Google LLC
```

2020-12-15 13:42 UTC, eugene-manuilov submitted a review, later dismissed
Awesome! Thanks.

2020-12-22 22:53 UTC, felixarntz approved these changes
Awesome!

2020-12-22 23:13 UTC, merged