Enhancement/2428 source link
google/site-kit-wp pull request #2531
Opened 2020-12-15 12:27 UTC by asvinb

## Summary

Addresses issue #2428 

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2020-12-18 11:20 UTC, eugene-manuilov requested changes
@asvinb overall it looks good to me. Just added one suggestion and it's ready to go.

2020-12-18 11:20 UTC, eugene-manuilov commented on assets/js/modules/analytics/datastore/service.js
> +		path += '/';
```suggestion
		let path = escapeURI`/report/${ type }/a${ accountID }w${ internalWebPropertyID }p${ profileID }/`;
		if ( argsSegment ) {
			path += escapeURI`${ argsSegment }/`;
		}
```

2020-12-18 11:23 UTC, eugene-manuilov commented
@asvinb could you please take a look at js tests too? Looks like it has stopped working after merging it with the develop branch.

2020-12-18 12:27 UTC, asvinb commented on assets/js/modules/analytics/datastore/service.js
> +		path += '/';
nice 👍

2020-12-18 13:56 UTC, eugene-manuilov approved these changes
:+1:

2020-12-22 21:06 UTC, felixarntz approved these changes
Great!

2020-12-22 22:15 UTC, merged