Use pie slice color for UserCountGraph chart line when pie slice is selected
google/site-kit-wp pull request #2643
Opened 2021-01-19 14:28 UTC by johnPhillips

## Summary

Addresses issue #2625

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-01-19 15:19 UTC, eugene-manuilov requested changes
Awesome! Thanks, @johnPhillips! All looks good to me, just added a few nit-picks to adjust formatting a little bit. Could you please fix it and I'll approve this PR?

2021-01-19 15:19 UTC, eugene-manuilov commented on assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/UserCountGraph.js
> +	const graphLineColor = dimensionColor || '#1a73e8';
Let's write it in a single line:

```suggestion
	const graphLineColor = useSelect( ( select ) => select( CORE_FORMS ).getValue( FORM_ALL_TRAFFIC_WIDGET, 'dimensionColor' ) || '#1a73e8' );
```

2021-01-19 15:19 UTC, eugene-manuilov commented on assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/DimensionTabs.js
> +		setValues( FORM_ALL_TRAFFIC_WIDGET, { dimensionName: tabs[ index ].dimensionName, dimensionValue: '', dimensionColor: '' } );
Let's split it into multiple lines to make it easier to read:

```suggestion
		setValues( FORM_ALL_TRAFFIC_WIDGET, {
			dimensionName: tabs[ index ].dimensionName,
			dimensionValue: '',
			dimensionColor: '',
		} );
```

2021-01-19 15:19 UTC, eugene-manuilov commented on assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/UserCountGraph.js
> +						1: { color: graphLineColor, lineWidth: 3, targetAxisIndex: 1 },
Same here, let's split it into multiple lines for readability purposes:

```suggestion
						1: {
							color: graphLineColor,
							lineWidth: 3,
							targetAxisIndex: 1,
						},
```

2021-01-19 15:48 UTC, johnPhillips commented
Thanks for the review @eugene-manuilov!
I made the changes you suggested, let me know if there's anything else you can see 👍

2021-01-19 16:48 UTC, eugene-manuilov approved these changes
Awesome!

2021-01-20 21:43 UTC, felixarntz approved these changes
Awesome!

2021-01-20 21:43 UTC, merged