Enhancement/2507 remove module datapoints for individual settings
google/site-kit-wp pull request #2651
Opened 2021-01-19 20:32 UTC by eugene-manuilov

## Summary

Addresses issue #2507

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-01-21 01:04 UTC, felixarntz requested changes
Mostly LGTM. There are a few minor things to clean up related to unnecessary `is_wp_error` checks mostly.

2021-01-21 01:04 UTC, felixarntz commented on includes/Modules/Analytics.php
>  					// Get the account ID from the saved settings - returns WP_Error if not set.
```suggestion
					// Get the account ID from the saved settings.
```

2021-01-21 01:04 UTC, felixarntz commented on includes/Modules/Tag_Manager.php
>  				return is_wp_error( $container_id ) || ! $container_id;
See above:
```suggestion
				return ! $container_id;
```

2021-01-21 13:27 UTC, eugene-manuilov commented on includes/Modules/AdSense.php
>  				}
Ok, removed it.

2021-01-21 13:27 UTC, eugene-manuilov commented on includes/Modules/AdSense.php
>  		}
Updated!

2021-01-21 20:34 UTC, felixarntz approved these changes
Great!

2021-01-21 20:34 UTC, merged

2021-01-22 10:29 UTC, aaemnnosttv commented
![more-red-than-green](https://user-images.githubusercontent.com/90871/100927615-09194580-34dd-11eb-8476-c58aa6be2903.png)