Keep row selected when changing dateRange.
google/site-kit-wp pull request #2684
Opened 2021-01-26 00:35 UTC by tofumatt

## Summary

Addresses issue #2644.

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-01-26 19:07 UTC, felixarntz requested changes
The existing code looks good, but there's one problem this introduces: We need to make sure that `selectedRow` is no longer set when changing the tab (i.e. the `dimensionName`). Right now, when I select a pie slice in e.g. "Channels" and then go over to "Locations", there will still be a slice initially selected (I guess the one with the same row index or something?). That should not be the case, the selection should only persist within the same dimension's pie chart.

We should reset `selectedRow` when changing tabs.

2021-01-26 20:04 UTC, tofumatt commented
Ah right, I missed that! I've added a reset on `dimensionName` change, should be good now 👍🏻

2021-01-26 20:41 UTC, felixarntz requested changes
There still seems to be something off here, although I thought your code would fix it. When I run it, it only works sometimes.

Instead of relying on `useEffect`, wouldn't it be more reliable to unset it when switching the tab, together with the dimension? That would IMO also better clarify the intent here.

2021-01-26 22:06 UTC, felixarntz requested changes
This is still not working as expected, it's unreliable and only appears to work on initial pageload. As soon as I do a couple more interactions (change date range, change tabs, back and forth etc) it doesn't keep the pie slice for the same dimension value selected like it should.

I left a comment below for what I think is the underlying problem here. I don't think we need to store a new piece of information actually, since `dimensionValue` already indicates which pie slice is/should be selected. Let's try to use that one.

2021-01-26 22:06 UTC, felixarntz commented on assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidgetV2/UserDimensionsPieChart.js
> +			chart.setSelection( [ { row: selectedRow } ] );
I think the underlying problem here might be that we're selecting the `row` which is not specific enough, and it also shouldn't be necessary. We already store when a pie slice is selected, by storing the `dimensionValue` which _is_ the pie slice.

Basically, _if_ there is a (non-empty) `dimensionValue`, we need to ensure that the `row` which has that value as label (i.e. `row[ 0 ]` if I'm not mistaken) is selected.

2021-01-28 02:17 UTC, felixarntz commented
Changed this to be against `master` since a fix for this issue should preferably go into the release.

2021-01-28 18:37 UTC, felixarntz commented
Closing since this will be covered by #2702.

2021-01-28 18:37 UTC, closed without merging