Align All Traffic pie chart legend and line chart x-axis labels. (#2738)
google/site-kit-wp pull request #2770
Opened 2021-02-08 15:15 UTC by johnPhillips

## Summary

Addresses issue #2738

## Relevant technical choices
I felt that it was worth briefly investigating a CSS solution, intending to follow the IB if I couldn't find one. 

Messing around in-browser, I found that on the current release a couple of changes on the parent `.googlesitekit-widget--analyticsAllTraffic__dimensions` div lined the legends up correctly, but the issue was that in `develop` there have been [a few changes which made it less straightforward](https://github.com/google/site-kit-wp/commit/13348bdbee4a44e12b20b0760a8e570e0d98385e). 

I therefore removed them and then attempted to add them back in one at a time to get them to coexist with the changes I made. Hopefully I haven't introduced a regression, and both issues are still solved 🤞.

![Feb-08-2021 15-11-02](https://user-images.githubusercontent.com/2470911/107238666-06c4f180-6a20-11eb-87ef-6fedd3a8da91.gif)

Very happy to attempt the method in the IB if needed.

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-02-08 16:33 UTC, eugene-manuilov commented
I am not sure about this approach because it pushes the pie chart down which makes it look less natural to me. @tofumatt can you review it on your end and tell if it is okay or not?

2021-02-08 21:56 UTC, tofumatt approved these changes
When I tested this locally and compared it to `develop` the Pie Chart wasn't pushed down for me in Chrome or Firefox on macOS, and it led to everything being lined up. I much prefer the CSS-only solution, and it worked at many viewpoints.

This works for me, I think it looks good. 👍🏻

2021-02-09 16:23 UTC, aaemnnosttv requested changes
Thanks @johnPhillips – I think this can work but needs a little tweaking.

It looks good in larger viewports, but the alignment is lost at **1279px** and below, until it breaks onto two rows. This seems to be the same breakpoint where the font size of the main total users metric decreases as well.
![image](https://user-images.githubusercontent.com/1621608/107393708-c3dc4a00-6b03-11eb-9de9-b362f8da96ea.png)

2021-02-10 20:09 UTC, felixarntz commented
Superseded by #2783.

2021-02-10 20:09 UTC, closed without merging