Enhancement/942 auth proxy setup
google/site-kit-wp pull request #2809
Opened 2021-02-15 19:06 UTC by eugene-manuilov

## Summary

Addresses issue #942

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-02-17 12:12 UTC, tofumatt approved these changes
Looks good to me! 👍🏻

2021-02-18 12:57 UTC, aaemnnosttv requested changes
Thanks @eugene-manuilov – this looks great overall, there's just one thing which is missing (see below) as well as a merge conflict.

Once addressed, please double check that this works with the new user input feature.

2021-02-18 12:57 UTC, aaemnnosttv commented on includes/Core/Authentication/Google_Proxy.php
> +			'user_input_flow',
We need to update this to also include the feature which was just added here:
https://github.com/google/site-kit-wp/blob/baec79d391492896a1ac4d0b41a6c93ac67ccf5c/includes/Core/Authentication/Clients/OAuth_Client.php#L921-L924

2021-02-18 14:08 UTC, eugene-manuilov commented
@aaemnnosttv should be good now.

2021-02-19 09:40 UTC, aaemnnosttv approved these changes
LGTM, thanks!

2021-02-19 09:40 UTC, merged