Enhance adblocker detection with more robust implementation
google/site-kit-wp pull request #2882
Opened 2021-02-26 11:43 UTC by aaemnnosttv

## Summary

Addresses issue #2794 

## Relevant technical choices

* Replaces URL pattern-based adblocker detection with more robust library-based solution
* Fixes duplicate module `checkRequirements` function invocations as a result of duplicate resolver functions

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-02-26 11:56 UTC, aaemnnosttv commented on assets/js/googlesitekit/modules/datastore/modules.js
> +		if ( select( STORE_NAME ).canActivateModule( slug ) ) {
This change isn't explicitly needed by this PR but a bug I noticed during implementation.

`checkRequirements` functions were being invoked twice due to separate resolvers being used for `canActivateModule` and `getCheckRequirementsError`. Even though they use the same underlying function, the datastore will run them if present.

2021-02-26 11:56 UTC, aaemnnosttv commented on assets/js/modules/adsense/datastore/adblocker.js
> +import { detectAnyAdblocker } from 'just-detect-adblock';
Even though it uses this library here, this could easily be replaced with something else as there are a few that work very similarly. This one seems to be one of the newer ones and seems to work well. If needed we could always fork one of these as an internal package to tweak for our needs.

Part of the issue here is a proof of concept that since our use is encapsulated within the datastore and connected components, we can rely on on-demand asynchronous logic rather than running this on every page load proactively.

2021-02-26 11:56 UTC, aaemnnosttv commented on assets/js/modules/adsense/datastore/adblocker.test.js
> -				global._googlesitekitLegacyData.canAdsRun = true;
Much nicer than messing with a global 👌

2021-02-26 11:56 UTC, aaemnnosttv commented on assets/js/modules/adsense/index.js
> +	isAdBlockerActive = () => registry.__experimentalResolveSelect( STORE_NAME ).isAdBlockerActive();
Issue to fix this hack is here: https://github.com/google/site-kit-wp/issues/2749

2021-03-02 22:02 UTC, felixarntz requested changes
Excellent - just one thing more to clean up, which I'll quickly do here.

2021-03-02 22:54 UTC, felixarntz approved these changes
Excellent!

2021-03-02 22:54 UTC, merged