Fix label truncation Search Console.
google/site-kit-wp pull request #2893
Opened 2021-03-01 14:43 UTC by johnPhillips

## Summary

Addresses issue #2747

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-03-02 12:03 UTC, aaemnnosttv approved these changes
LGTM 😄  Thanks @johnPhillips !

2021-03-02 12:06 UTC, aaemnnosttv requested changes
Oops, looks like this requires VRT reference images to be updated. 
![image](https://user-images.githubusercontent.com/1621608/109646123-6fefde80-7b60-11eb-87e8-b381fcfc9587.png)

Would you please review the failures and approve the changes if they're all expected?

2021-03-02 15:08 UTC, johnPhillips commented
@aaemnnosttv mostly the VRT changes are just down to the new height on the chart, which is barely perceptible.

However, the one you shared is a change from slanted labels to stacked labels, which is happening when the 28-day range is selected on medium-large screens up to about 1400px. I'm guessing this is due to the library using the extra space to fit in some more labels. I did check for regressions like this before, so I am slightly confused as to why it's now happening. Maybe the charts library is a bit of a moving target in this regard.

| Stacked  | Slanted |
| ------------- | ------------- |
| <img width="300" alt="Screenshot 2021-03-02 at 14 46 43" src="https://user-images.githubusercontent.com/2470911/109665579-3a4df400-7b66-11eb-9ebb-0c1ffad95a3b.png"> | <img width="292" alt="Screenshot 2021-03-02 at 14 43 21" src="https://user-images.githubusercontent.com/2470911/109665131-c57aba00-7b65-11eb-8b6f-37a7eed118e0.png"> |

I've approved them because I think this is a natural side-effect of applying this change to all date ranges, rather than just the 90-day range, which is what we agreed in the IB. We also agreed that it might be best to let the library manage the labels its own way as long as the truncation was solved.

However, very happy to go back to the drawing board if you don't think this is an acceptable regression. Let me know what you think?

2021-03-03 16:53 UTC, aaemnnosttv approved these changes

2021-03-03 16:53 UTC, merged