Fix scrolling in User Input.
google/site-kit-wp pull request #2995
Opened 2021-03-19 21:50 UTC by tofumatt

## Summary

Addresses issue #2848.

## Relevant technical choices

This checks for changes to the `activeSlug` rather than `activeSlug`, because listening to changes in `activeSlugIndex` meant changes to the "Preview" screen weren't accommodated. This fixes the issues reported here: https://github.com/google/site-kit-wp/issues/2848#issuecomment-802794834

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-03-22 11:35 UTC, eugene-manuilov requested changes

2021-03-22 11:35 UTC, eugene-manuilov commented on assets/js/components/user-input/UserInputQuestionnaire.js
> +		global.document.querySelector( '#googlesitekit-user-input-container' )?.scrollIntoView( { behavior: 'smooth' } );
@tofumatt I believe it would be better to use a ref for the container element instead of relying on its ID. Could you please update it?

2021-03-23 09:39 UTC, aaemnnosttv commented
@tofumatt @eugene-manuilov I just noticed this while looking at another issue, but it seems that the scrolling is putting things in the wrong place.


https://user-images.githubusercontent.com/1621608/112125602-47418e80-8bcc-11eb-9215-be475884a028.mp4

2021-03-23 12:49 UTC, eugene-manuilov commented
> @tofumatt @eugene-manuilov I just noticed this while looking at another issue, but it seems that the scrolling is putting things in the wrong place.
> 
>  Kapture.2021-03-23.at.11.37.08.mp4

@aaemnnosttv that's a storybook styles issue and not relevant to this ticket. I'll create a follow-up PR that fixes it.

2021-03-23 13:48 UTC, eugene-manuilov approved these changes
LGTM! Thanks, @tofumatt!

2021-03-23 13:48 UTC, merged