Add isSingleSlice chart utility function.
google/site-kit-wp pull request #3085
Opened 2021-04-05 14:01 UTC by asvinb

## Summary

Addresses issue #2991 

## Relevant technical choices

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-04-06 18:46 UTC, felixarntz commented
@asvinb Please keep in mind to connect PRs to their respective issue in the future using the ZenHub UI below the PR description :)

2021-04-09 18:03 UTC, eugene-manuilov requested changes
All looks good to me. Have one minor suggestion (which I am going to apply) and this is good to go.

2021-04-09 18:03 UTC, eugene-manuilov commented on assets/js/util/chart.js
> + * @param {Object} report Report data object.
```suggestion
 * @param {Array.<Object>} report An array of report data objects.
```

2021-04-09 18:59 UTC, eugene-manuilov approved these changes
Looks good now!

2021-04-09 18:59 UTC, merged