Update to match camelcase urls in Adsense.
google/site-kit-wp pull request #3135
Opened 2021-04-13 13:52 UTC by Hazlitte

## Summary

Update to match camelcase urls in Adsense.

Addresses issue #2695 

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [X] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-04-14 13:43 UTC, eugene-manuilov requested changes
@Hazlitte in general looks good to me, but there is one more thing to implement here:

> Add test coverage for this new behaviour in determineSiteStatus.

2021-04-14 13:43 UTC, eugene-manuilov commented on assets/js/modules/adsense/util/status.js
> +		return 0 <= lowerSiteURL.indexOf( urlChannel.urlPattern );
Let's use lower cased `urlPattern` as well:

```suggestion
		return 0 <= lowerSiteURL.indexOf( urlChannel.urlPattern.toLowerCase() );
```

2021-04-14 16:21 UTC, eugene-manuilov requested changes
@Hazlitte the following is not implemented yet. Please, update tests as requested in the ticket.

> Add test coverage for this new behaviour in determineSiteStatus.

2021-04-14 16:25 UTC, Hazlitte commented
@eugene-manuilov Apologies, I didn't spot the test coverage requirement.  I'll get it done.

2021-04-15 10:55 UTC, eugene-manuilov approved these changes
Awesome! Thanks, @Hazlitte!

2021-04-15 10:55 UTC, merged