Enhancement/3356 implement generating ideas state
google/site-kit-wp pull request #3396
Opened 2021-05-24 15:44 UTC by danielgent

## Summary

Addresses issue #3356

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-05-25 18:32 UTC, eugene-manuilov requested changes
Nice work, @danielgent. This looks solid. Added a few formatting comments and one suggestion to remove the redundant `ref={}` attribute. Please, update it and I'll approve this PR.

2021-05-25 18:32 UTC, eugene-manuilov commented on assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js
> +	// THIS
```suggestion
```

2021-05-25 18:32 UTC, eugene-manuilov commented on assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js
> +	// THIS
```suggestion
```

2021-05-25 19:18 UTC, danielgent commented on assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/index.js
> +	// ADD getNewIdeas?
Ooops! :see_no_evil:

2021-05-26 11:47 UTC, eugene-manuilov approved these changes
LGTM!

2021-05-26 11:47 UTC, merged