Update to change application name if multisite is enabled.
google/site-kit-wp pull request #3487
Opened 2021-06-07 12:09 UTC by Hazlitte

## Summary

Update to change application name if multisite is enabled.

Addresses issue #3118

## Relevant technical choices

## Checklist

- [X] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [X] I have added a QA Brief on the issue linked above.
- [X] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-06-07 12:31 UTC, Hazlitte commented
Hi @eugene-manuilov, I assigned this to you because you reviewed this before.  I created a new PR because of merge conflicts on the previous one.

2021-06-07 13:27 UTC, eugene-manuilov requested changes
Thanks, @Hazlitte. Almost looks good to me. Have one comment for phpunit tests. See my message here: https://github.com/google/site-kit-wp/pull/3328#discussion_r630048649. Please, update your PR.

2021-06-07 14:27 UTC, eugene-manuilov approved these changes
Awesome! Thanks, @Hazlitte!

2021-07-12 17:39 UTC, felixarntz approved these changes
Great! This can now be merged, as the service-side piece has been completed.

2021-07-12 17:39 UTC, merged