Use wp_resource_hints to add urls to dns-prefetch directives.
google/site-kit-wp pull request #3501
Opened 2021-06-08 10:28 UTC by asvinb

## Summary

Addresses issue #2203 

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-06-11 11:48 UTC, eugene-manuilov requested changes
Thanks, @asvinb. It looks okay, but we still need to add DNS prefetch for the Analytics module tag.

Plus, I think we can extract the common functionality into a trait class to reduce duplicate code.  Let's create a new `includes/Core/Tags/Tag_With_DNS_Prefetch_Trait.php` with the following trait:

```php
trait Tag_With_DNS_Prefetch_Trait {
    protected function get_dns_prefetch_hints_callback( $url ) {
        return function( $urls, $relation_type ) use ( $url ) {
            if ( 'dns-prefetch' === $relation_type ) {
                $urls[] = $url;
            }
            return $urls;
        };
    }
}
```

Then add this trait to AdSense, Analytics and TagManager tags and register `wp_resource_hints` filters:

```php
add_filter(
    'wp_resource_hints',
    $this->get_dns_prefetch_hints_callback( '//www.googletagmanager.com' ),
    10,
    2
);
```

2021-06-14 09:18 UTC, asvinb commented
> Thanks, @asvinb. It looks okay, but we still need to add DNS prefetch for the Analytics module tag.
> 
> Plus, I think we can extract the common functionality into a trait class to reduce duplicate code. Let's create a new `includes/Core/Tags/Tag_With_DNS_Prefetch_Trait.php` with the following trait:
> 
> ```
> trait Tag_With_DNS_Prefetch_Trait {
>     protected function get_dns_prefetch_hints_callback( $url ) {
>         return function( $urls, $relation_type ) use ( $url ) {
>             if ( 'dns-prefetch' === $relation_type ) {
>                 $urls[] = $url;
>             }
>             return $urls;
>         };
>     }
> }
> ```
> 
> Then add this trait to AdSense, Analytics and TagManager tags and register `wp_resource_hints` filters:
> 
> ```
> add_filter(
>     'wp_resource_hints',
>     $this->get_dns_prefetch_hints_callback( '//www.googletagmanager.com' ),
>     10,
>     2
> );
> ```

Nice! I didn't know about that. PR updated, can you check?

2021-06-14 10:42 UTC, eugene-manuilov requested changes
Looks good to me. Thanks, @asvinb. There are a few formatting issues that I'll apply and then I'll approve this PR.

2021-06-14 10:42 UTC, eugene-manuilov commented on includes/Core/Tags/Tag_With_DNS_Prefetch_Trait.php
> +	/**
```suggestion
trait Tag_With_DNS_Prefetch_Trait {

	/**
```

2021-06-14 10:42 UTC, eugene-manuilov commented on includes/Core/Tags/Tag_With_DNS_Prefetch_Trait.php
> +}
```suggestion
	}

}
```

2021-06-14 10:42 UTC, eugene-manuilov commented on includes/Core/Tags/Tag_With_DNS_Prefetch_Trait.php
> +	 * Adds the dns-prefetch directive to a specified URL.
```suggestion
	 * Gets a callback that can be used for the wp_resource_hints filter to set the dns-prefetch directive for a specified URL.
```

2021-06-14 11:12 UTC, eugene-manuilov approved these changes

2021-06-14 11:12 UTC, merged