Update to always return AMP_MODE_SECONDARY.
google/site-kit-wp pull request #3504
Opened 2021-06-08 12:41 UTC by Hazlitte

## Summary

Update to always return AMP_MODE_SECONDARY.

Addresses issue #2998

## Relevant technical choices

## Checklist

- [X] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [X] I have added a QA Brief on the issue linked above.
- [X] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-06-11 11:32 UTC, tofumatt commented
@Hazlitte Just a reminder to flag the PRs as "ready for review" once they're moved into the Code Review column, or the E2E tests and many other checks won't run. Thanks!

2021-06-11 11:50 UTC, tofumatt requested changes
Looks like the E2E AMP tests are failing as we now should never return `AMP_MODE_PRIMARY` as a mode.

I'm a bit surprised that this test isn't failing: https://github.com/google/site-kit-wp/blob/80868c0780a1d9febc153adadea50617624a22db/tests/phpunit/includes/TestCase.php#L166-L179

Given, from what I can tell, we should never return this mode anymore: https://github.com/google/site-kit-wp/blob/80868c0780a1d9febc153adadea50617624a22db/includes/Context.php#L28-L34

In fact, it might be worth adding a comment to the `const AMP_MODE_PRIMARY = 'primary';` declaration that this mode is currently unused because of this issue.

2021-06-14 20:04 UTC, tofumatt requested changes
There are a few tests that reference `get_amp_primary_context`, which we no longer use. I suppose they're fine to leave in, but just noting it.

Please test these changes with and without the AMP plugin installed, as when it's installed and enabled an error is thrown.

It would be good to test with a pre-2.0 version of the AMP plugin as well, obtained from https://wordpress.org/plugins/amp/advanced/

2021-06-15 09:27 UTC, Hazlitte commented on includes/Context.php
> -
@tofumatt Thank you, I didn't spot that.

2021-06-15 10:00 UTC, closed without merging