Bug/3549 continue to preselect second property
google/site-kit-wp pull request #3632
Opened 2021-06-25 11:45 UTC by eugene-manuilov

## Summary

Addresses issue #3549 

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-07-12 11:27 UTC, aaemnnosttv requested changes
Thanks @eugene-manuilov – this looks good to me and works well in my testing.

Just a few points to address, mainly around the use of fetch mocks instead of using the respective `receiveGet*` actions for tests that aren't specifically testing a resolver as is our convention. This should be quick to change though, so this should be mostly good to go 👍

2021-07-12 11:27 UTC, aaemnnosttv commented on assets/js/modules/analytics/datastore/profiles.test.js
> +				} );
Please use `receiveGet*` actions instead 🙂

2021-07-13 11:35 UTC, aaemnnosttv reviewed
Thanks @eugene-manuilov – this looks good, there are just a few instances left over where I didn't specifically reference the use of fetch mock where it should use receive actions instead. I think they're all annotated now, but please apply the same to any remaining instances that aren't specifically commented on according to the same convention. Thanks!

2021-07-13 11:35 UTC, aaemnnosttv commented on assets/js/modules/analytics-4/datastore/properties.test.js
> +				fetchMock.getOnce( webDataStreamsBatchEndpoint, {
Please use `receiveGet*` actions instead of fetch mock here as well 🙂

2021-07-13 11:35 UTC, aaemnnosttv commented on assets/js/modules/analytics-4/datastore/properties.test.js
> +				fetchMock.getOnce( propertiesEndpoint, {
See above

2021-07-13 11:35 UTC, aaemnnosttv commented on assets/js/modules/analytics/datastore/properties.test.js
> +				fetchMock.get( propertiesProfilesEndpoint, {
Here as well 🙂

2021-07-13 11:35 UTC, aaemnnosttv commented on assets/js/modules/analytics/datastore/properties.test.js
> +				fetchMock.get( propertiesProfilesEndpoint, {
See above

2021-07-13 11:35 UTC, aaemnnosttv commented on assets/js/modules/analytics/datastore/properties.test.js
> +				fetchMock.get( propertiesProfilesEndpoint, { body: fixtures.propertiesProfiles } );
This should stay 😄

2021-07-13 12:43 UTC, eugene-manuilov commented on assets/js/modules/analytics-4/datastore/properties.test.js
> +				fetchMock.getOnce( propertiesEndpoint, {
Updated.

2021-07-13 12:43 UTC, eugene-manuilov commented on assets/js/modules/analytics/datastore/properties.test.js
> +				fetchMock.get( propertiesProfilesEndpoint, {
Updated.

2021-07-13 12:43 UTC, eugene-manuilov commented on assets/js/modules/analytics/datastore/properties.test.js
> +				fetchMock.get( propertiesProfilesEndpoint, {
Updated.

2021-07-13 12:44 UTC, eugene-manuilov commented
@googlebot I fixed it.

2021-07-13 12:45 UTC, eugene-manuilov commented
@aaemnnosttv looks like you also need to say `@googlebot I fixed it.` to get `cla` fixed

2021-07-13 12:47 UTC, aaemnnosttv commented
@googlebot I fixed it.

2021-07-13 17:00 UTC, aaemnnosttv approved these changes
Great, thanks!

2021-07-13 17:05 UTC, merged