Enhancement/3531 user feedback survey 300ms
google/site-kit-wp pull request #3665
Opened 2021-07-02 15:41 UTC by danielgent

## Summary

Addresses issue #3531

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-07-02 15:43 UTC, danielgent commented on assets/js/components/surveys/__fixtures__/index.js
> +				question_ordinal: 3,
makes the UX better to play around with in storybook

2021-07-02 15:43 UTC, danielgent commented on assets/js/components/surveys/CurrentSurvey.js
> +					key={ currentQuestion.question_text }
As per my comment here https://github.com/google/site-kit-wp/issues/3531#issuecomment-873076129

2021-07-05 11:20 UTC, eugene-manuilov requested changes
Thanks, @danielgent. In general looks good to me. Left two small comments and it should be good to go. Could you please take a look at it?

2021-07-05 11:20 UTC, eugene-manuilov commented on assets/js/components/surveys/CurrentSurvey.test.js
> +		await waitFor( () =>	expect(
Please, don't use tabs within the line. We use tabs only for indentation.
```suggestion
		await waitFor( () => expect(
```

2021-07-05 11:20 UTC, eugene-manuilov commented on assets/js/components/surveys/CurrentSurvey.js
> +					key={ currentQuestion.question_text }
Nice catch! Thanks!

2021-07-05 11:20 UTC, eugene-manuilov commented on assets/js/components/surveys/CurrentSurvey.js
> +			setHasAnsweredQuestion( true );
Let's return early to reduce nesting:
```suggestion
		if ( hasAnsweredQuestion ) {
			return;
		}
		
		setHasAnsweredQuestion( true );
```

2021-07-05 12:02 UTC, danielgent commented on assets/js/components/surveys/CurrentSurvey.js
> +			setHasAnsweredQuestion( true );
That's a nice change :smile:

2021-07-05 12:42 UTC, eugene-manuilov approved these changes
Awesome! Thanks, @danielgent!

2021-07-05 12:42 UTC, merged