Enhancement/990 disable admin bar
google/site-kit-wp pull request #3750
Opened 2021-07-21 19:51 UTC by eugene-manuilov

## Summary

Addresses issue #990

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-07-22 19:53 UTC, eugene-manuilov commented
@googlebot I consent.

2021-07-27 00:41 UTC, tofumatt requested changes
Looks great. I think it'd be nice to set the Admin Bar as enabled for the Storybook stories/reference images. If it isn't a huge pain, just because it's nice when the stories/references have an "expected" default.

This also needs a QA Brief, but after that we can merge this, and I think it'll be fine to add to the release 👍🏻

2021-07-27 00:41 UTC, tofumatt commented on assets/js/components/settings/SettingsAdmin.js
>  											</span>
A bit unrelated to the changes being made, but this icon doesn't need "alt" text like this and we should remove it.

The status is already read above ("Site Kit is connected"), so this text is just floating here without context and would result in a screen reader reading: "Site Kit is connected Connected".

A follow-up issue might be better, as I see this pattern in two files in the code.

2021-07-27 00:48 UTC, tofumatt commented on assets/js/components/settings/SettingsAdmin.js
>  											</span>
Filed #3763 🙂

2021-07-27 10:52 UTC, eugene-manuilov commented
@tofumatt, storybook is updated!

2021-07-28 23:20 UTC, tofumatt approved these changes
Nice!

(The CLA error looks to be because there's a merge commit or something, it's safe to ignore.)

2021-07-28 23:21 UTC, tofumatt requested changes
Oops, can you add a QA brief first?

Then we can merge this 👍🏻

2021-07-28 23:22 UTC, tofumatt approved these changes
(Actually, I'm marking this as approved because once it has a QA Brief it's fine to merge, so if you want to merge it after the QA Brief is added that's cool, no need for me to review the code again 🙂 )

2021-07-29 11:10 UTC, merged