Feature/2681 disable auto ads
google/site-kit-wp pull request #3770
Opened 2021-07-27 15:24 UTC by asvinb

## Summary

Addresses issue #

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-07-30 17:03 UTC, eugene-manuilov requested changes
Thanks, @asvinb. In general, this looks good. Added a few minor comments. Please, take a look.

2021-07-30 17:03 UTC, eugene-manuilov commented on assets/js/modules/adsense/components/common/AutoAdExclusionSwitches.js
> +				{ __( 'Don\'t display ads for:', 'google-site-kit' ) }
```suggestion
				{ __( 'Don’t display ads for:', 'google-site-kit' ) }
```

2021-08-02 08:23 UTC, asvinb commented on includes/Modules/AdSense/Auto_Ad_Guard.php
> +		) {
👍

2021-08-02 08:24 UTC, asvinb commented on includes/Modules/AdSense/Auto_Ad_Guard.php
> +	 * @return bool|WP_Error TRUE if guarded tag can be activated, otherwise FALSE or an error.
You're right. Copy and paste 🤦

2021-08-02 08:25 UTC, asvinb commented on includes/Modules/AdSense/Auto_Ad_Guard.php
> + * Class for the AdSense tag guard.
@eugene-manuilov I checked with the other class names and none have much description. Rather the descriptions are within the methods within the class, which I think are enough? 🤔

2021-08-02 08:25 UTC, asvinb commented on tests/phpunit/integration/Modules/AdSense/Auto_Ad_GuardTest.php
> +	public function test_cant_activate() {
👍

2021-08-02 08:25 UTC, asvinb commented on includes/Modules/AdSense.php
> +			$tag->use_guard( new Auto_Ad_Guard( $this->get_settings() ) );
Good catch!

2021-08-02 08:25 UTC, asvinb commented on assets/js/modules/adsense/components/settings/SettingsView.js
> +						}
👍

2021-08-02 08:25 UTC, asvinb commented on assets/js/modules/adsense/components/common/AutoAdExclusionSwitches.js
> +				{ __( 'Don\'t display ads for:', 'google-site-kit' ) }
👍

2021-08-02 10:30 UTC, eugene-manuilov requested changes
Thanks, @asvinb. It's almost there. Just have one more suggestion.

2021-08-02 10:30 UTC, eugene-manuilov commented on includes/Modules/AdSense/Auto_Ad_Guard.php
> + * Class for the AdSense tag guard.
Ok, how about something like this:
```suggestion
 * Tag guard class for the AdSense module that blocks the tag placement if it is disabled for a certain user group.
```

2021-08-02 10:30 UTC, eugene-manuilov commented on tests/phpunit/integration/Modules/AdSense/Auto_Ad_GuardTest.php
> +		);
Let's extract this repeating code into a private method and use it in all tests:

```php
private function get_auto_ad_guard( $auto_ads_disabled = array() ) {
    $settings = new Settings( new Options( new Context( GOOGLESITEKIT_PLUGIN_MAIN_FILE ) ) );
    $guard = new Auto_Ad_Guard( $settings );

    update_option( Settings::OPTION, array( 'autoAdsDisabled' => $auto_ads_disabled ) );

    return $settigns;
}

public function test_can_activate() {
    $guard = $this->get_auto_ad_guard();
    $this->assertTrue( $guard->can_activate() );
}

public function test_cant_activate_content_creators() {
    $guard = $this->get_auto_ad_guard( array( 'loggedinUsers' ) );
    ...
}

public function test_cant_activate_content_creators() {
    $guard = $this->get_auto_ad_guard( array( 'contentCreators' ) );
    ...
}
```

2021-08-03 12:10 UTC, eugene-manuilov requested changes
Awesome! Thanks, @asvinb. There is the last thing that we need to update and it should be good to go. I'll apply it by myself.

2021-08-03 12:10 UTC, eugene-manuilov commented on tests/phpunit/integration/Modules/AdSense/Auto_Ad_GuardTest.php
> +		);
This is not needed since we already set it in the `get_auto_ad_guard` method.
```suggestion
```

2021-08-03 12:11 UTC, eugene-manuilov approved these changes

2021-08-03 13:02 UTC, merged