Fix some Google charts in Safari with new date utility
google/site-kit-wp pull request #3785
Opened 2021-07-30 17:54 UTC by aaemnnosttv

## Summary

Addresses issue #3784 

## Relevant technical choices

- Took code that we were already using for parsing our date strings from an existing utility to create the new one we needed

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-07-30 17:56 UTC, aaemnnosttv commented on assets/js/modules/adsense/util/site-stats-data.js
> -	const stringToDate = ( dateString ) => new Date( `${ dateString } 00:00:00` );
This function is now replaced by the new utility.

2021-07-30 17:56 UTC, aaemnnosttv commented on assets/js/modules/search-console/util/site-stats-data.js
> -	const stringToDate = ( dateString ) => new Date( `${ dateString } 00:00:00` );
This function is now replaced by the new utility.

2021-07-30 17:56 UTC, aaemnnosttv commented on assets/js/util/date-range/string-to-date.js
> + * @since n.e.x.t
In case we include this in the release.
```suggestion
 * @since 1.38.0
```

2021-07-30 18:27 UTC, felixarntz approved these changes
Excellent!

2021-07-30 18:28 UTC, felixarntz requested changes
@aaemnnosttv Actually, while the code looks good, an e2e test is now failing.

2021-08-02 07:48 UTC, aaemnnosttv commented
@felixarntz the failure is something we've seen on other PRs too. I reran them all and they passed again so it seems to be an instability introduced in a previous PR. If that's the only concern here, then I think this should be safe to merge now 🙂

2021-08-02 17:12 UTC, wpdarren commented
@aaemnnosttv @felixarntz just confirming that I tested this (the PR using tester plugin) on search console module in Safari and switched to 7, 14, 28 and 90 days. The error message no longer appears and graphs/data is displayed.  👍

2021-08-02 19:54 UTC, felixarntz approved these changes
Great!

2021-08-02 19:54 UTC, merged