Enhancement/3773 move idea hub widget footer into widget.footer prop
google/site-kit-wp pull request #3803
Opened 2021-08-04 19:34 UTC by danielgent

## Summary

Addresses issue #3773

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-08-04 19:40 UTC, danielgent commented on assets/sass/components/idea-hub/_googlesitekit-idea-hub-dashboard-ideas-widget.scss
> +	}
This reset not mentioned in IB.  Padding is being applied to this by a `.mdc-layout-grid` class

2021-08-05 13:24 UTC, eugene-manuilov requested changes
Thanks, @danielgent. Looks good to me. Added three minor suggestions that I'll apply by myself.

2021-08-05 13:24 UTC, eugene-manuilov commented on assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Pagination.js
> +	tab: PropTypes.string,
```suggestion
	tab: PropTypes.oneOf( [ 'new-ideas', 'saved-ideas', 'draft-ideas' ] ),
```

2021-08-05 13:24 UTC, eugene-manuilov commented on assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Pagination.js
> +	}, [ page, setValue, total, uniqueKey ] );
Let's not display the pagination if there are no ideas:

```suggestion
	}, [ page, setValue, total, uniqueKey ] );

	if ( total < 1 ) {
		return null;
	}
```

2021-08-05 13:45 UTC, merged

2021-08-06 09:42 UTC, danielgent commented on assets/js/modules/idea-hub/components/dashboard/DashboardIdeasWidget/Pagination.js
> +	tab: PropTypes.oneOf( [ 'new-ideas', 'saved-ideas', 'draft-ideas' ] ),
I'm surprised these aren't constants defined somewhere :smile: 

We could also define `PropTypes.oneOf( [ 'new-ideas', 'saved-ideas', 'draft-ideas' ] )` in a constants file somewhere.  `react/prop-types` gets confused by this but we're not using that anywhere