Infrastructure/3133 update latest google charts  v51 upgrade
google/site-kit-wp pull request #3881
Opened 2021-08-16 18:35 UTC by danielgent

## Summary

Addresses issue #

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-08-18 14:53 UTC, aaemnnosttv requested changes
Looks good for the most part, just a few things we might want to change - we should keep the `chartVersion` prop to the `Chart` component though.

2021-08-18 15:50 UTC, danielgent commented on assets/js/components/GoogleChart.js
> -				chartVersion="49"
Ok. Just noting that this step was mentioned explicitly in the IB.  I assumed a previous bug was called by the versions not being matched.. I'll add this prop back but set to the latest version :+1:

2021-08-18 15:52 UTC, felixarntz commented on includes/Core/Assets/Assets.php
> +						wp_add_inline_script( $handle, 'google.charts.load( "51", { packages: [ "corechart" ] } );' );
@aaemnnosttv Are we using the new `Chart` component consistently throughout now? I don't recall, but we've probably removed all usages of the old way - in that case I agree, we should get rid of the manual loading calls here and in Storybook. Good point on adding preloading still, let's do that for the Site Kit admin screens at least.

2021-08-18 16:00 UTC, danielgent commented on .storybook/preview-head.html
> +	google.charts.load( '51', {
I removed this and all the storybook tests pass so this looks good to go :+1:

2021-08-18 16:56 UTC, danielgent commented on includes/Core/Assets/Assets.php
> +						wp_add_inline_script( $handle, 'google.charts.load( "51", { packages: [ "corechart" ] } );' );
I've just removed this whole enqueue section and the e2e tests work *BUT* that's not exactly what change is being asked for with _"preloading"_ :thinking: @aaemnnosttv

2021-08-19 09:17 UTC, aaemnnosttv commented on includes/Core/Assets/Assets.php
> +						wp_add_inline_script( $handle, 'google.charts.load( "51", { packages: [ "corechart" ] } );' );
@felixarntz we only have the one `GoogleChart` component for a while now which uses the React `Chart` within so unless we're manually creating a chart somewhere then it should be all using the same component. I can't think of any exceptions to this so I think we should be safe.

```
8 results - 8 files

assets/js/components/MiniChart.js:
  74: 			<GoogleChart

assets/js/components/Sparkline.js:
  73: 			<GoogleChart

assets/js/modules/adsense/components/module/ModuleOverviewWidget/Stats.js:
  135: 					<GoogleChart

assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserCountGraph.js:
  188: 			<GoogleChart

assets/js/modules/analytics/components/dashboard/DashboardAllTrafficWidget/UserDimensionsPieChart.js:
  471: 				<GoogleChart

assets/js/modules/analytics/components/module/ModuleAcquisitionChannelsWidget/PieChart.js:
  37: 			<GoogleChart

assets/js/modules/analytics/components/module/ModuleOverviewWidget/SiteStats.js:
  84: 					<GoogleChart

assets/js/modules/search-console/components/module/ModuleOverviewWidget/Stats.js:
  131: 					<GoogleChart
```

As for preloading, this is not the right term (I always forget which one) but looking at [`wp_resource_hints`](https://developer.wordpress.org/reference/functions/wp_resource_hints/) which is what core uses, `wp_dependencies_unique_hosts` is what grabs all the hosts from enqueued styles and scripts so to preserve this, we'd only need to hook in to add `www.gstatic.com` to the list of `dns-prefetch`.

2021-08-19 16:59 UTC, felixarntz commented on includes/Core/Assets/Assets.php
> +						wp_add_inline_script( $handle, 'google.charts.load( "51", { packages: [ "corechart" ] } );' );
Thanks @aaemnnosttv, both makes sense.

2021-08-24 09:38 UTC, aaemnnosttv commented on includes/Core/Assets/Assets.php
> +						wp_add_inline_script( $handle, 'google.charts.load( "51", { packages: [ "corechart" ] } );' );
@felixarntz after digging into this a bit, it seems `wp_dependencies_unique_hosts` does not traverse dependencies, only top-level scripts and styles (those "directly" enqueued) so this dns-prefetch isn't something we currently have now even when the chart loader is printed on the page.

I'll open a new issue for us to explore this in the future but we don't need to block this one to preserve something we aren't losing 😄

2021-08-24 09:42 UTC, aaemnnosttv reviewed
LGTM, just the loader to remove as well.

2021-08-24 09:42 UTC, aaemnnosttv commented on .storybook/preview-head.html
>  <script src="https://www.gstatic.com/charts/loader.js"></script>
```suggestion
```

2021-08-24 09:44 UTC, aaemnnosttv commented
@googlebot I consent.

2021-08-24 10:04 UTC, aaemnnosttv commented
VRT failure was usual unstable Buttons test.

2021-08-24 10:04 UTC, merged