Add Badge component.
google/site-kit-wp pull request #3900
Opened 2021-08-18 09:23 UTC by asvinb

## Summary

Addresses issue #3810 

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-08-22 19:01 UTC, johnPhillips commented
@googlebot I consent.

2021-08-24 18:56 UTC, tofumatt requested changes
Looks like a tracking event was removed and I'm not sure why, but otherwise this looks good. The badges everywhere seem right to me 👍🏻

2021-08-24 18:56 UTC, tofumatt commented on assets/js/components/Badge.js
> +	<span className="googlesitekit-badge">{ label }</span>
The IB mentions using `googlesitekit__badge`, but I think `googlesitekit-badge` _is_ the more appropriate CSS class name. Just flagging that here that it's been noticed but I think this is better. 🙂

2021-08-24 18:56 UTC, tofumatt commented on assets/js/modules/idea-hub/components/dashboard/DashboardCTA.js
> -		);
Why was this removed? I don't see it mentioned in the ACs/IB, and it seems like something worth tracking—to see if users are interested in this new feature.

2021-08-24 20:51 UTC, tofumatt approved these changes

2021-08-24 20:52 UTC, tofumatt commented
@googlebot I consent.

2021-08-24 21:15 UTC, merged