Enhancement/3908 ih messaging
google/site-kit-wp pull request #3956
Opened 2021-08-28 17:29 UTC by johnPhillips

## Summary

Addresses issue #3908

## Relevant technical choices

Although in the IB I mentioned that it might be a good idea to check the styles on the 'Experimental' badge across different viewports, I found that although the heading text and badge wrap somewhat awkwardly here and there, actually there isn't a particular viewport that can be targeted to make a uniform fix.

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-08-30 10:34 UTC, eugene-manuilov requested changes
Thanks, @johnPhillips. This looks good but misses the following part from IB:

```
You will probably need to add some simple CSS for larger viewports to get the Experimental badge to display nicely with the heading, for example by adding display: inline-flex to .googlesitekit-idea-hub__title (see images below).
```

2021-08-31 14:54 UTC, johnPhillips commented
@eugene-manuilov See the `relevant technical choice` section.

A bit more context:

When I wrote the IB I noticed that occasionally, on some screen widths, the text would wrap and that meant the `Experimental` label was orphaned on a new line which looked not-quite-optimal. So I noted that some CSS might be required.

However, in development I had a more thorough look at the various screen widths and wasn't able to identify a consistent way to stop this, as it isn't a mobile / tablet / desktop issue. It can happen at any breakpoint if the width of the container is sufficient to cause the badge to wrap. So the options were:
- use `display: inline-flex` on all viewports (looks a little bit strange on mobile)
- write some extremely specific, whack-a-mole media queries to target the few precise widths where the badge wraps (at a given font size etc)
- do nothing and accept that occasionally the badge will wrap.

That was the logic. I'm very happy to revisit this, but didn't want to spend too long on it as it felt quite marginal.

Let me know what you think?

2021-08-31 15:39 UTC, eugene-manuilov commented
@johnPhillips if we leave it as is, it will continue looking ugly on smaller screens. For example:

![2021-08-31_18-36](https://user-images.githubusercontent.com/873049/131532733-14f8702d-5cb8-4441-9c08-ddf0414a965f.png)

We can fix it by using `display: flex; justify-content: space-between; align-items: flex-start;` (like you said) styles for the `<h3>` title and it will look much better:

![2021-08-31_18-37](https://user-images.githubusercontent.com/873049/131532908-319ba35d-c35d-432e-9fe4-92b1667321b2.png)

2021-08-31 16:13 UTC, johnPhillips commented
@eugene-manuilov I'm happy to add that - just to flag again that it isn't really about device width. 

For example, on very wide desktops (~1400px), we also see the issue. Adding the fix can cause the last word of the heading to be orphaned in the same way the badge was, so it still looks slightly strange:

| As-is | with `display: inline-flex` |
| --- | --- | 
| ![Screenshot 2021-08-31 at 17 03 08](https://user-images.githubusercontent.com/2470911/131537907-07bae1e9-f6cd-4814-a04f-ccd76014f710.png) | ![Screenshot 2021-08-31 at 17 03 21](https://user-images.githubusercontent.com/2470911/131537913-e11059c4-fb97-40a7-ade5-4664642c74df.png) | 

On smaller viewports (~375px), it looks fine because the badge is inline and the text wraps. However, adding the fix makes for a slightly strange 2 column layout:

| As-is | with `display: inline-flex` |
| --- | --- | 
| ![Screenshot 2021-08-31 at 17 02 25](https://user-images.githubusercontent.com/2470911/131538032-d9cbd91d-e6ca-409e-83c8-ddedc344a98b.png) | ![Screenshot 2021-08-31 at 17 02 05](https://user-images.githubusercontent.com/2470911/131538030-74a45224-6d28-42e7-aa6e-91deaee0811b.png) |

I did spend a bit of time looking at this on Friday and couldn't find a simple way to make it look good every time, so just wanted to make my thought process clear. 

Again, very happy to add the rule - your call 👍

2021-08-31 17:08 UTC, eugene-manuilov approved these changes
Ok, I think I am going to approve it without CSS changes because this is out-of-scope for this ticket. Thanks, @johnPhillips.

2021-08-31 17:08 UTC, eugene-manuilov commented
We can address styles in a separate ticket in the future.

2021-08-31 17:08 UTC, merged