Enhancement/3938 idea tracking
google/site-kit-wp pull request #3979
Opened 2021-09-01 14:46 UTC by eugene-manuilov

## Summary

Addresses issue #3938

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-09-08 18:09 UTC, felixarntz requested changes
@eugene-manuilov Mostly looks solid, just a few minor points of feedback.

2021-09-08 19:44 UTC, eugene-manuilov commented on includes/Modules/Idea_Hub.php
> +		}
Updated.

2021-09-08 19:45 UTC, eugene-manuilov commented on includes/Modules/Idea_Hub.php
> +		}
Ok, updated.

2021-09-08 19:46 UTC, eugene-manuilov commented on includes/Modules/Idea_Hub.php
> +			if ( ! empty( $uri ) && is_string( $uri ) ) {
Yep, doesn't seem to be needed. Removed.

2021-09-08 19:52 UTC, eugene-manuilov commented on includes/Modules/Idea_Hub.php
> +				$uri = untrailingslashit( $this->context->get_reference_site_url() ) . $uri;
Without using the reference site URL here, I get the following error:

```json
{
  "error": {
    "code": 400,
    "message": "Uri is not subpath of creator uri",
    "errors": [
      {
        "message": "Uri is not subpath of creator uri",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

That's why I added this code to make sure the reference site URL is included in the post URL.

2021-09-16 00:44 UTC, felixarntz approved these changes
Great!

2021-09-16 01:43 UTC, merged