Enhancement/4182 refresh tokens on sitekit pages
google/site-kit-wp pull request #4190
Opened 2021-10-05 15:06 UTC by eugene-manuilov

## Summary

Addresses issue #4182

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-10-05 18:00 UTC, aaemnnosttv requested changes
Thanks @eugene-manuilov – this is very close, just a small change left to make regarding the change to the hook used in one instance.

2021-10-05 18:18 UTC, eugene-manuilov commented on includes/Core/Authentication/Authentication.php
> +			'admin_init',
:man_facepalming: Good catch, @aaemnnosttv. Updated.

2021-10-05 19:12 UTC, felixarntz approved these changes
LGTM! Using `current_screen` instead of `admin_init` should work as expected. Even in the unlikely scenario that it might be invoked again, we won't refresh the token again since that would have already happened before.

2021-10-06 07:07 UTC, aaemnnosttv approved these changes
Great, thanks @eugene-manuilov 👍

2021-10-06 07:08 UTC, merged