Add EntitySearchInput Component
google/site-kit-wp pull request #4261
Opened 2021-10-23 00:49 UTC by kuasha420

## Summary

Addresses issue #4049 

## Relevant technical choices

## Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-10-30 00:31 UTC, kuasha420 commented on assets/js/components/EntitySearchInput.js
> +			}
Hi, initially I implemented the `Enter` key functionality like [this](https://github.com/google/site-kit-wp/pull/4261/commits/221752df0563c7aaec93961774814f0809303f59) but it was kind of a mess, so I have reverted that one and done the current iteration. However, I had to 

* deviate from the IB and put the `onKeyDown` function to the `PostSearcherAutoSuggest` component 
* and pass `onClose` as the prop from the `EntitySearchInput` component.

Let me know which one you prefer. 

Another thing I noticed is, if the searchTerm is not yet debounced and API request is not complete, pressing `Enter` will do nothing, even if the searchTerm is a exact match. Is that something we should handle with lots of duplicate code or leave as is? 

Cheers.

2021-11-01 15:37 UTC, eugene-manuilov requested changes
Thanks, @kuasha420. Just one more comment and should be good.

2021-11-01 15:37 UTC, eugene-manuilov commented on assets/js/components/PostSearcherAutoSuggest.js
> +				return onSelectCallback( searchTerm );
@kuasha420 we also need to update the `onSelectCallback` callback to make it case-insensative:

```js
const foundMatch = results.find(
	( post ) =>
		post.post_title.toLowerCase() === value.toLowerCase()
);
```

2021-11-01 15:38 UTC, eugene-manuilov commented on assets/js/components/EntitySearchInput.js
> +			}
> Another thing I noticed is, if the searchTerm is not yet debounced and API request is not complete, pressing Enter will do nothing, even if the searchTerm is a exact match. Is that something we should handle with lots of duplicate code or leave as is?

I think this is fine for now.

2021-11-01 15:45 UTC, eugene-manuilov commented
@kuasha420 could you please also add the pointer cursor to the search results styles?

2021-11-02 14:13 UTC, eugene-manuilov approved these changes
LGTM! Thanks, @kuasha420.

2021-11-02 16:01 UTC, kuasha420 commented
@eugene-manuilov fixed the conflicts. Thanks.

2021-11-02 16:37 UTC, eugene-manuilov approved these changes

2021-11-02 16:37 UTC, merged