Enhancement/4106 loading state on secondary ga4 dropdown
google/site-kit-wp pull request #4296
Opened 2021-10-29 18:10 UTC by eugene-manuilov

## Summary

Addresses issue #4106

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-10-31 23:27 UTC, tofumatt requested changes
Looks good, but can you add a QA Brief for this issue?

2021-11-01 09:57 UTC, eugene-manuilov commented
@tofumatt QAB is added.

2021-11-01 23:41 UTC, tofumatt requested changes
It looks like there's a merge conflict here that needs resolving.

Regarding the QA brief: it might be missing some steps? I wasn't able to see a secondary dropdown as mentioned in the issue when doing Analytics setup with or without GA4setup enabled. I see this in the settings, when switching accounts:

![2021-11-01 23 39 43](https://user-images.githubusercontent.com/90871/139756356-51a4c68e-45df-406c-ac07-a210158936fe.gif)

Is something wrong with my build or am I missing a step to get to the point where this scenario comes up?

2021-11-02 11:47 UTC, eugene-manuilov commented
@tofumatt you need to disconnect the Analytics module and setup it again with UA+GA4 properties selected. Then you will see GA4 dropdown in the settings form and will be able to observe the progress bar for the GA4 dropdown.

Merge conflict is resolved.

2021-11-02 12:07 UTC, eugene-manuilov commented on assets/js/components/Header.stories.js
> +import UserInputSuccessBannerNotification from './notifications/UserInputSuccessBannerNotification';
I have had to make these changes after merging the develop branch into mine.

2021-11-02 13:04 UTC, tofumatt approved these changes
Thanks for the extra context on the QA process. Got it working and looks good, so I'll get this merged as soon as all of the E2E tests run. 👍🏻

2021-11-02 13:56 UTC, merged