Keep the Chip selected on page refresh.
google/site-kit-wp pull request #4394
Opened 2021-11-23 05:32 UTC by kuasha420

## Summary

Addresses issue #4053 

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2021-11-23 15:14 UTC, eugene-manuilov requested changes

2021-11-23 18:28 UTC, kuasha420 commented on assets/js/components/DashboardNavigation.js
> +	useEffect( () => {
Applied your suggestion and now it seems to be working correctly. Yay.

2021-11-23 18:35 UTC, eugene-manuilov commented
@kuasha420 could you please resolve merge conflicts?

2021-11-24 11:50 UTC, eugene-manuilov approved these changes
LGTM. Thanks, @kuasha420!

2021-11-24 11:50 UTC, merged