Add ModuleSetupFooter component.
google/site-kit-wp pull request #4671
Opened 2022-01-18 14:55 UTC by asvinb

## Summary

Addresses issue:

- #1045 

## Relevant technical choices

## Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

2022-01-20 16:24 UTC, eugene-manuilov requested changes
Great work, @asvinb. Looks good to me in general. Added a few minor comments with some suggestions. Please, take a look.

2022-01-20 17:32 UTC, asvinb commented on assets/js/components/setup/ModuleSetupFooter.js
> +export default function ModuleSetupFooter( { module, onCancelButtonClick } ) {
Sure thing! Updated!

2022-01-20 17:33 UTC, asvinb commented on assets/js/components/setup/ModuleSetupFooter.js
> +			<Grid>
Unfortunately there are some existing CSS rules which will break the layout and require some further tweaks to the CSS. I suggest we leave it like that, unless you are very keen on removing that extra wrapper :) Let me know

2022-01-20 17:33 UTC, asvinb commented on assets/js/components/setup/ModuleSetupFooter.js
> +		slug: PropTypes.string.isRequired,
Good catch!

2022-01-20 17:33 UTC, asvinb commented on assets/js/components/setup/ModuleSetupFooter.test.js
> + * Site Kit by Google, Copyright 2021 Google LLC
👍

2022-01-20 17:33 UTC, asvinb commented on assets/js/components/setup/ModuleSetupFooter.js
> + * Site Kit by Google, Copyright 2021 Google LLC
👍

2022-01-21 15:59 UTC, eugene-manuilov commented on assets/js/components/setup/ModuleSetupFooter.js
> +			<Grid>
Ok, that's fine, just wondered if we could combine those :smile: Thanks, @asvinb.

2022-01-21 16:02 UTC, eugene-manuilov requested changes
Thanks, @asvinb. Looks good to me. Added one more suggestion that I'll apply by myself and then I'll approve it.

2022-01-21 16:03 UTC, eugene-manuilov approved these changes

2022-01-21 16:17 UTC, eugene-manuilov requested changes
Found one more occurrence of the `onCancelButtonClick` property. I will update it.

2022-01-21 16:17 UTC, eugene-manuilov commented on assets/js/components/setup/ModuleSetupFooter.test.js
> +					onCancelButtonClick={ () => {} }
Ok, this one also need to be updated: 
```suggestion
					onCancel={ () => {} }
```

2022-01-21 17:32 UTC, eugene-manuilov approved these changes
All good now.

2022-01-21 17:32 UTC, merged