Enhance/4510 fix helper text font size new
google/site-kit-wp pull request #4679
Opened 2022-01-19 12:27 UTC by hussain-t

## Summary

Addresses issue: #4510 

## Relevant technical choices

## Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

## Screenshot
<img width="396" alt="Screenshot 2022-01-19 at 10 13 15 AM" src="https://user-images.githubusercontent.com/24408261/150100194-952777f0-a7f1-4363-a087-e63de9c42d89.png">

2022-01-20 17:25 UTC, asvinb requested changes

2022-01-20 17:25 UTC, asvinb commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
@hussain-t Looking at the VRT updates, I think the intended change by the CSS update should not affect those screens. To fix that, we have 2 solutions:

1. Either we explicitly set `p.mdc-text-field-helper-text` to be `0.75rem` which will prevent a lot of regressions.
2. Or we tweak the styles for other components so that there are no regressions. For e.g adding more specificity to the following selectors and exclude `p.mdc-dialog__lead` from setting the font size to `1rem`:
	* `.googlesitekit-settings-module p.googlesitekit-settings-module__status`
	* `.googlesitekit-settings-connect-module p.googlesitekit-settings-connect-module__text`
	* `.googlesitekit-settings-connect-module p.googlesitekit-settings-connect-module__cta`
	* `.googlesitekit-settings-module p.googlesitekit-settings-module__status`
	* `.googlesitekit-wizard-progress-step p.googlesitekit-wizard-progress-step__text`
	

@aaemnnosttv  I personally prefer the first option since we don't have VRT for all screens and it'll hard/take a lot of time to differentiate between any unwanted changes. Let me know what you think?

2022-01-21 10:03 UTC, aaemnnosttv commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
@asvinb I would be okay with styling `p.mdc-text-field-helper-text` if this issue were specific to helper-text only, but the problem is a larger one that font-size for `p` tags is interfering with Material styles, so this would not work with the current AC.

As to the VRTs, some of the changes I'm seeing are due to stylesheets for some components not including `.googlesitekit-plugin` at the top level, which all our styles should have.

Let's check for missing `.googlesitekit-plugin` (e.g. `_googlesitekit-cta-link.scss`) and see if adding those balances out the number of VRT failures and additional fixes that are needed.

2022-01-25 13:19 UTC, asvinb commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
@hussain-t Unfortunately the changes in the PR introduce more regressions. For e.g, you can compare the position of the tooltip when you hover the last button in the following story:
Your PR: https://google.github.io/site-kit-wp/storybook/pull/4679/?path=/story/components-button--vrt-story
Develop: https://google.github.io/site-kit-wp/storybook/main/?path=/story/components-button--vrt-story
Notice how it's spaced incorrectly.

I've pushed a new POC branch where I've added the `.googlesitekit-plugin` prefix only where needed.
https://github.com/google/site-kit-wp/compare/poc/4510-helper-text?expand=1
I tested locally and there don't seem to be any regressions.
@aaemnnosttv I think we can create a separate issue to update all the *.scss files to always have the `.googlesitekit-plugin` prefix and tackle the UI issues there since it can be very time consuming, especially to QA. Let me know what you think and if you're ok with it, i'll create the ticket. @hussain-t Feel free to take a look at my POC and let me know your thoughts.

2022-01-25 16:27 UTC, aaemnnosttv commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
@asvinb we can create a new issue for the correction to scss files, sure. Would that then be a prerequisite to finishing this issue or are you proposing something else?

As an aside to avoid large diffs, please prefix the first/top-level selector rather than wrap it with `.googlesitekit-plugin` (where possible). 

E.g.


```diff
- .googlesitekit-plugin {
-     .googlesitekit-wizard-progress-step {
+ .googlesitekit-plugin .googlesitekit-wizard-progress-step {
```

2022-01-26 13:37 UTC, asvinb commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
@aaemnnosttv So to finish this issue, I suggest we only add the `.googlesitekit-plugin` prefix only to files where there are regressions pertaining to the current issue, like I did in the [branch](https://github.com/google/site-kit-wp/compare/poc/4510-helper-text?expand=1) I shared. Then a separate issue will tackle making sure all SCSS files are prefixed correctly. Unless you are happy with doing it in the current ticket and we'll be way above the estimates since it'll require a lot of testing and QA.

About the large diffs, totally agree with you, however for the sake of consistency, I would prefer if we have the first/top-level selector wrapped and immediately it's clear that everything is wrapped within `.googlesitekit-plugin`. It's more obvious 😁 
Let me know what you think!

2022-01-27 17:53 UTC, aaemnnosttv commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
> So to finish this issue, I suggest we only add the .googlesitekit-plugin prefix only to files where there are regressions pertaining to the current issue, like I did in the branch I shared. Then a separate issue will tackle making sure all SCSS files are prefixed correctly. 

@asvinb would this require changing the AC or we could still complete it as defined but in a more simplified way?

---

As to the future approach, can we maybe apply the wrapping `.googlesitekit-plugin` class at a higher level so we don't need to worry about it within stylesheet partials or would that mess up logic with `&` in selectors? E.g.

```scss
.googlesitekit-plugin {
	@import "components/...";
	@import "components/...";
	@import "components/...";
	// ...
}
```

2022-01-28 14:36 UTC, asvinb commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
@EvanHerman We can still complete it as defined in a more simplified way in the sense that we don't prefix all the files for now. WE only prefix the files which are causing regressions and then we can open a new ticket to prefix all the files :)

The wrapper at a higher level is awesome! But I think this should go in a separate ticket 😁

2022-01-28 15:48 UTC, hussain-t commented on assets/sass/base/_defaults.scss
> +	p:not([class*="mdc-"]) {
Thanks @aaemnnosttv. Wrapping the `.googlesitekit-plugin` class is a great idea 👍 
As @asvinb suggested let's do that in a separate ticket.

2022-02-01 08:37 UTC, asvinb approved these changes

2022-02-01 09:39 UTC, aaemnnosttv approved these changes
Great, thanks all!

2022-02-01 09:41 UTC, merged