Restore Analytics CTA in Unified Dashboard Search Funnel Widget.
google/site-kit-wp pull request #4772
Opened 2022-02-02 14:19 UTC by tofumatt

## Summary

Addresses issue: #4771.

- #

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-02-03 10:30 UTC, aaemnnosttv commented on assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js
> +				{ isAnalyticsConnected && isAnalyticsActive && (
Connected will only be true if the module is also active so we don't need to check both here. https://github.com/google/site-kit-wp/blob/8b08f895c24403d4f7ae844f87a03dd88691098a/assets/js/googlesitekit/modules/datastore/modules.js#L787

2022-02-03 10:30 UTC, aaemnnosttv commented on assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js
> +								<Cell
I think the second `Cell` can be defined unconditionally here, only the children would need to be conditional. That would help avoid potentially having 3 half-cells at some point if the logic got off in some edge case like we've seen before.

2022-02-03 10:30 UTC, aaemnnosttv commented on assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js
> +										) }
Maybe this could be simplified using something like `whenActive( { moduleName: 'analytics', FallbackComponent, IncompleteComponent } )( Null )` ?

2022-02-03 14:18 UTC, tofumatt commented on assets/js/modules/search-console/components/dashboard/SearchFunnelWidget/index.js
> +import { Grid } from '@material-ui/core';
Hah, whoops. VSCode auto-imported it and it totally worked, so I didn't even notice 😅

2022-02-08 17:50 UTC, aaemnnosttv requested changes
Thanks @tofumatt – this works great, the only thing is that there is an added element which is doubling the grid gap within the widget.

![image](https://user-images.githubusercontent.com/1621608/153045939-27dddad0-6b8f-4339-a29f-2b3f8c4cfb3e.png)

The inner grid gap should match the widget below (shown above), essentially the same as the gap between the cells 😄

2022-02-08 18:13 UTC, aaemnnosttv approved these changes
Great, thanks @tofumatt !

2022-02-08 18:20 UTC, merged