Add GET:sites for AdSense module.
google/site-kit-wp pull request #4845
Opened 2022-02-15 09:19 UTC by asvinb

## Summary

Addresses issue:

- #4754 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-02-17 12:34 UTC, techanvil commented
Hi @asvinb, the code looks good and works well in my testing. However, the IB specifies to add tests for the new endpoint, so I'd expect to see some test coverage using `WP_REST_Request` to retrieve the endpoint, as seen in various other endpoint tests in the PHP integration suite.

I realise the other endpoints in this particular file don't have tests but maybe we can start here and backfill when we can :)

2022-02-17 12:35 UTC, techanvil requested changes
Hi @asvinb, the code looks good and works well in my testing. However, the IB specifies to add tests for the new endpoint, so I'd expect to see some test coverage using `WP_REST_Request` to retrieve the endpoint, as seen in various other endpoint tests in the PHP integration suite.

I realise the other endpoints in this particular file don't have tests but maybe we can start here and backfill when we can :)

2022-02-17 13:39 UTC, asvinb commented
Thanks @techanvil . @aaemnnosttv @eugene-manuilov Is there a reason why we don't have any PHP tests for module endpoints? I see we are only checking for the datapoints, but that's it. I wondering whether it's an oversight or there was a specific reason since none endpoints are tested.

2022-02-17 14:17 UTC, eugene-manuilov commented
@techanvil @asvinb I think the only test that we can add for the new endpoint is the one that checks that the endpoint returns the appropriate error if the request doesn't contain the `accountID` value. No need to check anything else there for now. We have some ideas on how to refactor endpoints and make them easier to test, but it's still yet to be implemented.

> Is there a reason why we don't have any PHP tests for module endpoints? I see we are only checking for the datapoints, but that's it. I wondering whether it's an oversight or there was a specific reason since none endpoints are tested.

I can't say exactly because the majority of datapoints had been already implemented before I joined the project. My hunch is that we didn't add it because of the complexity of those tests because we would need to mock a lot of functionality from the Google SDK that we use in our endpoints.

2022-02-21 08:24 UTC, asvinb commented on tests/phpunit/integration/Modules/AdSenseTest.php
> +	public function test_get_sites_no_account_ID_REST_endpoint() {
Good catch @techanvil ! Updated!

2022-02-21 08:26 UTC, asvinb commented on tests/phpunit/integration/Modules/AdSenseTest.php
> +		$request  = new WP_REST_Request( 'GET', '/' . REST_Routes::REST_ROOT . '/modules/adsense/data/sites?accountID=foo' );
I've removed the test, however I'am thinking maybe we should test for a return code other than `400` but like you said, if we are putting extra load on the servers, then we can wait.

2022-02-21 10:22 UTC, techanvil commented on tests/phpunit/integration/Modules/AdSenseTest.php
> +		$request  = new WP_REST_Request( 'GET', '/' . REST_Routes::REST_ROOT . '/modules/adsense/data/sites?accountID=foo' );
Nice one @asvinb :ok_hand:

2022-02-21 10:55 UTC, techanvil approved these changes
LGTM, nice one @asvinb

2022-02-21 13:12 UTC, eugene-manuilov approved these changes
LGTM too

2022-02-21 13:12 UTC, merged