Infrastructure/4804 update meta capabilities
google/site-kit-wp pull request #4897
Opened 2022-02-28 17:05 UTC by hussain-t

## Summary

Addresses issue:

- #4804 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-03-02 15:25 UTC, techanvil requested changes
Thanks @hussain-t, a few minor comments but also a more involved one about the JSON encoding for you to take a look at.

2022-03-03 07:55 UTC, hussain-t commented on assets/js/googlesitekit/datastore/user/permissions.js
> +				// The backend returns the meta capabilities' slug within `single-quotes'.
Thanks @techanvil that's a good catch 👍

2022-03-03 12:45 UTC, techanvil approved these changes
Thanks @hussain-t, this LGTM. There was just one super trivial comment about spacing consistency that you missed, literally just adding an empty line, so I have made this change and approved. Cheers

2022-03-03 12:53 UTC, merged

2022-03-04 04:19 UTC, hussain-t commented
Thanks @techanvil, sorry I missed that :)

2022-03-04 09:16 UTC, techanvil commented
> Thanks @techanvil, sorry I missed that :)

No worries, cheers Hussain!