Extract new global for tracking configuration.
google/site-kit-wp pull request #5340
Opened 2022-06-13 14:24 UTC by jimmymadon

## Summary

Addresses issue:

- #

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-06-15 06:37 UTC, hussain-t requested changes
Thanks, @jimmymadon. This looks good so far. However, I left a few comments for your consideration.

2022-06-15 06:37 UTC, hussain-t commented on includes/Core/Assets/Assets.php
> +		 * @since 1.2.0
Could you change it to `n.e.x.t`?
```suggestion
		 * @since n.e.x.t
```

2022-06-15 06:37 UTC, hussain-t commented on includes/Core/Assets/Assets.php
> +		 * @param array $data Base data.
```suggestion
		 * @param array $data Tracking data.
```

2022-06-15 06:37 UTC, hussain-t commented on includes/Core/Assets/Assets.php
> +		 * Filters the most basic inline data to pass to JS.
```suggestion
		 * Filters the most basic inline tracking data to pass to JS.
```

2022-06-15 06:37 UTC, hussain-t commented on .storybook/utils/resetGlobals.js
> +		isAuthenticated: false,
We have to remove `trackingEnabled` and `trackingID` from the `global._googlesitekitBaseData = {}` object since we are adding them here.

2022-06-16 16:55 UTC, hussain-t approved these changes
Thanks, @jimmymadon. LGTM 👍

2022-06-16 17:30 UTC, eugene-manuilov approved these changes
LGTM

2022-06-16 17:30 UTC, merged