Bug/5358 Fix Dashboard Sharing Settings Modal position on mobile
google/site-kit-wp pull request #5422
Opened 2022-06-23 16:33 UTC by jimmymadon

## Summary

Addresses issue:

- #5358 

## Relevant technical choices

The solution within the IB did not fully fix the issue when we scrolled a tiny bit, so that only a part of the WP Admin Bar is scrolled. In this little edge case, the `top` and `height` values of the dialog box need to be set dynamically, based on the number of pixels actually scrolled. Also used flex to stretch instead of hardcoding heights. Could potentially clean up more of the height values on the `.mdc-dialog__container` that were recently added to develop - but not sure what they were fixing so have kept them for now.

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-06-24 08:22 UTC, asvinb requested changes

2022-06-24 08:22 UTC, asvinb commented on assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.js
> +import { useWindowScroll } from 'react-use';
@jimmymadon Let's leave a line after all the external dependencies imports.

2022-06-24 08:22 UTC, asvinb commented on assets/js/components/dashboard-sharing/DashboardSharingSettingsButton.js
> +					style={ {
@jimmymadon Nice! I'am thinking maybe we should not set the styles dynamically here on larger breakpoints, i.e we just set them on small breakpoints. we can use the existing `breakpoint` value we have to decide whether or not to add those styles.

2022-06-24 08:23 UTC, asvinb commented
Nice catch @jimmymadon . You're right, the IB did not cater for when you scroll a little bit. I left a couple of comments, can you check them out and let me know what you think?

2022-06-24 09:03 UTC, makiost commented
The changes from #5360 still work as they should 👍

2022-06-24 15:17 UTC, asvinb commented
Thanks @jimmymadon !

2022-06-27 11:11 UTC, techanvil requested changes

2022-06-27 11:36 UTC, merged