Enhance/5479 add error code to base data
google/site-kit-wp pull request #5596
Opened 2022-07-21 21:55 UTC by kuasha420

## Summary

Addresses issue:

- #5479 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-07-25 11:52 UTC, jimmymadon requested changes
Thanks @kuasha420. Looks great overall - just two minor comments.

2022-07-25 11:52 UTC, jimmymadon commented on assets/js/googlesitekit/datastore/site/info.js
> +	 * @since 1.14.0
```suggestion
	 * @since n.e.x.t
```

2022-07-25 11:52 UTC, jimmymadon commented on assets/js/components/notifications/ErrorNotifications.test.js
> +		expect( container ).toHaveTextContent( 'Get help' );
Perhaps it would be nice to add an assertion to check the Link's URL (errorTroubleshootingLinkURL) as well?

2022-07-26 08:51 UTC, jimmymadon approved these changes
@kuasha420 Thanks for the updates - this LGTM now!

2022-07-26 10:42 UTC, techanvil approved these changes
LGTM! Nice one @kuasha420

2022-07-26 10:42 UTC, merged