Add isSiteKitScreen utility function.
google/site-kit-wp pull request #5598
Opened 2022-07-22 06:45 UTC by makiost

## Summary

Addresses issue:

- #5424 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-07-24 18:04 UTC, jimmymadon requested changes
Thanks @makiost - this looks great! Just added some very minor doc suggestions and a question on using lodash.

2022-07-24 18:04 UTC, jimmymadon commented on assets/js/util/is-site-kit-screen.js
> + * @param {string} viewContext THe view-context.
```suggestion
 * @param {string} viewContext The view-context.
```

2022-07-24 18:04 UTC, jimmymadon commented on assets/js/util/is-site-kit-screen.js
> + * Utility function to check whether or not a view-context is a site kit view.
```suggestion
 * Utility function to check whether or not a view-context is a Site Kit view.
```

2022-07-25 08:18 UTC, makiost commented on assets/js/util/is-site-kit-screen.js
> +	includes( SITE_KIT_VIEW_CONTEXTS, viewContext );
My bad, totally forgot about the vanilla includes method! 🥴

2022-07-25 11:38 UTC, jimmymadon approved these changes
Thanks @makiost - LGTM!

2022-07-25 11:49 UTC, eugene-manuilov requested changes

2022-07-25 11:49 UTC, eugene-manuilov commented on assets/js/util/is-site-kit-screen.js
> +const isSiteKitScreen = ( viewContext ) =>
Thanks, @makiost. In general, looks good to me, but could you please add js tests for this function?

2022-07-26 09:04 UTC, eugene-manuilov requested changes
Thanks for adding tests, @makiost. Added one comments to ask you to restruct tests to use the `it.each()()` approach. Please, take a look.

2022-07-26 09:04 UTC, eugene-manuilov commented on assets/js/util/is-site-kit-screen.test.js
> +	} );
We need to use `it.each( [] )()` approach to make each value a separate test:

```js
it.each( [
    [ 'VIEW_CONTEXT_DASHBOARD', VIEW_CONTEXT_DASHBOARD ],
    ...
] )( 'should return TRUE for %s screen', ( _, screen ) => {
    expect( isSiteKitScreen( screen ) ).toBe( true );
} );
```

Same applies to other tests as well.

2022-07-26 11:48 UTC, eugene-manuilov requested changes

2022-07-26 11:48 UTC, eugene-manuilov commented on assets/js/util/is-site-kit-screen.test.js
> +	} );
@makiost we need to use `it.each()()` for this test too 😄 

```js
it.each( [
    [ 'a string', 'foo' ],
    [ 'an empty object', {} ],
    [ 'a number', 1 ],
    ...
] )( 'should return FALSE for %s', ( _, screen ) => {
    expect( isSiteKitScreen( screen ) ).toBe( false );
} );
```

2022-07-26 12:04 UTC, eugene-manuilov approved these changes
Nice! Thanks, @makiost.

2022-07-26 12:18 UTC, merged