Replace all support links with ones using getDocumentationLinkURL().
google/site-kit-wp pull request #5624
Opened 2022-07-28 21:59 UTC by tofumatt

## Summary

Addresses issue:

- #5485.

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-07-29 12:05 UTC, techanvil requested changes
Looks good @tofumatt, just needs a couple of minor tweaks...

2022-07-29 12:05 UTC, techanvil commented on assets/js/components/notifications/IdeaHubPromptBannerNotification.js
> +			'using-site-kit/idea-hub'
This slug should just be `idea-hub`
```suggestion
			'idea-hub'
```

2022-08-02 22:12 UTC, tofumatt commented on assets/js/components/notifications/IdeaHubPromptBannerNotification.js
> +			'using-site-kit/idea-hub'
Oh shoot, thanks! 👍🏻

2022-08-02 22:13 UTC, tofumatt commented on assets/js/components/help/HelpMenu.js
> +					href={ documentationURL }
Hmmm… yeah, I don't like the hardcoded URL but I was wondering if this would work. Maybe this one shouldn't be changed for now 🤔

2022-08-03 16:17 UTC, techanvil commented on assets/js/components/help/HelpMenu.js
> +					href={ documentationURL }
Seems sensible for now :+1:

2022-08-03 16:19 UTC, techanvil approved these changes
LGTM! Nice one @tofumatt

2022-08-03 16:21 UTC, merged