Limit shared requests for AdSense reports to metrics and dimensions used by the Site Kit dashboard.
google/site-kit-wp pull request #5726
Opened 2022-08-23 11:21 UTC by techanvil

## Summary

Addresses issue:

- #5712 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-08-23 11:52 UTC, techanvil commented on includes/Modules/AdSense.php
> +				'ESTIMATED_EARNINGS',
As per https://github.com/google/site-kit-wp/issues/5712#issuecomment-1222341102, please take the time to double-check the codebase and verify this list of metrics.

2022-08-23 11:53 UTC, techanvil commented on includes/Modules/AdSense.php
> +				'DATE',
As per https://github.com/google/site-kit-wp/issues/5712#issuecomment-1222341102, please take the time to double-check the codebase and verify this dimension is the only one in current use.

2022-08-24 20:10 UTC, aaemnnosttv commented
@techanvil this should be ready to finish up. Please see the final changes in #5727.

2022-08-26 13:08 UTC, eugene-manuilov approved these changes
LGTM

2022-08-26 15:13 UTC, aaemnnosttv requested changes
LGTM @techanvil, just a few minor details that seem to have been missed.

2022-08-26 15:13 UTC, aaemnnosttv commented on includes/Modules/AdSense.php
> +							'invalid_analytics_report_metrics',
```suggestion
							'invalid_adsense_report_metrics',
```

2022-08-26 15:13 UTC, aaemnnosttv commented on includes/Modules/AdSense.php
> +							'invalid_analytics_report_dimensions',
```suggestion
							'invalid_adsense_report_dimensions',
```

2022-08-26 15:13 UTC, aaemnnosttv commented on includes/Modules/Analytics.php
> -			return null;
👍

2022-08-26 15:17 UTC, techanvil commented
> LGTM @techanvil, just a few minor details that seem to have been missed.

D'oh, thanks for the spot. Have applied the fixes.

2022-08-26 16:40 UTC, aaemnnosttv approved these changes
LGTM, thanks @techanvil !

2022-08-26 16:41 UTC, aaemnnosttv commented
I changed the base back to develop as the release is already set to go and this has been downgraded in priority as well.

2022-08-26 16:41 UTC, merged