Remove legacy widget area constants.
google/site-kit-wp pull request #5845
Opened 2022-09-14 21:48 UTC by sashadoes

## Summary

Addresses issue:

- #5476 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-09-15 05:33 UTC, hussain-t requested changes
@sashadoes, there are a few points to be considered:
- I can see unrelated changes to this ticket in this PR. All the changes related to `ModuleList*` are unnecessary. 
- Some of the changes mentioned in the IB weren't found. For example, deleting the related files.
- Could you add more details in the QAB, even if it's the same as the AC, that would help the QA to carry out the testing?

Thanks!

2022-09-15 05:33 UTC, hussain-t commented on assets/js/components/ModulesList.js
> - * ModulesList component.
Removing this file seems to be an unrelated change to this issue.

2022-09-15 05:33 UTC, hussain-t commented on assets/js/components/ModulesListItem.js
> - * ModulesListItem component.
Same here, removing this file seems to be an unrelated change to this issue.

2022-09-15 05:33 UTC, hussain-t commented on assets/js/googlesitekit/widgets/register-defaults.js
> +		Component: URLSearchWidget,
The `URLSearchWidget` component has to be deleted. Please refer back to the IB.

2022-09-15 05:33 UTC, hussain-t commented on stories/notifications.stories.js
> -		'Module Setup Complete',
Why do we need to remove this story?

2022-09-15 05:33 UTC, hussain-t commented on stories/modules-list.stories.js
> - * Modules List stories.
Same here; this seems to be unrelated.

2022-09-16 09:18 UTC, hussain-t requested changes
All looks good except the deletion in the `.storybook/storybook-data.js` file. @sashadoes please check my comment. Thanks!

2022-09-16 09:18 UTC, hussain-t commented on .storybook/storybook-data.js
> -	},
Why do we have to delete these lines?

2022-09-19 13:05 UTC, hussain-t approved these changes
LGTM 👍

2022-09-19 20:30 UTC, eugene-manuilov approved these changes
LGTM

2022-09-19 20:30 UTC, merged