Fix timezone Date issue.
google/site-kit-wp pull request #5880
Opened 2022-09-22 20:47 UTC by sashadoes

## Summary

Addresses issue:

- #5816 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-09-23 08:16 UTC, asvinb requested changes
@sashadoes I left some comments in the PR. Can you check them out? Thanks!

2022-09-23 08:16 UTC, asvinb commented on assets/js/components/GoogleChart.js
> +import { stringToDate } from '../util/date-range/string-to-date';
@sashadoes Please move the import within `Internal dependencies`

2022-09-23 08:16 UTC, asvinb commented on assets/js/components/notifications/BannerNotification/index.js
> +import { stringToDate } from '../../../util/date-range/string-to-date';
@sashadoes Same, let's move that import within `Internal dependencies`

2022-09-23 08:16 UTC, asvinb commented on assets/js/modules/adsense/util/index.js
> +import { stringToDate } from '../../../util/date-range/string-to-date';
@sashadoes Please add a comment for "Internal dependencies" similar to what we have in other files.

2022-09-23 08:16 UTC, asvinb commented on assets/js/modules/analytics/util/data-mock.js
>  import { MODULES_ANALYTICS } from '../datastore/constants';
@sashadoes Please move the `MODULES_ANALYTICS` and `stringToDate` imports within `Internal dependencies`

2022-09-23 08:16 UTC, asvinb commented on assets/js/modules/search-console/util/data-mock.js
> +import { stringToDate } from '../../../util/date-range/string-to-date';
Same, should be within `Internal dependencies`

2022-09-26 09:15 UTC, asvinb requested changes

2022-09-26 09:15 UTC, asvinb commented on assets/js/modules/adsense/util/index.js
> +import { stringToDate } from '../../../util/date-range/string-to-date';
@sashadoes Please move the import directly under Internal dependencies. Exports should not be under internal dependencies.

2022-09-27 08:05 UTC, asvinb commented
@sashadoes I made a small tweak: https://github.com/google/site-kit-wp/pull/5880/commits/678b5c4db1ea2becb2f386b76a8dfa62ed9c0a22 Otherwise LGTM

2022-09-27 08:05 UTC, asvinb approved these changes

2022-09-27 16:20 UTC, techanvil requested changes
Nice work here @sashadoes.

I have noticed one more place where we _could_ pass a string into a Date constructor:

https://github.com/google/site-kit-wp/blob/bbe3ba6ff1e035146cc781887befdda9cc7021a5/assets/js/util/date-range/get-date-string.js#L30-L39

At the moment, we are only using this function with `Date` instances.

However we should probably update the function to use `stringToDate` when the passed `date` arg is a string, to avoid unexpected bugs slipping through in future.

Alternatively we could update the parameter type to be `Date` rather than `string|number|Date`, I am open to suggestion. What do you think?

2022-09-28 00:51 UTC, sashadoes commented
Hi @techanvil. Thank you for this shout :)
I tried both approaches and decided to go with the last one making `getDateString` work with Date obj only. 
My top argument is that the func Signatures work better with monolithic arguments, especially as the utility function should be 'stupid', as well as that it aimed to work with Date and return a string (even from the name), plus there are no real cases in the code where we pass a string.

Please let me know if you are happy.

2022-09-28 09:03 UTC, techanvil commented
> Hi @techanvil. Thank you for this shout :) I tried both approaches and decided to go with the last one making `getDateString` work with Date obj only. My top argument is that the func Signatures work better with monolithic arguments, especially as the utility function should be 'stupid', as well as that it aimed to work with Date and return a string (even from the name), plus there are no real cases in the code where we pass a string.
> 
> Please let me know if you are happy.

Thanks @sashadoes, sounds good to me! Just a couple of small tweaks and this should be good to go.

2022-09-28 09:04 UTC, techanvil requested changes

2022-09-28 20:11 UTC, sashadoes commented
Hi @techanvil . Looking at tests more precisely reveals that `getDateString ` receives the date number (nit a Date instance) here eg -> https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/util/data-mock.js#L262 (typeof new Date().setDate() is 'number' ).

At the same time option 1 you suggest previously has to modify `stringToDate` a lot as it is designed only to work with year-month-day strings pattern. Overall, putting extra logic inside `stringToDate` to serve it for `getDateString ` feels a bit over. 

However, I feel we can rethink improvements to make it more explicit and robust, but not sure if it should be done within this ticket's scope. 

Please let me know your thoughts. Thank you.

2022-09-29 08:49 UTC, techanvil commented
Thanks @sashadoes!

> Hi @techanvil . Looking at tests more precisely reveals that `getDateString ` receives the date number (nit a Date instance) here eg -> https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/adsense/util/data-mock.js#L262 (typeof new Date().setDate() is 'number' ).

Good spot there :+1: 

> At the same time option 1 you suggest previously has to modify `stringToDate` a lot as it is designed only to work with year-month-day strings pattern. Overall, putting extra logic inside `stringToDate` to serve it for `getDateString ` feels a bit over.

I should have been a bit clearer - what I was trying to say is we could modify `getDateString`, not `stringToDate`. Specifically we could modify `getDateString` so it _calls_ `stringToDate` when passed a string:

```js
export const getDateString = ( date ) => {
	const dateInstance =
		typeof date === 'string' ? stringToDate( date ) : new Date( date );

	invariant(
		isValidDateInstance( dateInstance ),
		INVALID_DATE_INSTANCE_ERROR
	);

	// etc.
};
```

So I guess we could either update the test in `adsense/util/data-mock.js` to pass in a `Date` instance instead of a `number`, or make the change suggested above to `getDateString`.

On balance I'd go with the change to `getDateString` but happy either way.

2022-09-29 15:27 UTC, sashadoes commented
Thank you @techanvil ,🙏🏻 I see the idea. But with that solution
```js
export const getDateString = ( date ) => {
	const dateInstance =
		typeof date === 'string' ? stringToDate( date ) : new Date( date );

	invariant(
		isValidDateInstance( dateInstance ),
		INVALID_DATE_INSTANCE_ERROR
	);

	// etc.
};
```
We will have vulnerability for the strings that has a different format than year-month-day as `stringToDate` can work only with.
So we have to extend `stringToDate`  or place a rule alike: 

```js
export const getDateString = ( date ) => {
	// check format yyyy-m-d
	const checkStringFormat = new RegExp(
		'^d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])$'
	);
	const dateInstance = checkStringFormat.test( date )
		? stringToDate( date )
		: new Date( date );

	invariant(
		isValidDateInstance( dateInstance ),
		INVALID_DATE_INSTANCE_ERROR
	);

//etc...
```

What do you think?

2022-09-29 16:13 UTC, techanvil commented
Hi @sashadoes, thanks for your patience here. I should have been cognisant of the fact that `stringToDate` only works for that `YY-MM-DD` format. Sorry to have wasted a bit of time here but I guess it's all valuable learning one way or the other!

That being the case, I think the right thing to do would in fact to go back to the simplification of `getDateString` to only accept `Date` instances.

We can then update the usage of it in `assets/js/modules/search-console/util/data-mock.js` and `assets/js/modules/adsense/util/data-mock.js`.

This seems preferable to me than adding extra complexity that isn't actually needed. And it ensures we don't leave a latent bug waiting to happen. Does that sound OK to you?

2022-10-02 20:50 UTC, sashadoes commented
@techanvil No problem at all. Thank you for your time and assistance here.
Changing to our final version now 😇

2022-10-03 23:49 UTC, tofumatt approved these changes
Looks good to me 👍🏻

2022-10-03 23:52 UTC, merged

2022-10-06 19:05 UTC, aaemnnosttv reviewed
A few minor details that seem to have been missed here.

2022-10-06 19:05 UTC, aaemnnosttv commented on assets/js/modules/adsense/util/data-mock.js
> +			return getDateString( new Date( updatedMilliseconds ) );
This part is missing `stringToDate` use.

2022-10-06 19:05 UTC, aaemnnosttv commented on assets/js/modules/search-console/util/data-mock.js
> +			return getDateString( new Date( updatedMilliseconds ) );
Similar to before, this part is missing `stringToDate` use.

2022-10-06 19:19 UTC, aaemnnosttv commented
Nevermind, I misread the code and it's only copying a date instance rather than parsing a string, so this is all good 👍