Pre-fetch permissions endpoint
google/site-kit-wp pull request #5918
Opened 2022-09-27 10:14 UTC by nfmohit

## Summary

Addresses issue:

- #5772 

## Relevant technical choices

This PR prevents the permissions endpoint from being globally exposed and pre-fetches its data.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 4.7 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-10-01 00:34 UTC, tofumatt requested changes
Looks good and works well in testing. 👍🏻 

Looks like the GCP setup story has still changed unintentionally—can you check to see why that is? https://google.github.io/site-kit-wp/storybook/pull/5918/?path=/story/setup-using-gcp--step-one vs https://google.github.io/site-kit-wp/storybook/develop/?path=/story/setup-using-gcp--step-one

2022-10-01 13:12 UTC, nfmohit commented on assets/js/googlesitekit/datastore/user/permissions.js
> +	 * @since 1.82.0*
Removed, thank you!

2022-10-01 13:13 UTC, nfmohit commented
> Looks like the GCP setup story has still changed unintentionally—can you check to see why that is? https://google.github.io/site-kit-wp/storybook/pull/5918/?path=/story/setup-using-gcp--step-one vs https://google.github.io/site-kit-wp/storybook/develop/?path=/story/setup-using-gcp--step-one

Fixed the story. Thank you for the kind review, @tofumatt!

2022-10-04 00:27 UTC, tofumatt approved these changes
Looks great, awesome stuff! 😎

2022-10-04 00:27 UTC, merged