Infrastructure/5940 - Use require-await in ESLint
google/site-kit-wp pull request #6124
Opened 2022-11-09 06:19 UTC by hussain-t

## Summary

Addresses issue:

- #5940 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-11-10 11:32 UTC, asvinb commented
LGTM

2022-11-11 14:40 UTC, techanvil requested changes
Hi @hussain-t, this is looking good. I have spotted a handful of cases where the function has been left `async` and the rule disabled where it looks to be unnecessary. Please can you review these cases.

2022-11-11 14:40 UTC, techanvil commented on assets/js/googlesitekit-idea-hub-notice.js
> +// eslint-disable-next-line require-await
Hmm, it doesn't look like this function needs to be `async`, as it doesn't return anything and there's no attempt to `catch` any exception it throws where it's invoked below...

2022-11-11 14:40 UTC, techanvil commented on assets/js/googlesitekit/api/index.js
> +	// eslint-disable-next-line require-await
Doesn't look like this function needs to be `async` as `siteKitRequest` is async itself and returns a Promise.

2022-11-11 14:40 UTC, techanvil commented on assets/js/googlesitekit/datastore/user/user-input-settings.js
> +		async ( { payload: { settingID, values } } ) => {
Doesn't look like this needs to be `async` as it returns a Promise from `setItem`...

2022-11-11 14:40 UTC, techanvil commented on tests/backstop/engine_scripts/puppet/loadCookies.js
> +	// eslint-disable-next-line require-await
Doesn't look like this needs to be `async` as it returns a Promise.

2022-11-11 14:40 UTC, techanvil commented on tests/e2e/specs/modules/analytics/setup-with-account-no-tag.test.js
> +// eslint-disable-next-line require-await
Doesn't look like this needs to be `async` as `wpApiFetch` returns a Promise.

2022-11-14 18:20 UTC, techanvil approved these changes
Thanks, @hussain-t. LGTM!

2022-11-14 18:21 UTC, merged