Bug/4767 - Refactor destructuring useSelect results to fix the `Cannot read properties of undefined` JS error
google/site-kit-wp pull request #6183
Opened 2022-11-21 08:19 UTC by hussain-t

## Summary

Addresses issue:

- #4767 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-11-24 17:53 UTC, tofumatt requested changes
Overall looks good! 👍🏻 

There's a few places where the changes resulted in the selects not working as previous… one was a missing `return` value which I fixed, but there's another one where changing a value to default to an object messed with a truthy check.

Also: let's change https://github.com/google/site-kit-wp/blob/2de75e88d8d077da2153617eb7afb1352e051960/assets/js/components/user-input/UserInputApp.js#L38-L41 while we're at it. It looks like it's calling `select( CORE_USER ).getUserInputSettings()` as a side effect, so we can probably just do:

```js
const hasFinishedGettingInputSettings = useSelect( ( select ) => {
	// This needs to be called here to check on its resolution,
	// as it's called/used by child components of this component,
	// but we need to call it here to know if it's resolving.
	//
	// This is sort of a select side-effect, but it's necessary here.
	select( CORE_USER ).getUserInputSettings();

	return select(
		CORE_USER
	).hasFinishedResolution( 'getUserInputSettings' );
} );
```

After that this should be good-to-go 🙂

2022-11-28 04:49 UTC, hussain-t commented on assets/js/components/settings/SettingsRenderer.js
>  			moduleLoaded: !! module,
That's 💯. My bad, I missed it. Thanks for catching it!

2022-11-28 04:57 UTC, hussain-t commented on assets/js/components/ViewOnlyMenu/Service.js
>  	);
Yes, I was thinking of separating the calls. However, having the fallback seems cleaner as pointed out 👍

2022-11-28 04:58 UTC, hussain-t commented on assets/js/modules/analytics/components/common/PropertySelect.js
> +		select( MODULES_ANALYTICS ).isResolving( 'getProperties', [
Good catch. Thanks for fixing it!

2022-11-28 05:42 UTC, hussain-t commented
VRT is failing not due to the changes we made in the PR. However, I verified it's failing on `develop` as well.

2022-11-30 02:48 UTC, tofumatt approved these changes

2022-11-30 02:48 UTC, merged