Create WP dashboard widget to show daily uniques.
google/site-kit-wp pull request #6208
Opened 2022-11-28 13:53 UTC by sashadoes

## Summary

Addresses issue:

- #631 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-11-28 14:31 UTC, sashadoes commented
Quite not sure why VRT tests fail. I got the same on develop branch

2022-12-01 18:16 UTC, techanvil commented on assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartWidget.js
> +			ticks: dates,
The IB specifies that the x-axis should only show the first and last dates for the axis labels.

In order to achieve this, set `ticks` to be an array containing only the first and last date, and set `chartArea.left` and `chartArea.left` to `20` (or maybe a touch less) in order to provide space for the labels to render.

2022-12-01 22:00 UTC, techanvil requested changes

2022-12-01 22:00 UTC, techanvil commented on assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartWidget.js
> +		options.vAxis.viewWindow.max = 100;
This line should not be necessary if we are not showing the y-axis labels.

2022-12-01 22:00 UTC, techanvil commented on assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartWidget.js
> +		options.vAxis.viewWindow.max = undefined;
This line should not be necessary if we are not showing the y-axis labels.

2022-12-01 22:00 UTC, techanvil commented on assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartWidget.js
> +		textStyle: {
These `textStyle` and `titleTextStyle` options should not be needed if not showing the y-axis labels or title.

2022-12-02 10:50 UTC, techanvil commented on assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartWidget.js
> +	const analyticsModuleConnected = analyticsModule?.connected;
Update: Actually, I have just realised that `isModuleConnected` does a check for both the active and connected state of the module, so you should not need to use `isModuleActive` here, only `isModuleConnected`.

https://github.com/google/site-kit-wp/blob/a1327c4f3c572a326d51fc6fe5e7c695e2859f98/assets/js/googlesitekit/modules/datastore/modules.js#L1099

2022-12-03 22:56 UTC, sashadoes commented
Thank you @techanvil for your review and feedback. 
I made an update.

2022-12-05 18:39 UTC, techanvil requested changes
Thanks @sashadoes! Just one small change and I think this should be good to go.

2022-12-05 18:39 UTC, techanvil commented on assets/js/components/wp-dashboard/WPDashboardUniqueVisitorsChartWidget.js
> +		textPosition: 'none',
Please restore the `gridlines.color` setting as this is still needed for the horizontal grid lines.

```js
		gridlines: {
			color: '#eee',
		},
```

2022-12-06 13:13 UTC, merged