Enhancement/6163 update getnotifications resolver
google/site-kit-wp pull request #6302
Opened 2022-12-08 10:28 UTC by derweili

## Summary

Addresses issue:

- #6163

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-12-15 14:03 UTC, jimmymadon approved these changes
Thanks @derweili. LGTM!

2022-12-15 21:56 UTC, aaemnnosttv requested changes
Thanks @derweili – this is really close, just one thing to address.

2022-12-15 21:56 UTC, aaemnnosttv commented on assets/js/googlesitekit/data/create-notifications-store.test.js
> +		store = registry.registerStore(
Nice 👍

2022-12-15 21:56 UTC, aaemnnosttv commented on assets/js/googlesitekit/data/create-notifications-store.test.js
> +		registry = createTestRegistry();
This isn't be necessary but also, as a store composition utility we want to test in a bit more isolation than the average partial. Please keep this as before.

2022-12-17 17:05 UTC, aaemnnosttv approved these changes
LGTM, thanks @derweili !

2022-12-17 17:05 UTC, merged