Refactor module ownership or access check using a new selector
google/site-kit-wp pull request #6336
Opened 2022-12-15 23:45 UTC by kuasha420

## Summary

Addresses issue:

- #6192 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2022-12-21 10:36 UTC, hussain-t approved these changes
Nice one, @kuasha420. LGTM 👍

2022-12-21 10:42 UTC, hussain-t requested changes
@kuasha420, though no changes affect the UI or features, it’s better to test the areas that were refactored and do a smoke test. For example, the modules’ settings header and the settings edit page.  Could you add a QAB?

2022-12-21 11:32 UTC, kuasha420 commented
@hussain-t Thanks for spotting the missing QA brief. Added and moved it to MR. :+1:

2022-12-21 11:37 UTC, hussain-t approved these changes
Approved after verifying the QAB.

2022-12-21 18:13 UTC, tofumatt requested changes
Looks great, just a few comments and then this is good to go 😄

2022-12-22 19:33 UTC, kuasha420 commented on assets/js/googlesitekit/modules/datastore/modules.js
> +	 * 								 `undefined` If the state is still being resolved,
Yikes, thanks.

2022-12-22 19:34 UTC, kuasha420 commented on assets/js/googlesitekit/modules/datastore/modules.js
> +			const moduleOwnerID = select( moduleStoreName )?.getOwnerID();
Sounds Reasonable, applied!

2022-12-22 20:04 UTC, kuasha420 commented on assets/js/googlesitekit/modules/datastore/modules.js
> +			const moduleOwnerID = select( moduleStoreName )?.getOwnerID();
Hmm, turns out `select` call for a non-existent module returns `null` and not `undefined`. I have changed the check to a `null`. Let me know what you think.

2023-01-03 21:55 UTC, kuasha420 commented
@tofumatt Thank you for the review, addressed your feedback and fixed up the merge conflicts/test fails. Back to you for another look. Cheers.

2023-01-05 17:13 UTC, tofumatt approved these changes

2023-01-05 17:13 UTC, tofumatt commented on assets/js/googlesitekit/modules/datastore/modules.js
> +			}
There wasn't a test for this behaviour, but it was easy to add one so I did: 32df08712130c346b51203e1064710f73573d5a4

2023-01-05 17:36 UTC, merged