Simplify in-progress state when submitting User Input answers.
google/site-kit-wp pull request #6381
Opened 2023-01-06 13:56 UTC by sashadoes

## Summary

Addresses issue:

- #6323 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-01-11 10:46 UTC, hussain-t requested changes
Thanks, @sashadoes. The changes LGTM. However, I did a bit of testing and found the `What are your top goals for this site?` section’s checkboxes are editable (not disabled). Ideally, I think the `Edit` link should be disabled, and we shouldn’t let the users edit while submitting. WDYT?


https://user-images.githubusercontent.com/24408261/211786538-71aa8126-ba12-4199-84bf-9811908b6201.mov



cc: @aaemnnosttv

2023-01-11 16:08 UTC, sashadoes commented
@hussain-t thanks for the review and feedback. I made an update.

2023-01-11 18:50 UTC, hussain-t approved these changes
Thanks, @sashadoes. LGTM 👍

2023-01-12 15:41 UTC, eugene-manuilov requested changes
Thanks, @sashadoes. Mostly looks good to me. Added two comments for you. Please, take a look.

2023-01-12 15:41 UTC, eugene-manuilov commented on assets/js/components/user-input/UserInputPreview.js
> +									<Spinner isSaving={ isScreenLoading } />
We have the `SpinnerButton` component for this purposes. Could you please update this component to use it instead?

2023-01-12 15:41 UTC, eugene-manuilov commented on assets/js/components/user-input/CancelUserInputButton.js
> +export default function CancelUserInputButton( { disabled = false } ) {
The default state for the `disabled` property is `undefined`. Let's stick with it:
```suggestion
export default function CancelUserInputButton( { disabled } ) {
```

2023-01-13 11:30 UTC, eugene-manuilov approved these changes
LGTM

2023-01-13 11:31 UTC, eugene-manuilov requested changes
Actually, just noticed that this PR has merge conflicts. @sashadoes, could you please resolve all merge conflicts?

2023-01-13 16:34 UTC, eugene-manuilov approved these changes
Looks good now

2023-01-13 16:36 UTC, merged