Add Key_Metrics entry point classes.
google/site-kit-wp pull request #6383
Opened 2023-01-06 23:52 UTC by jimmymadon

## Summary

Addresses issue:

- #6308 

## Relevant technical choices

 - See [this comment](https://github.com/google/site-kit-wp/issues/6308#issuecomment-1373882141).
 - As for sanitising a non-boolean value for the isWidgetHidden flag, I have decided to keep it "hidden" unless the data says 'false'. I guess this is better than the opposite alternative?

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-01-12 17:25 UTC, eugene-manuilov requested changes
Thanks, @jimmymadon. All look good to me. Added a few suggestions to fix formatting issues and to simplify code blocks. Once updated, it should be good to go.

2023-01-12 17:25 UTC, eugene-manuilov commented on includes/Core/Util/Sanitize.php
> +	/**
```suggestion
class Sanitize {

	/**
```

2023-01-12 17:25 UTC, eugene-manuilov commented on includes/Core/Util/Sanitize.php
> +}
```suggestion
	}

}
```

2023-01-12 17:25 UTC, eugene-manuilov commented on includes/Core/Util/Sanitize.php
> +	 * @since n.e.x.t Moved the method its own utility class.
Let's just use @since n.e.x.t` because otherwise it is not clear from where it was moved from.
```suggestion
	 * @since n.e.x.t
```

2023-01-12 17:25 UTC, eugene-manuilov commented on includes/Core/Util/Sanitize.php
> +	public static function sanitize_string_list( $elements = array() ) {
Let's add phpunit tests for this static function since it is publicly available now.

2023-01-12 17:25 UTC, eugene-manuilov commented on includes/Core/Key_Metrics/Key_Metrics_Settings.php
> +			}
```suggestion
			if ( isset( $settings['isWidgetHidden'] ) ) {
				$sanitized_settings['isWidgetHidden'] = false !== $settings['isWidgetHidden'];
			}
```

2023-01-17 11:30 UTC, jimmymadon commented on includes/Core/Key_Metrics/Key_Metrics_Settings.php
> +			}
Nice!

2023-01-17 12:18 UTC, eugene-manuilov requested changes
Thanks, @jimmymadon. Almost looks good to me. There is one suggestion that i'll apply by myself and will approve this PR.

2023-01-17 12:18 UTC, eugene-manuilov commented on includes/Core/Key_Metrics/Key_Metrics_Settings.php
> + * Class for representing a user's dismissed items.
```suggestion
 * Class to store user key metrics settings.
```

2023-01-17 12:18 UTC, eugene-manuilov approved these changes
LGTM now.

2023-01-17 16:25 UTC, eugene-manuilov approved these changes

2023-01-17 17:29 UTC, merged

2023-01-17 17:59 UTC, jimmymadon commented on includes/Core/Key_Metrics/Key_Metrics_Settings.php
> + * Class for representing a user's dismissed items.
Thanks!