Simplify experience when additional scopes are required to view the d…
google/site-kit-wp pull request #6409
Opened 2023-01-15 00:38 UTC by sashadoes

…ashboard.

## Summary

Addresses issue:

- #5497 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-01-15 17:13 UTC, hussain-t requested changes
Thanks, @sashadoes. Overall the changes LGTM. However, I’ve left a little comment to rename a variable. Also, it would be nice to add a test case to verify the modal doesn’t appear in `assets/js/components/PermissionsModal/index.test.js`. WDYT?

2023-01-15 17:13 UTC, hussain-t commented on assets/js/components/PermissionsModal/AuthenticatedPermissionsModal.js
> +			unsatisfiedScopes.includes( i )
Can we rename it to `scope` for clarity?

```suggestion
		permissionsError?.data?.scopes.every( ( scope ) =>
			unsatisfiedScopes.includes( scope )
```

2023-01-16 14:46 UTC, hussain-t approved these changes
Thanks, @sashadoes. LGTM 👍

2023-01-16 19:55 UTC, eugene-manuilov approved these changes
LGTM

2023-01-16 19:55 UTC, merged