Add Google account details to `UserMenu`
google/site-kit-wp pull request #6501
Opened 2023-01-30 21:37 UTC by nfmohit

## Summary

Addresses issue:

- #5775 

## Relevant technical choices

This PR updates the Site Kit `UserMenu` and adds Google account details to it, similar to other Google services.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-01-31 08:17 UTC, nfmohit reviewed
Notes to Code Reviewer:

2023-01-31 08:17 UTC, nfmohit commented on assets/sass/components/global/_googlesitekit-user-menu.scss
> +		color: $c-surfaces-on-surface;
While the Figma token for this element references `GM3/sys/light/on-surface`, we do not have such a token in our codebase yet. Hence, the similar `$c-surfaces-on-surface` token is being used here.

2023-01-31 08:17 UTC, nfmohit commented on assets/sass/components/global/_googlesitekit-user-menu.scss
> +		color: $c-surfaces-on-surface;
Same as above.

2023-01-31 08:17 UTC, nfmohit commented on assets/sass/components/global/_googlesitekit-user-menu.scss
> +		color: $c-surfaces-on-surface-variant;
Same as above. Since a token like `GM3/sys/light/on-surface-variant` isn't available, the similar `$c-surfaces-on-surface-variant` is being used.

2023-01-31 17:19 UTC, eugene-manuilov approved these changes
LGTM

2023-01-31 17:29 UTC, eugene-manuilov requested changes
Actually, one thing that we forgot to take into account is that it should correctly look on a narrow screen: 
![image](https://user-images.githubusercontent.com/873049/215837262-4f40ca42-cd0b-4cd5-b7d9-646f9805ef89.png)

@nfmohit could you please update styles to make sure the menu looks correctly when it doesn't fit the screen?

2023-01-31 20:20 UTC, nfmohit commented
> @nfmohit could you please update styles to make sure the menu looks correctly when it doesn't fit the screen?

Thanks so much for the kind review, @eugene-manuilov! That's a nice catch. I've updated it so that it works well on narrow screens.

Besides, I've also made [this additional change](https://github.com/google/site-kit-wp/pull/6501#discussion_r1092432772) for better responsiveness in smaller screens.

Let me know if this looks good to you now, thank you!

2023-02-01 13:57 UTC, eugene-manuilov approved these changes
Thanks, @nfmohit. All looks good now! Approved!

2023-02-01 13:57 UTC, merged