Simplify in progress state in Analytics activation CTA.
google/site-kit-wp pull request #6504
Opened 2023-01-31 15:15 UTC by sashadoes

## Summary

Addresses issue:

- #6416 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-02-03 20:52 UTC, aaemnnosttv commented on assets/js/components/ActivateAnalyticsCTA.js
> +	}, [ isActivating, isNavigatingToReauthURL, debouncedSetInProgress ] );
This part is more/less copied from [what we have implemented in `ResetButton`](https://github.com/google/site-kit-wp/blob/83b2edfd1bf05179172566acc8a9a4bb75fbeaf9/assets/js/components/ResetButton.js#L62-L75)

The idea here is that we want the in progress state to be set right away when the user clicks the button, but add a significant delay in setting it back to `false` due to the gap between activation and navigation in the case where Analytics needs to be activated before navigating to the setup.

2023-02-03 20:52 UTC, aaemnnosttv commented on tests/e2e/specs/modules/analytics/write-scope-requests.test.js
> +		await pageWait();
This change was mostly unrelated to the other changes here as far as I can tell but the failure caused confusion here so it seems to be fixed now 👍

2023-02-07 22:08 UTC, tofumatt requested changes
Looks good, but can you please add a QA Brief to this issue?

After that this is good-to-go 👍🏻

2023-02-08 20:44 UTC, tofumatt approved these changes

2023-02-08 20:45 UTC, merged