Fix key Metrics flicker from Admin Settings.
google/site-kit-wp pull request #6525
Opened 2023-02-03 00:34 UTC by sashadoes

## Summary

Addresses issue:

- #6428 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-02-03 17:52 UTC, eugene-manuilov requested changes
Thanks, @sashadoes. Left a few comments for you. Please, take a look.

2023-02-03 17:52 UTC, eugene-manuilov commented on assets/js/components/settings/SettingsAdmin.js
> +										settingsdView
```suggestion
										settingsView
```

2023-02-03 17:52 UTC, eugene-manuilov commented on assets/js/components/user-input/UserInputPreview.js
> +		settingsdView = false,
```suggestion
		settingsView = false,
```

2023-02-03 17:52 UTC, eugene-manuilov commented on assets/js/components/user-input/UserInputPreview.js
> +				{ settingsdView && (
```suggestion
				{ settingsView && (
```

2023-02-03 17:52 UTC, eugene-manuilov commented on assets/js/components/user-input/UserInputPreview.js
> +	settingsdView: PropTypes.bool,
```suggestion
	settingsView: PropTypes.bool,
```

2023-02-03 17:52 UTC, eugene-manuilov commented on assets/js/components/user-input/UserInputPreview.js
> +				) }
I think we should preserve the previous layout: this block should go first wrapped with <Row><Cell>, then the div with `googlesitekit-user-input__preview` class.

```js
return (
    <Fragment>
        { settingsView && (
            <Row>
                <Cell>
                    <p ...>...</p>
                </Cell>
             </Row>
        ) }
        <div className={ classnames( 'googlesitekit-user-input__preview', { ... } ) }>
            ...
        </div>
    </Fragment>
)
```

2023-02-03 20:28 UTC, sashadoes commented
Thanks, @eugene-manuilov . I made an update :)

2023-02-06 10:47 UTC, eugene-manuilov approved these changes
LGTM

2023-02-06 10:47 UTC, merged