Reduce code complexity in DataBlock.
google/site-kit-wp pull request #6531
Opened 2023-02-03 20:03 UTC by sashadoes

## Summary

Addresses issue:

- #6028 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-02-07 15:27 UTC, eugene-manuilov requested changes
Thanks, @sashadoes. Left a few comments for you. Please, take a look.

2023-02-07 15:27 UTC, eugene-manuilov commented on assets/js/components/DataBlock.js
> +			aria-disabled={ gatheringData }
This property value should remain the same as it was before:
```suggestion
			aria-disabled={ gatheringData || undefined }
```

2023-02-07 15:27 UTC, eugene-manuilov commented on assets/js/components/DataBlock.js
> +	const handleClick = () => {
Please, use `useCallback` for all callbacks to make it consistent with other components.

2023-02-07 15:27 UTC, eugene-manuilov commented on assets/js/components/DataBlock.js
> +	const datapointFormatted = datapoint && numFmt( datapoint, datapointUnit );
Same here, I don't know for sure but explicitly checking whether the `datapoint` variable is `undefined` might have some sense that will be lost after your changes. Please, revert it as it was before.

2023-02-08 10:28 UTC, eugene-manuilov requested changes
Thanks, @sashadoes. Looks good to me, but I am not sure about naming. The `DataBlockAddons` name is not clear to me. Let's probably move these components into `components/DataBlock` folder and split `DataBlockAddons` into multiple components: `Sparkline`, `Change` and `SourceLink`.

2023-02-09 13:43 UTC, eugene-manuilov requested changes
Thanks, @sashadoes. Added the last comments from myself. Once they are addressed, we are good to go.

2023-02-09 13:43 UTC, eugene-manuilov commented on assets/js/components/DataBlock/Change.js
> + * Site Kit by Google, Copyright 2021 Google LLC
```suggestion
 * Site Kit by Google, Copyright 2023 Google LLC
```

2023-02-09 13:43 UTC, eugene-manuilov commented on assets/js/components/DataBlock/Change.js
> +			<Fragment>
We don't need this fragment element. Let's get rid of it.

2023-02-09 13:43 UTC, eugene-manuilov commented on assets/js/components/DataBlock/index.js
> + * Site Kit by Google, Copyright 2021 Google LLC
```suggestion
 * Site Kit by Google, Copyright 2023 Google LLC
```

2023-02-09 13:43 UTC, eugene-manuilov commented on assets/js/components/DataBlock/index.js
> +			) }
Let's split it to remove a need for using the `Fragment` element:

```js
{ ! gatheringData && sparkline && (
    <Sparkline ... />
) }
{ ! gatheringData && (
    <div className="googlesitekit-data-block__change-source-wrapper">...</div>
) }
{ gatheringData && (
    <GatheringDataNotice style={ gatheringDataNoticeStyle } />
) }
```

2023-02-09 23:19 UTC, sashadoes commented
Thank you @eugene-manuilov 🙂

2023-02-10 16:15 UTC, eugene-manuilov approved these changes
Thanks, @sashadoes. Looks good to me.

2023-02-10 16:15 UTC, merged