Fix Site Health notices and add basic E2E tests
google/site-kit-wp pull request #6598
Opened 2023-02-16 17:00 UTC by aaemnnosttv

## Summary

Addresses issue:

- #6597 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-02-20 18:12 UTC, techanvil requested changes
This looks good @aaemnnosttv and works well. I have left a few comments on the tests, please take a look.

2023-02-20 18:12 UTC, techanvil commented on tests/phpunit/integration/Core/Util/Debug_DataTest.php
> -				'recoverable_modules',
It could be worth adding an additional test case here to cover the Dashboard Sharing fields...

2023-02-20 21:07 UTC, aaemnnosttv commented on tests/e2e/specs/wp-admin/site-health.test.js
> +		await setupSiteKit();
Oops, thanks!

2023-02-20 21:13 UTC, aaemnnosttv commented on tests/phpunit/integration/Core/Modules/Module_Sharing_SettingsTest.php
> +						'management'  => 'owner',
I thought about that before and decided to go this way but I don't see a reason not to; SGTM 👍

2023-02-21 16:49 UTC, techanvil approved these changes
Nice one @aaemnnosttv, LGTM!

2023-02-21 16:50 UTC, merged