Do not dismiss tour if there was a missing step
google/site-kit-wp pull request #7258
Opened 2023-07-06 07:38 UTC by nfmohit

## Summary

Addresses issue:

- #7036 

## Relevant technical choices

This PR prevents dismissing a feature tour if there was a missing step.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-07-07 12:38 UTC, techanvil requested changes
Hey @nfmohit, when you described this amended solution in your [comment](https://github.com/google/site-kit-wp/issues/7036#issuecomment-1619544162) on the issue, I had assumed that it would still retain the ability for the user to dismiss the feature tour by pressing the close or "Got it" buttons.

However with this implementation, in the case where there's a missing step and the user navigates to it, if they subsequently press close/"Got it" the tour is _not_ dismissed. This is problematic as we could end up in the situation where a user has a broken feature tour that keeps popping up and they cannot dismiss.

Do you have any thoughts on how we could still ensure that a deliberate action of the user to close the tour will still dismiss it? If this is overly complicated we might need to move it back to IB to redo the spec...

2023-07-09 10:31 UTC, nfmohit commented
> Hey @nfmohit, when you described this amended solution in your [comment](https://github.com/google/site-kit-wp/issues/7036#issuecomment-1619544162) on the issue, I had assumed that it would still retain the ability for the user to dismiss the feature tour by pressing the close or "Got it" buttons.
> 
> However with this implementation, in the case where there's a missing step and the user navigates to it, if they subsequently press close/"Got it" the tour is _not_ dismissed. This is problematic as we could end up in the situation where a user has a broken feature tour that keeps popping up and they cannot dismiss.
> 
> Do you have any thoughts on how we could still ensure that a deliberate action of the user to close the tour will still dismiss it? If this is overly complicated we might need to move it back to IB to redo the spec...

I understand what you mean. I had the same concerns, however, I spent quite sometime with the `react-joyride` API but couldn't figure out a straight-forward solution to this. Would you like to take a look as well, or should we send it back to IB for redoing the spec and re-evaluating the estimate?

Thank you, @techanvil!

2023-07-10 17:17 UTC, techanvil commented
> I understand what you mean. I had the same concerns, however, I spent quite sometime with the `react-joyride` API but couldn't figure out a straight-forward solution to this. Would you like to take a look as well, or should we send it back to IB for redoing the spec and re-evaluating the estimate?
> 
> Thank you, @techanvil!

Thanks @nfmohit. As discussed in the standup, I did have a look myself too but couldn't see any readily apparent solution for this one. As a result we're going to close this issue and I've created https://github.com/google/site-kit-wp/issues/7281 as a followup to redo the IB.

2023-07-10 17:17 UTC, techanvil commented
Closing as we're going to redo the IB in https://github.com/google/site-kit-wp/issues/7281.

2023-07-10 17:17 UTC, closed without merging