Key Metrics Setup CTA Dismissal
google/site-kit-wp pull request #7304
Opened 2023-07-13 00:11 UTC by kuasha420

## Summary

Addresses issue:

- #6232 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-07-13 16:36 UTC, techanvil requested changes
Hey @kuasha420, this is looking good, just a few minor comments from me to consider. Please take a look.

2023-07-13 16:36 UTC, techanvil commented on assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.stories.js
> +						} ) }
This CSS class isn't needed, as there's no animation to disable for the `KeyMetricsSetupCTAWidget` component.

```suggestion
```

2023-07-13 18:38 UTC, kuasha420 commented on assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js
> +		select( CORE_USER ).isItemDismissed( KEY_METRICS_SETUP_CTA_WIDGET_SLUG )
Hi, I have copied the implementation from the `AdBlockingRecoveryWidget` and not the `AdSenseSetupCTA`, that's why there's the difference. Both will most likely change to accommodate the change to support periodic dismissals, so I'd rather keep it consistent between this two. Cheers.

2023-07-13 18:42 UTC, kuasha420 commented on assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js
> +	);
See my other comment.

2023-07-14 09:14 UTC, techanvil commented on assets/js/components/KeyMetrics/KeyMetricsSetupCTAWidget.js
> +		select( CORE_USER ).isItemDismissed( KEY_METRICS_SETUP_CTA_WIDGET_SLUG )
Ahh, thanks for the explanation. Makes sense, let's leave as-is then!

2023-07-14 09:16 UTC, techanvil approved these changes
LGTM, nice work @kuasha420!

2023-07-14 09:18 UTC, merged