Fix / 6907 WP Dashboard Submenu Not Visible
google/site-kit-wp pull request #7332
Opened 2023-07-19 08:31 UTC by 10upsimon

## Summary

Addresses issue:

- #6907

## Relevant technical choices

- Added custom z-indexes section to SASS variables storage file at `assets/sass/config/_variables.scss`.
- Defined new `$z-index-sk-header` SASS variable to reference value `9980`.
- Updated the SK Header CSS selector for `.googlesitekit-header` in `assets/sass/components/global/_googlesitekit-header.scss` and changed the existing `z-index` property value to be the newly defined `$z-index-sk-header` variable, thus reducing the z-index to `9980` and no longer causing display issues with the WordPress admin sidebar sub/flyout menus.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-07-19 16:35 UTC, techanvil commented on assets/sass/config/_variables.scss
> +// Custom z-index values
As @aaemnnosttv alluded to [here](https://github.com/google/site-kit-wp/issues/6907#issuecomment-1634979154), it's probably worth adding a bit more info as a comment to describe the notable, related z-indexes that you found while investigating this issue. No need to go into too much detail - we can always refer back to this issue for the full writeup - but a brief summary would be handy, essentially these bits:

> * The top admin bar and its child menus, at z-index `99999`
> * The left most main/side admin menu wrapper, at z-index `9990`
> * The left most main/side admin menu sub menus on hover, at z-index `9999`

2023-07-19 16:36 UTC, techanvil requested changes
Hey @10upsimon, this looks great, I've left a request for a bit more info in the comments. Please take a look.

2023-07-20 09:15 UTC, 10upsimon commented
> Hey @10upsimon, this looks great, I've left a request for a bit more info in the comments. Please take a look.

Hey @techanvil , thanks for the feedback. Please see https://github.com/google/site-kit-wp/pull/7332/commits/421532b879570a1161be7ef0504b43ce90e0ff30 where I have added more supporting info via a SASS comment block, I trust this is what you meant.

Thanks!

2023-07-20 09:22 UTC, techanvil commented
> > Hey @10upsimon, this looks great, I've left a request for a bit more info in the comments. Please take a look.
> 
> Hey @techanvil , thanks for the feedback. Please see [421532b](https://github.com/google/site-kit-wp/commit/421532b879570a1161be7ef0504b43ce90e0ff30) where I have added more supporting info via a SASS comment block, I trust this is what you meant.
> 
> Thanks!

Thanks @10upsimon, yes, that's spot on, cheers!

2023-07-20 12:05 UTC, merged