Use GitHub Actions matrices for PHP and E2E.
google/site-kit-wp pull request #7396
Opened 2023-08-03 21:53 UTC by tofumatt

## Summary

Addresses issue:

- #5030.

## Relevant technical choices

Included PHP version in the PHP matrices. They weren't explicitly mentioned in the ACs/IB, but it made sense and were probably intented to be included. 🤔

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-08-09 18:33 UTC, aaemnnosttv requested changes
Thanks @tofumatt – this is great to see so much consolidated. A few points to address but otherwise looking good!

2023-08-09 18:33 UTC, aaemnnosttv commented on .github/workflows/php-lint-tests.yml
> +      - '.github/workflows/php-tests-wp-latest-php-7-4.yml'
```suggestion
      - '.github/workflows/php-lint-tests.yml'
```

2023-08-09 18:52 UTC, aaemnnosttv commented
> I also combined the lint and test files for easier organisation/scan-ability in actions, now they look like this:

@tofumatt Let's leave the two separate workflows for now since they're concerned with some different files and we don't really benefit much from combining them in the same workflow. I initially thought that this was done to only run the PHP tests if the linting passed but that isn't the case. I also don't think that's necessary for the most part since we have linting as a pre-commit check, so it's probably rare that this would fail for us to justify delaying the other tests.

2023-08-09 18:57 UTC, tofumatt commented on .github/workflows/php-lint-tests.yml
> +      - '.github/workflows/php-tests.yml'
Argh, right on, I changed these file names a few times during development 🙂

2023-08-09 18:58 UTC, tofumatt commented on .github/workflows/php-lint-tests.yml
> +        if: ${{ matrix.php_version == '8.0' }}
Yeah, I had some weird linting happen (with the Google, org-wide CodeQL tool) when I omitted them, you can see it in the commit history).

I'll try again, especially with the `startsWith`, as maybe it'll be okay then.

2023-08-09 19:01 UTC, tofumatt commented
@aaemnnosttv My thinking was that it allows us to consolidate all PHP-related tests/workflows into one file and one set of `paths`. It could eventually allow us to share the build/install step too (or run `lint` as part of the test workflow, which would actually save us several minutes.)

The JS tests and linting are part of the same workflow AND job, this at least brings the PHP ones into the same workflow, and means one fewer set of _very similar_/identical paths to be maintained for PHP linting/testing.

We also certainly _could_ delay running tests until linting completes, but it's probably not worth it 🤔

2023-08-17 18:36 UTC, aaemnnosttv commented on .github/workflows/php-lint-tests.yml
> +        if: ${{ matrix.php_version == '8.0' }}
Looks like it didn't like this line 🤷‍♂️ 
https://github.com/google/site-kit-wp/blob/9bb8ab1f7ba9888bcbc2b9d7014e4ef794e53d24/.github/workflows/php-tests.yml#L128

2023-08-17 19:35 UTC, aaemnnosttv approved these changes
Great!

2023-08-17 19:35 UTC, merged