Add client side cache store.
google/site-kit-wp pull request #7517
Opened 2023-08-30 10:15 UTC by zutigrm

## Summary

Addresses issue:

- #6472 

## Relevant technical choices

Created new cache store per IB. Tests for the new action are included as well.

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-09-05 09:36 UTC, hussain-t requested changes
Thanks, @zutigrm. Overall, the changes look good. I've left a few nitpicky comments. Please take a look. 

FYI, verifying the unit tests is part of the code review. This ticket doesn't involve any user-facing changes. Hence, it can bypass the QA and move to approval by the merge reviewer. I have updated the QAB.

2023-09-05 09:36 UTC, hussain-t commented on assets/js/googlesitekit/datastore/site/cache.test.js
> + * Site Kit by Google, Copyright 2021 Google LLC
```suggestion
 * Site Kit by Google, Copyright 2023 Google LLC
```

2023-09-05 09:36 UTC, hussain-t commented on assets/js/googlesitekit/datastore/site/cache.test.js
> +		describe( '*setCacheItem', () => {
This is not in our conventions. So, we could remove the asterisk.
```suggestion
		describe( 'setCacheItem', () => {
```

2023-09-05 11:49 UTC, hussain-t approved these changes
Nice one, @zutigrm. LGTM 👍

2023-09-05 20:08 UTC, tofumatt approved these changes

2023-09-05 20:52 UTC, merged

2023-09-07 20:39 UTC, aaemnnosttv commented on assets/js/googlesitekit/datastore/site/cache.js
> +	 * @param {boolean} [args.isError]   Optional. Whether the cached item is an error.
For an arguments object with properties that are all optional, we use `options` as the name for this kind of object as a convention. `args` could contain optional properties but implies that at least one or more are required.