De-duplicate WP Dashboard Errors
google/site-kit-wp pull request #7701
Opened 2023-10-16 09:24 UTC by kuasha420

## Summary

Addresses issue:

- #5615 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-10-18 20:55 UTC, kuasha420 commented
Thank you @jimmymadon , based on your feedback and the follow up discussion on Slack, I've extracted the added logic to a new `WPDashboardReportError` and used it in all WPDashboard components. I've decided to directly import the new component instead of exposing it in the Widget API, as its usage is limited to the WP Dashboard widgets, but let me know if you have any other ideas. 

Cheers.

2023-11-01 20:10 UTC, kuasha420 commented
Thank you @jimmymadon for the review. As par the follow up discussion. I've updated the PR accordingly. Please have another look. Cheers.

2023-11-02 17:03 UTC, techanvil requested changes
Hey @kuasha420, this is generally looking good, there is one aspect I think we should reconsider though, and I've left couple of minor comments regarding the tests. Please see what you think.

2023-11-03 00:55 UTC, kuasha420 commented on assets/js/googlesitekit/widgets/components/WPDashboardReportError.js
> +		: error.message;
@techanvil  Thank you, this seem reasonable, all things considered so I've gone ahead and implemented this and applied your other suggested changes. Let me know if that looks okay. Cheers.

2023-11-03 11:27 UTC, techanvil commented on assets/js/googlesitekit/widgets/components/WPDashboardReportError.js
> +		: error.message;
Nice one @kuasha420, LGTM!

2023-11-03 11:38 UTC, techanvil approved these changes
LGTM, nice one @kuasha420!

2023-11-03 11:38 UTC, merged