Limit all banners
google/site-kit-wp pull request #7828
Opened 2023-11-06 08:41 UTC by zutigrm

## Summary

Addresses issue:

- #6634 

## Relevant technical choices

I also included a quick fix for adSense banner title - since it was throwing the error in console log. Title is required, but it was not passed, so there was a prop types console error

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-11-13 06:32 UTC, hussain-t requested changes
Thanks, @zutigrm. Overall, LGTM. However, I have left a couple of comments on the test mocks. Please take a look at my comments. Please resolve the merge conflicts as well.

2023-11-13 06:32 UTC, hussain-t commented on assets/js/components/notifications/BannerNotifications.test.js
> +			.receiveGetModules( Object.values( modules ) );
We could avoid these by using the `provideModules` utility:
```suggestion
		provideModules( registry, [
			{
				slug: 'adsense',
				active: true,
				connected: true,
			},
		] );
```

2023-11-13 06:32 UTC, hussain-t commented on assets/js/components/notifications/BannerNotifications.test.js
> +		);
We don't have to mute the API call since we are mocking the `setSettings` action with the `accountID` below.

2023-11-13 08:58 UTC, zutigrm commented
@hussain-t Thank you for valuable feedback. Good catch, I updated the PR

2023-11-14 18:25 UTC, tofumatt approved these changes

2023-11-14 18:25 UTC, merged