Issue / 7532 Update Internal Event Tracking GA4
google/site-kit-wp pull request #7972
Opened 2023-12-11 10:09 UTC by 10upsimon

## Summary

Addresses issue:

- #

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-12-13 22:47 UTC, tofumatt requested changes
Largely looks good to me, just a question about the global really 🙂

2023-12-13 22:47 UTC, tofumatt commented on assets/js/util/index.js
> +global._gsktag = trackEvent;
Let's add some whitespace here to separate this more from the comment below…

```suggestion
global._gsktag = trackEvent;

```

That said: why place this global here? This seems a bit… "buried"/hidden in the codebase for this type of change to be made, especially with no comment explaining it or what it does.

Can you add a comment explaining what this is and why it's here?

It might also be good to put in a more dedicated place related to `trackEvent`, etc. 🤔

2023-12-15 12:53 UTC, 10upsimon commented on assets/js/util/index.js
> +global._gsktag = trackEvent;
> That said: why place this global here?

@tofumatt thanks for picking this up, that was left over from debugging the trackEvent via a global that could be accessed in console I believe, I have removed it and I am still observing the internal tracking functioning correctly.

Back over to you.

2023-12-18 17:34 UTC, tofumatt approved these changes

2023-12-18 17:34 UTC, merged

2024-01-11 21:09 UTC, aaemnnosttv commented on assets/js/util/index.js
> +global._gsktag = trackEvent;
From the IB :)

> [Remove WIP test function](https://github.com/google/site-kit-wp/compare/poc/track-event-ga4#diff-35e7b36727377afdfe72372f2fdc85d4d74f6a423a820ad573c77b3c07a1341b)