Copy over analytics settings.
google/site-kit-wp pull request #7983
Opened 2023-12-14 11:46 UTC by zutigrm

## Summary

Addresses issue:

- #7923 

## Relevant technical choices

Deviations from IB:
* Couldn't implement old settings values fallback in `get` method in Settings, as at this point options have already synced with default to fill in the missing keys, and we arrive at the problem of determining what's older chicken or the egg - are the current settings updated values, or are the analytics settings correct values and options were updated with defaults (all 4 keys have different value types, it is not realistic to determine by them not having a value (having an empty value), as one is boolean, another array, etc). So I added the filter, which will run when options are retrieved but before missing keys are filled by default values to ensure settings array always returns proper data, and there is a way to check if they are missing.
* Removed `get` method as it is not needed any more
* Test is implemented in `Analytics_4Test` instead of Settings, due to change mentioned above

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2023-12-14 19:14 UTC, eugene-manuilov requested changes
Thanks, @zutigrm. Mostly looks good to me. Left a few minor comments with some small changes. Please, let me know if you have questions.

2023-12-14 19:14 UTC, eugene-manuilov commented on assets/js/modules/analytics-4/datastore/base.js
>  		// 'adsConversionID',
This is not an owned setting, let's remove this remaining comment.

2023-12-14 19:14 UTC, eugene-manuilov commented on tests/phpunit/integration/Modules/Analytics_4/SettingsTest.php
>  				// 'adsConversionID'        => '',
Same here, let's remove this remaining part of the comment.

2023-12-15 09:27 UTC, zutigrm commented
@eugene-manuilov Thank you for the feedback. PR updated

2023-12-19 12:16 UTC, eugene-manuilov requested changes
Thanks, @zutigrm. Mostly looks good to me. Just added a few minor comments with tiny changes. Please, take a look.

2023-12-19 12:16 UTC, eugene-manuilov commented on tests/backstop/reference/google-site-kit_Components_TextField_0_document_0_small.png
Looks like vrt images should be already updated in the develop branch. Try to merge the latest changes into your branch. I think these changes in images should disappear.

2023-12-19 12:16 UTC, eugene-manuilov commented on includes/Modules/Analytics_4/Settings.php
> +	protected function retrieve_missing_analytics_4_settings( $option ) {
Let's probably drop `analytics_4` from the function name: `retrieve_missing_settings`.

2023-12-19 12:16 UTC, eugene-manuilov commented on includes/Modules/Analytics_4/Settings.php
> +			},
I think we can move this logic into the `retrieve_missing_...` method and use `add_filter( 'option_' . self::OPTION, array( $this, 'retrieve_missing_...' ) )`.

2023-12-19 14:54 UTC, zutigrm commented
@eugene-manuilov Thank you for the suggestions, I updated PR

2023-12-20 16:39 UTC, eugene-manuilov requested changes
@zutigrm, I still see vrt images changed. Could you please revert changes in those images?

2023-12-21 12:12 UTC, eugene-manuilov requested changes
Thanks, @zutigrm. The last one comment with a suggestion, that I'll apply by myself.

2023-12-21 12:12 UTC, eugene-manuilov commented on includes/Modules/Analytics_4/Settings.php
> +			return;
```suggestion
			return $option;
```

2023-12-21 12:14 UTC, eugene-manuilov approved these changes

2023-12-21 12:29 UTC, merged