Enhance/5830 date format consistency
google/site-kit-wp pull request #8053
Opened 2024-01-07 23:34 UTC by kuasha420

## Summary

Addresses issue:

- #5830

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-01-08 09:56 UTC, zutigrm approved these changes
Thanks @kuasha420 LGTM

2024-01-09 17:41 UTC, tofumatt requested changes
Looks great!

Just one minor tweak I'd suggest: let's add another tick when there's zero data. Right now the charts look a bit odd in a zero data state, because they only show the reference date (eg. the last date in the date range):

![CleanShot 2024-01-09 at 17 39 45](https://github.com/google/site-kit-wp/assets/90871/3286efa7-4b82-4bcd-a405-8a233e164b1a)

![CleanShot 2024-01-09 at 17 39 51](https://github.com/google/site-kit-wp/assets/90871/83bddb3e-3708-4f63-9995-1979152348f5)

If it's straightforward to do, can we add a tick for the start date or similar in that case?

2024-01-15 19:33 UTC, tofumatt reviewed
I removed the `getNextDate` utility function here as it was a lot of code (between the tests/comments/etc.) for what could be done in a few lines, plus I think it was a bit awkwardly-named, because really it was creating an arbitrary date based on the arguments, not the "next date".

Otherwise looks good. 👍🏻

2024-01-15 19:33 UTC, tofumatt approved these changes

2024-01-15 23:37 UTC, merged