Enhancement/7931 migrate ga4 settings view
google/site-kit-wp pull request #8065
Opened 2024-01-09 16:39 UTC by jimmymadon

## Summary

Addresses issue:

- #7931 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [x] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-01-12 12:55 UTC, hussain-t requested changes
Thanks, @jimmymadon. The changes LGTM. However, unit tests are missing for the `getServiceURL` selector. Can you copy over the tests from the `analytics` datastore?

2024-01-15 08:47 UTC, hussain-t approved these changes
Nice one, @jimmymadon. LGTM 👍

2024-01-15 11:40 UTC, techanvil requested changes
Hey @jimmymadon, this is looking good, just a couple of very minor comments from me to address.

2024-01-15 11:40 UTC, techanvil commented on assets/js/modules/analytics-4/components/common/TrackingExclusionSwitches.js
> +};
I'd suggest creating these in a separate constants file rather than creating this stub component file.

2024-01-15 11:40 UTC, techanvil commented on assets/js/modules/analytics-4/components/settings/OptionalSettingsView.js
> +							{ adsConversionID ? (
We might as well use the ternary-avoiding pattern here too for consistency.

2024-01-17 16:50 UTC, techanvil approved these changes
LGTM, nice one @jimmymadon!

2024-01-17 16:50 UTC, techanvil commented on assets/js/modules/analytics-4/components/common/TrackingExclusionSwitches.js
> +};
Thanks @jimmymadon, fair enough I can see the benefit of that approach for ease of migration, we can still extract these to a constants file in due course.

2024-01-17 16:51 UTC, merged