7926 migrate analytics ga4 class
google/site-kit-wp pull request #8083
Opened 2024-01-13 21:21 UTC by jimmymadon

## Summary

Addresses issue:

- #7926

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

2024-01-22 15:50 UTC, aaemnnosttv submitted a review, later dismissed
Don't merge yet :)

2024-01-24 17:04 UTC, zutigrm approved these changes
Thanks @jimmymadon, LGTM

2024-02-08 10:14 UTC, nfmohit requested changes
Incredible hard work here, thank you @jimmymadon!

I have left a few comments.

I'd suggest leaving unused methods intact in the legacy module for now so that we can reference old code easily. There are a few test cases removed from `AnalyticsTest` as well which wouldn't hurt to keep.

Besides, there are a few other minor comments, and `develop` needs to be merged into this branch.

Thank you!

2024-02-09 06:28 UTC, nfmohit commented on includes/Modules/Analytics_4.php
> +			if ( ! empty( $tag_id ) ) {
Ah, yes, that actually makes sense. Let's keep it as it is. Thanks!

2024-02-09 07:07 UTC, nfmohit requested changes
Hi @jimmymadon. I was just testing this out one last time by creating a new account and it looks like we've hit a roadblock. Let me know what you think, thanks!

2024-02-09 07:07 UTC, nfmohit commented on includes/Modules/Analytics_4.php
> +		$this->get_settings()->merge( $new_settings );
I was just testing this out and found an unfortunate major problem. We're saving the `accountID` here to the `analytics-4` module, however, our current `analytics` settings and overall infrastructure depends on the `accountID` from the `analytics` module, thus, causing an unavailable `accountID` issue.

![image](https://github.com/google/site-kit-wp/assets/20284937/4895dff6-6856-46ba-811e-4121e831972a)

There are 2 probable steps we can take here:

1. In this place, also save the `accountID` for `analytics` and remove in [#7932](https://github.com/google/site-kit-wp/issues/7932).
2. Keep this on hold as well and release it with [#7932](https://github.com/google/site-kit-wp/issues/7932) (more merge conflicts may occur).

Let me know what you think, thanks!

2024-02-09 20:59 UTC, nfmohit approved these changes
LGTM now, thank you Jimmy! 👍

2024-02-09 21:01 UTC, merged

2024-02-23 22:09 UTC, tofumatt commented
We may want to include this change/TODO as well: https://github.com/google/site-kit-wp/blob/3df13cfacbe5cc58d71349d3bc5bab60c4ffc41a/includes/Modules/Analytics_4.php#L639-L640