Enhancement/7685 inp tooltip
google/site-kit-wp pull request #8194
Opened 2024-01-29 19:30 UTC by zutigrm

## Summary

Addresses issue:

- #7685 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-01-30 16:45 UTC, hussain-t approved these changes
Thanks, @zutigrm. LGTM 👍 

FYI, I've added the missing prop types for `hintText`.

2024-01-31 11:28 UTC, nfmohit requested changes
Nice work here, thank you @zutigrm.

I have left a few comments, but as they're very minor, I've gone ahead and applied them myself.

Hope that's okay, thanks!

2024-01-31 11:28 UTC, nfmohit commented on assets/js/modules/pagespeed-insights/components/common/FieldReportMetrics.js
> +								'INP will replace FID in March 2024 <LearnMoreLink />',
We are missing a period.

```suggestion
								'INP will replace FID in March 2024. <LearnMoreLink />',
```

2024-01-31 11:28 UTC, nfmohit commented on assets/sass/components/dashboard/_googlesitekit-ReportMetric.scss
> +	letter-spacing: 0.25px;
Let's use our SCSS variable for letter-spacing. Also, let's add a line-height value that is same as the referenced note.

```suggestion
	letter-spacing: $ls-s;
	line-height: $lh-body-lg;
```

2024-01-31 11:28 UTC, nfmohit commented on assets/sass/components/dashboard/_googlesitekit-ReportMetric.scss
> +	margin-top: 7px;
Let's use a relative 0.5em value as that appears to align more with the AC (half of 1em).

```suggestion
	margin-top: 7px;
```

2024-01-31 11:44 UTC, nfmohit approved these changes
LGTM! 👍

2024-01-31 11:44 UTC, merged