Track events for the dashboard top earning pages widget.
google/site-kit-wp pull request #8286
Opened 2024-02-20 13:16 UTC by benbowler

## Summary

Addresses issue:

- #8212

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-02-22 14:29 UTC, tofumatt approved these changes
Looks good, thanks for finding the fix and all the context around it. 👍🏻 

Just one variable name tweak and then I'll merge this 👍🏻

2024-02-22 14:29 UTC, tofumatt commented on assets/js/modules/adsense/components/dashboard/DashboardTopEarningPagesWidgetGA4.js
> +	};
Let's avoid shorthand variables like `el` in favour of `element`, when possible:
```suggestion
	const updateTrackingRef = ( element ) => {
		trackingRef.current = element;
		if ( element && ! trackingRefReady ) {
			setTrackingRefReady( true );
		}
	};
```

2024-02-22 15:52 UTC, tofumatt requested changes
Oh, actually, just one thing here.

Given #8049 isn't merged yet, can you provide a way for QA to test the linked state of the component to test the `trackEvent` calls there? I assume you used some JS console code to trigger the linked state—can you add that in so that part can be QA'd?

2024-02-23 09:03 UTC, benbowler commented
@tofumatt added a section to the QAB on how to test the linked state.

2024-02-23 12:02 UTC, tofumatt approved these changes
Awesome, thanks @benbowler! 👍🏻

2024-02-23 12:02 UTC, merged