DRAFT: Create the foundation of the Ads module setup flow.
google/site-kit-wp pull request #8348
Opened 2024-03-05 12:22 UTC by benbowler

## Summary

Addresses issue:

- #8346

## Relevant technical choices

In the interest of speed I created a draft PR along with the IB, there's still much work to do here in terms of cleaning up the designs to match the AC/Figma, confirm the correct function of the form and validation etc..

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-03-07 13:53 UTC, 10upsimon requested changes
@benbowler thank you for this, code mostly LGTM aside from an alignment issue with the Ads Conversion ID input notice for when there is no value entered as yet, please see the screenshot below:

![Site Kit by Google Dashboard ‹ sitekit 10uplabs com — WordPress 2024-03-07 at 3 48 08 PM](https://github.com/google/site-kit-wp/assets/72872375/14aaea4f-f746-4f72-9066-8b14b7ef4b4f)

I am also wondering if perhaps we should add a storybook state for this?

2024-03-11 18:08 UTC, benbowler commented
@10upsimon moving this back to CR with you after reading Sigals Slack message about the validation message and including validation here in the setup flow as in the settings pages.

2024-03-18 15:32 UTC, benbowler commented
FYI I updated some of the copy in the Ads Settings branch in [this commit](https://github.com/google/site-kit-wp/pull/8344/commits/a0203767f82237a61c6f86a4485ad4424bfa9e48).

2024-03-19 08:57 UTC, 10upsimon requested changes
@benbowler I noticed one small nitpick WRT banner naming convention but keen to hear your thoughts.

2024-03-19 08:57 UTC, 10upsimon commented on assets/js/components/notifications/SetupSuccessSubtleNotification.js
@benbowler I was thinking about this for a while, and it may seem like a nit pick comment, but if this banner is _only_ related to ads (and it is, given the textual nature of it) I feel we may want to be a but more explicit in terms of naming convention here. The file name and its location do not really elude to the fact that it is an ads only banner.

I think it may be worth renaming this to `AdsSetupSuccessSubtleNotification` or similar, what do you think?

2024-03-19 08:57 UTC, 10upsimon commented on assets/js/components/notifications/SetupSuccessSubtleNotification.stories.js
The same applies to the stories file as I outlined above IRO a more ads explicit naming convention here.

2024-03-19 09:04 UTC, 10upsimon commented on assets/js/components/notifications/SetupSuccessSubtleNotification.js
As per Slack comms, the thought from @benbowler here was that in future other modules may use this style, and conditional output will simply live within this same component.

2024-03-19 09:05 UTC, 10upsimon approved these changes
Thanks @benbowler this seems good to go IMO.

2024-03-20 14:04 UTC, tofumatt approved these changes
Looks good, just a few minor copy issues; I'll make the changes and merge 👍🏻

2024-03-20 14:06 UTC, tofumatt approved these changes

2024-03-20 14:07 UTC, tofumatt reviewed
Just needs the merge conflicts resolved and then we're good-to-go 😄

2024-03-20 15:50 UTC, merged