Add site health checks for Ads module.
google/site-kit-wp pull request #8379
Opened 2024-03-11 19:55 UTC by benbowler

## Summary

Addresses issue:

- #8245

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 5.6.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-03-12 16:39 UTC, benbowler commented on includes/Modules/Ads/Tag_Matchers.php
> +			"/gtag\(['|\"]config['|\"],['|\"]AW-[0-9]+['|\"]\)/",
```suggestion
			"/gtag\(['|\"]config['|\"],\s*['|\"]AW-[0-9]+['|\"]\)/",
```

2024-04-01 12:30 UTC, zutigrm approved these changes
Thanks @benbowler LGTM.

I synced this branch with develop since the tag implementation was needed to confirm the behaviour.

I also updated the QAB to describe all cases, and take new tag implementation into account, which now brings the inline comment used to detect that tag is placed by Site Kit.

Note to the Merge reviewer: There is a weird CI only test failure for php 5.6, it might be some glitch, couldn't replicate it locally, and the code change here is very small to affect it

2024-04-01 12:48 UTC, eugene-manuilov requested changes
Thanks, @benbowler. A few comments from me. Please, take a look.

2024-04-01 12:48 UTC, eugene-manuilov commented on includes/Modules/Ads.php
> +	use Module_With_Tag_Trait;
This is not needed because it is already added to the class.

2024-04-01 12:48 UTC, eugene-manuilov commented on includes/Modules/Ads.php
> +	 * @return array
Let's add a description for what is returned from this function to make it consistent with other method phpdocs.

2024-04-01 12:48 UTC, eugene-manuilov commented on tests/phpunit/integration/Modules/AdsTest.php
> +		$this->assertEqualSets(
Let's also verify that the value is the same as we set in the settings.

2024-04-02 17:25 UTC, eugene-manuilov approved these changes

2024-04-02 17:25 UTC, merged