Conversion event providers webpack partial
google/site-kit-wp pull request #8609
Opened 2024-04-24 11:22 UTC by zutigrm

## Summary

Addresses issue:

- #8531

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-04-25 13:19 UTC, tofumatt requested changes
Will this file be included in production builds? Let's not do that.

If you need to add steps to a QA brief to have the user test the webpack building of this it's fine, but I don't think we should be including test files like this in the repo 🤔

2024-04-25 13:19 UTC, tofumatt commented on assets/js/event-providers/test-plugin-integration.js
> +addEventListener( 'DOMContentLoaded', () => {
This looks like a test file that shouldn't be included in the plugin, right?

Let's move it out of this folder and put it in a test folder 😄 

Let's also add some comments explaining what it is/does/is for. Right now the purpose of this file is quite unclear! 😅

2024-04-25 13:19 UTC, tofumatt commented on assets/js/event-providers/test-plugin-integration.js
> +			console.log( item );
```suggestion
			globa.console.log( item );
```

2024-04-25 13:58 UTC, zutigrm commented
@tofumatt The purpose of the test file is just for QA:Eng, I described in the last step that this file should be deleted. I just scrambled some quick code, purely for testing the builds, and engineer testing it, will remove it

2024-04-29 20:01 UTC, tofumatt commented
@zutigrm Yes, that makes sense to do. We shouldn't be checking in test code, especially code that will result in built files that would be shipped to production builds.

And removing it with a new PR would need to be tracked in a new issue for QA, etc. so I'll handle that part of the QA brief here and then remove the file 👍🏻

2024-04-29 22:58 UTC, tofumatt approved these changes

2024-04-29 23:15 UTC, merged