Add the datastore API for determining audience type (default, SK-created or user-created).
google/site-kit-wp pull request #8622
Opened 2024-04-25 16:29 UTC by techanvil

## Summary

Addresses issue:

- #8129 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-04-25 16:30 UTC, techanvil commented on assets/js/modules/analytics-4/datastore/__fixtures__/available-audiences.json
> +[
This file is copied in from the [PR](https://github.com/google/site-kit-wp/pull/8606/files#diff-14a74e8381f52f6f42e160be1dff0079e1d0e8bbc7b222bb035f49a1f42621ab) for #8487, I haven't branched from that branch as there are pending changes to apply to the file there.

2024-05-01 06:27 UTC, hussain-t approved these changes
Great work, @techanvil. LGTM 👍

2024-05-01 06:27 UTC, hussain-t requested changes
@techanvil, could you resolve the conflicts?

2024-05-01 10:02 UTC, techanvil commented
Thanks @hussain-t, the merge conflicts are resolved :)

2024-05-01 10:10 UTC, techanvil commented
@hussain-t, there are a couple of failing E2E tests, but these are just the usual flaky tests and aren't related to the changes in this PR. I'm sending back your way rather than rerunning these.

2024-05-01 10:25 UTC, hussain-t approved these changes
Great work, @techanvil. LGTM 👍

2024-05-02 05:14 UTC, nfmohit approved these changes
LGTM ✅

2024-05-02 05:14 UTC, merged