Issue / 8564 PAX Extend Ads Settings Edit View
google/site-kit-wp pull request #8636
Opened 2024-04-29 09:30 UTC by 10upsimon

## Summary

Addresses issue:

- #8564

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-05-01 19:01 UTC, tofumatt approved these changes
Looks good 👍🏻

2024-05-01 19:02 UTC, tofumatt requested changes
Oh, shoot, looks like there's a merge conflict actually, can you resolve it? https://github.com/google/site-kit-wp/pull/8636/conflicts

Then we're good-to-go 👍🏻

2024-05-02 07:20 UTC, 10upsimon commented on includes/Modules/Ads.php
@tofumatt pointing out a somewhat unrelated change, but I had to adapt the is_connected() check to also include the presence of PAX settings, or else it would show the module with setup incomplete state.

2024-05-02 07:21 UTC, 10upsimon commented on tests/backstop/reference/google-site-kit_Modules_Ads_Settings_SettingsEdit_Default_0_document_0_small.png
@tofumatt these VRT updates came about due to recent removal of the access checks, so the "ask admin for access" message is now removed, hence these VRT updates as well.

2024-05-02 08:12 UTC, tofumatt approved these changes
Awesome, thanks for the extra info too 👍🏻

2024-05-02 08:14 UTC, merged