Enhance/#8138 - Add the Audiences Widget Area happy path view
google/site-kit-wp pull request #8672
Opened 2024-05-07 12:28 UTC by hussain-t

## Summary

Addresses issue:

- #8138 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [x] Ensure the acceptance criteria are satisfied.
- [x] Reassess the implementation with the IB.
- [x] Ensure no unrelated changes are included.
- [x] Ensure CI checks pass.
- [x] Check Storybook where applicable.
- [x] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [x] Ensure the PR has the correct target branch.
- [x] Double-check that the PR is okay to be merged.
- [x] Ensure the corresponding issue has a ZenHub release assigned.
- [x] Add a changelog message to the issue.

2024-05-23 11:09 UTC, nfmohit requested changes
Nice work here, thank you @hussain-t !

While the code mostly looks good, I'm not able to fully test the behaviour of the tiles as the dashboard immediately crashes as soon as the report requests complete for the audience tiles.

<details>
<summary>Error</summary>

```
An error occurred while running 'mapSelect': A valid set of dimension names and values is required. 
    at ContentLinkComponent (webpack-internal:///./assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/AudienceTilePagesMetric.js:68:25)
    at div
    at div
    at div
    at div
    at AudienceTilePagesMetric (webpack-internal:///./assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/AudienceTilePagesMetric.js:55:23)
    at div
    at div
    at div
    at div
    at eval (webpack-internal:///./assets/js/googlesitekit/widgets/components/Widget.js:38:23)
    at AudienceTile (webpack-internal:///./assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/index.js:73:21)
    at div
    at div
    at div
    at eval (webpack-internal:///./assets/js/googlesitekit/widgets/components/Widget.js:38:23)
    at AudienceTilesWidget (webpack-internal:///./assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js:73:21)
    at WhenActiveComponent (webpack-internal:///./assets/js/util/when-active.js:58:20)
    at WidgetRenderer (webpack-internal:///./assets/js/googlesitekit/widgets/components/WidgetRenderer.js:61:19)
    at div
    at Cell (webpack-internal:///./assets/js/material-components/layout/Cell.js:45:25)
    at WidgetCellWrapper (webpack-internal:///./assets/js/googlesitekit/widgets/components/WidgetCellWrapper.js:39:30)
    at div
    at eval (webpack-internal:///./assets/js/material-components/layout/Row.js:44:24)
    at div
    at div
    at eval (webpack-internal:///./assets/js/material-components/layout/Grid.js:44:24)
    at WidgetAreaRenderer (webpack-internal:///./assets/js/googlesitekit/widgets/components/WidgetAreaRenderer.js:97:19)
    at div
    at WidgetContextRenderer (webpack-internal:///./assets/js/googlesitekit/widgets/components/WidgetContextRenderer.js:52:18)
    at DashboardMainApp (webpack-internal:///./assets/js/components/DashboardMainApp.js:112:106)
    at DashboardEntryPoint (webpack-internal:///./assets/js/components/DashboardEntryPoint.js:47:30)
    at RestoreSnapshots (webpack-internal:///./assets/js/components/RestoreSnapshots/index.js:47:23)
    at ErrorHandler (webpack-internal:///./assets/js/components/ErrorHandler/index.js:77:81)
    at ThemeProvider (webpack-internal:///./node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)
    at Root (webpack-internal:///./assets/js/components/Root/index.js:66:23)
overrideMethod @ console.js:273
useSelect @ index.js:127
ContentLinkComponent @ AudienceTilePagesMetric.js:62
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
onStoreChange @ index.js:160
eval @ index.js:176
eval @ registry.js:76
globalListener @ registry.js:75
eval @ index.js:155
dispatch @ redux.js:306
s @ VM51034:3
eval @ index.js:30
eval @ promise-middleware.js:25
eval @ resolvers-cache-middleware.js:54
_callee$ @ index.js:349
tryCatch @ runtime.js:45
invoke @ runtime.js:274
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:5
_next @ asyncToGenerator.js:27
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:15
_next @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:34
eval @ asyncToGenerator.js:23
setTimeout (async)
_callee2$ @ index.js:338
tryCatch @ runtime.js:45
invoke @ runtime.js:274
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:5
_next @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:34
eval @ asyncToGenerator.js:23
_fulfillSelector @ index.js:366
fulfillSelector @ index.js:306
selectorResolver @ index.js:369
eval @ report.js:395
eval @ report.js:395
selector @ factory.js:21
eval @ index.js:116
runSelector @ index.js:243
eval @ AudienceTilesWidget.js:188
useSelect @ index.js:113
AudienceTilesWidget @ AudienceTilesWidget.js:188
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ react-dom.development.js:18596
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
scheduleUpdateOnFiber @ react-dom.development.js:21199
dispatchAction @ react-dom.development.js:15660
onStoreChange @ index.js:160
eval @ index.js:176
eval @ registry.js:76
globalListener @ registry.js:75
eval @ index.js:155
dispatch @ redux.js:306
s @ VM51034:3
eval @ index.js:30
eval @ promise-middleware.js:25
eval @ resolvers-cache-middleware.js:54
dispatch @ redux.js:700
unhandledActionControl @ runtime.js:57
eval @ create.js:47
next @ create.js:46
eval @ create.js:38
Promise.then (async)
eval @ runtime.js:43
eval @ create.js:47
next @ create.js:46
eval @ create.js:38
any @ builtin.js:15
eval @ create.js:47
next @ create.js:46
unhandledActionControl @ runtime.js:58
eval @ create.js:47
next @ create.js:46
eval @ create.js:38
any @ builtin.js:15
eval @ create.js:47
next @ create.js:46
unhandledActionControl @ runtime.js:58
eval @ create.js:47
next @ create.js:46
eval @ create.js:38
iterate @ create.js:51
runtime @ create.js:73
iterator @ builtin.js:90
eval @ create.js:47
next @ create.js:46
eval @ create.js:38
eval @ runtime.js:45
eval @ create.js:47
next @ create.js:46
eval @ create.js:38
iterate @ create.js:51
runtime @ create.js:73
eval @ runtime.js:66
eval @ runtime.js:65
eval @ index.js:33
eval @ promise-middleware.js:25
eval @ resolvers-cache-middleware.js:54
_callee3$ @ index.js:431
tryCatch @ runtime.js:45
invoke @ runtime.js:274
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:5
_next @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:34
eval @ asyncToGenerator.js:23
fulfillResolver @ index.js:393
_callee$ @ index.js:346
tryCatch @ runtime.js:45
invoke @ runtime.js:274
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:5
_next @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:34
eval @ asyncToGenerator.js:23
setTimeout (async)
_callee2$ @ index.js:338
tryCatch @ runtime.js:45
invoke @ runtime.js:274
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:5
_next @ asyncToGenerator.js:27
eval @ asyncToGenerator.js:34
eval @ asyncToGenerator.js:23
_fulfillSelector @ index.js:366
fulfillSelector @ index.js:306
selectorResolver @ index.js:369
eval @ audience-settings.js:258
selector @ factory.js:21
eval @ index.js:116
runSelector @ index.js:243
eval @ AudienceSegmentationSetupSuccessSubtleNotification.js:47
useSelect @ index.js:113
AudienceSegmentationSetupSuccessSubtleNotification @ AudienceSegmentationSetupSuccessSubtleNotification.js:47
renderWithHooks @ react-dom.development.js:14803
mountIndeterminateComponent @ react-dom.development.js:17482
beginWork @ reac [...]

2024-05-23 12:52 UTC, hussain-t commented
Thanks for raising this, @nfmohit. I've fixed the issue. So that you know, the test failure is not related to this PR.

2024-05-26 20:07 UTC, nfmohit commented on tests/backstop/reference/google-site-kit_Modules_Analytics4_Components_AudienceSegmentation_Dashboard_AudienceTilesWidget_Default_0_document_0_small.png
These VRT additions look alright, however, as these are just copies of the `google-site-kit_Modules_Analytics4_Components_AudienceSegmentation_Dashboard_AudienceTiles_*` references created due to changing the name of the component (from `AudienceTiles` to `AudienceTilesWidget`), could you remove the outdated `google-site-kit_Modules_Analytics4_Components_AudienceSegmentation_Dashboard_AudienceTiles_*` files that are no longer relevant?

2024-05-26 20:13 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js
I have found an issue where I get a console error from this component when both `pageviews` and `totalPageviews` are `0`.

![image](https://github.com/google/site-kit-wp/assets/20284937/dd930007-07a8-436f-963e-f2fe93bdee1d)

This seems to happen because when passing the `percentageOfTotalPageViews` prop into `AudienceTile`, `pageviews` is divided by `totalPageviews`. Both being `0`, it results in a `NaN` value.

I realise this isn't exactly related to your PR, so you can either choose to address it here, or open a follow-up issue so that this bug is fixed.

Thank you!

2024-05-27 05:37 UTC, hussain-t commented on assets/js/modules/analytics-4/datastore/report.js
> +				) }`
Sorry, I used it for debugging and missed reverting it. Good catch 👍

2024-05-27 05:54 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js
I've fixed it in this PR.

2024-05-27 07:21 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js
Unfortunately, the solution for this doesn’t work, because apparently, `totalPageviews` is a string.

![image](https://github.com/google/site-kit-wp/assets/20284937/5832ace9-7714-4081-8a8e-41c899a2300d)

I've pushed a fix for this so that `totalPageviews` is cast as a number.

2024-05-27 10:06 UTC, nfmohit approved these changes
LGTM, brilliant work, @hussain-t !

2024-05-27 10:06 UTC, merged