Remove adsModule feature flag and it's use.
google/site-kit-wp pull request #8685
Opened 2024-05-09 15:11 UTC by benbowler

## Summary

Addresses issue:

- #8541

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-05-09 15:21 UTC, benbowler commented
One note I found in testing is that the Ads Conversion ID is still shown on the Analytics Settings View even after you click "Got it" to confirm the transfer has taken place, this could be confusing IMO because it looks like you don't have a conversion ID set if you came back later and you forgot about the migration process. I suggest we hide this field from the settings view once the message has been dismissed.

2024-05-09 15:54 UTC, benbowler commented
Addressed as in the IB, the VRTs are failing here due to test instability which is being resolved in #8402, after this is merged we can update this branch and re-run checks.

2024-05-13 14:45 UTC, eugene-manuilov requested changes
Thanks, @benbowler. Mostly looks good to me. Just one comment from me.

2024-05-13 14:45 UTC, eugene-manuilov commented on includes/Core/Modules/Modules.php
> -		}
Let's add the Ads module to the core modules directly, similarly how we do for other modules: https://github.com/google/site-kit-wp/blob/ee48119f96675c792cb7a556edcdccad7a1f435b/includes/Core/Modules/Modules.php#L146-L153

2024-05-14 09:42 UTC, benbowler commented
Thanks @eugene-manuilov, I've addressed your comment.

2024-05-14 13:24 UTC, eugene-manuilov approved these changes

2024-05-14 13:25 UTC, eugene-manuilov commented
@benbowler, could you please resolve merge conflicts?

2024-05-14 14:07 UTC, merged