Add partial data badges
google/site-kit-wp pull request #8727
Opened 2024-05-17 18:03 UTC by nfmohit

## Summary

Addresses issue:

- #8142

## Relevant technical choices

This PR adds the partial data badges in Audience Segmentation widget.

### Deviation from IB

- The tooltips appear when the info icon is hovered, instead of the entire badge.
- The IB proposed two separate components for desktop and mobile viewports. This PR implements one and changes appearance based on the viewport.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-05-22 11:17 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/AudienceTilePagesMetric.js
> +	isTopContentPartialData = false,
Updated, thank you!

2024-05-22 11:17 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/AudienceTilePagesMetric.js
> +						<PartialDataBadge
I agree, updated, please let me know if this looks good now, thanks!

2024-05-22 11:17 UTC, nfmohit commented
> Thanks @nfmohit, nice work here. Just making another case for separate components for mobile and desktop, considering their different appearance (Badge vs Notice). Let me know what you think.

I agree, updated, thank you!

2024-05-23 11:08 UTC, kuasha420 requested changes
Excellent work @nfmohit! Thanks for being patient with me and addressing my feedback. I've found one small tweak after the refactor, I'll push the fix myself and get this merged. Cheers!

2024-05-23 11:23 UTC, kuasha420 approved these changes
Thanks @nfmohit :tada:

2024-05-23 11:30 UTC, merged

2024-05-23 11:31 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/PartialDataBadge.js
> +			<Fragment>
Oops, looks like I mistakenly overlooked it, thank you for removing! 🦅