Confirm changes conversion tracking
google/site-kit-wp pull request #8855
Opened 2024-06-11 09:23 UTC by zutigrm

## Summary

Addresses issue:

- #8821 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-06-11 10:37 UTC, benbowler requested changes
Hey @zutigrm, the code here looks good, however it does not address one of the key elements from the AC:

> When the state of the "Enable enhanced conversion tracking" toggle is changed in the edit view of either Ads or GA4 settings edit views, the "Save" CTA button should be re-labelled to read as "Confirm changes"

The button copy does change for other field changes in the Ads and Analytics settings components.

2024-06-11 13:29 UTC, zutigrm commented
@benbowler Thanks, got the requirement mixed up with 8618 issue it was fixing. PR updated.

Side note - change on the label requires additional check for conversion settings change, but `Footer` component has already complexity `20`, additional check goes to `21`. So I refactored it a bit, to extract the 2 components from inline components with a lot of conditional checks, into individual components.

2024-06-11 13:54 UTC, benbowler approved these changes
Thanks @zutigrm, looking good. Moving to MR.

2024-06-11 15:04 UTC, zutigrm commented
@eugene-manuilov It seems your review isn't saved when you sent it back to Execution. Can you please check? Thanks

2024-06-11 15:08 UTC, eugene-manuilov reviewed
Thanks, @zutigrm, but this is not how this issue should be fixed. We need to revert your changes and update the `rollbackChanges` functions in the settings datastore for both Analytics-4 and Ads modules to rollback conversion tracking changes:
https://github.com/google/site-kit-wp/blob/e9c3f4ab005a9f538cf214cc70e2db9dd7cbf140/assets/js/modules/analytics-4/datastore/settings.js#L236-L242

Plus, we need to update the `createSettingsStore` factory to allow overriding the default `haveSettingsChanged` selector similarly to how we do it for `createSubmitChangesStore` in the `createModuleStore` factory. This will require creating a new `makeDefaultHaveSettingsChanged` function similar to what we have for `makeDefaultCanSubmitChanges`.

2024-06-12 11:17 UTC, eugene-manuilov requested changes
Thanks, @zutigrm. Almost looks good to be, but let's update it to be more consistent with other `make*` and `validate*` functions that we use there. Please, see my comments.

2024-06-12 11:17 UTC, eugene-manuilov commented on assets/js/googlesitekit/data/create-settings-store.js
> +		haveSettingsChanged = null,
Let's call it `validateHaveSettingsChanged` to be consistent with other overrides.

2024-06-12 11:17 UTC, eugene-manuilov commented on assets/js/googlesitekit/data/create-settings-store.js
> +		),
Let's use the same approach as the `createValidationSelector` function uses. It should be something like this:

```js
haveSettingsChanged: createRegistrySelector( ( select ) => ( state, ...args ) => validateHaveSettingsChanged( select, state, ...args ) );
```

2024-06-12 11:17 UTC, eugene-manuilov commented on assets/js/googlesitekit/data/create-settings-store.js
> +}
This function should be similar to `makeDefaultCanSubmitChanges`:
```js
function makeDefaultHaveSettingsChanged() {
    return ( select, state, keys ) {
        ...
    }
}
```

2024-06-12 11:17 UTC, eugene-manuilov commented on assets/js/googlesitekit/modules/create-module-store.js
> +		haveSettingsChanged = null,
Let's rename this to be `validateHaveSettingsChanged`.

2024-06-12 11:17 UTC, eugene-manuilov commented on assets/js/googlesitekit/modules/create-module-store.js
> +				haveSettingsChanged,
And after all renamings and updates this should be:
```js
validateHaveSettingsChanged: validateHaveSettingsChanged || makeDefaultHaveSettingsChanged(),
```

2024-06-13 11:25 UTC, eugene-manuilov approved these changes
Great! Thanks, @zutigrm.

2024-06-13 11:25 UTC, merged