Use pivot reports to fetch audiences metrics.
google/site-kit-wp pull request #8870
Opened 2024-06-13 14:02 UTC by ankitrox

## Summary

Addresses issue:

- #8726 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-06-21 12:02 UTC, techanvil requested changes
Thanks @ankitrox, good work so far. I've left a number of comments to address, please take a look.

2024-06-21 12:02 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js
One of the points of the AC/IB has been missed here, which is that all the destructuring/parsing of report rows should be removed from this component, and instead the relevant report rows for an audience should be passed directly to the `AudienceTile` component, which will need a new prop structure and associated logic.

Note the relevant points in the AC and IB:

AC:
> * The `AudienceTiles` and `AudienceTile` components should be further refactored so the reports that are retrieved in `AudienceTiles` are passed directly to `AudienceTile`, and the corresponding data parsing/extraction logic is moved from `AudienceTiles` to `AudienceTile`. Hopefully this logic can be simplified in the process.

IB:
>  * [ ] Update `AudienceTile` to use the new prop structure defined above.
>  * [ ] Update `AudienceTile` stories to use this new pivot report data-mock functionality defined in #8484

I.e. these areas of the code are up for a refactor in this issue:

https://github.com/google/site-kit-wp/blob/3a0ed6d1837eeb48d383704a928f81cbb3028b47/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js#L389-L462

https://github.com/google/site-kit-wp/blob/3a0ed6d1837eeb48d383704a928f81cbb3028b47/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js#L482-L540

https://github.com/google/site-kit-wp/blob/3a0ed6d1837eeb48d383704a928f81cbb3028b47/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTile/index.js#L59-L80

Please note, the comments that refer to #8484 were written before #8726 was split off from #8484. They should be taken to refer to this issue instead.

2024-06-21 12:55 UTC, ankitrox commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js
> +	 * Collects the rows of interest for the relevant audience from report.
Removed the doc.

2024-06-21 13:02 UTC, ankitrox commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js
> +				limit: configuredAudiences.length,
@techanvil Yes, this limit is required. We have added [validations](https://github.com/google/site-kit-wp/blob/develop/assets/js/modules/analytics-4/utils/validation.js#L291) in #8484 to add `fieldNames` and `limit`.

2024-06-21 13:14 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget.js
> +				limit: configuredAudiences.length,
Thanks for clarfying! For some reason I thought it wasn't a required parameter, but I see it is as per the API [docs](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Pivot).

2024-06-24 09:46 UTC, techanvil commented on assets/js/modules/analytics-4/utils/data-mock.js
> +				args?.dimensionFilters?.[ dimension ]?.some(
Hey @ankitrox I just realised `every()` would be more appropriate here:

```suggestion
				args?.dimensionFilters?.[ dimension ]?.every(
```

2024-06-25 11:20 UTC, techanvil requested changes
Hi @ankitrox, thanks for the update. This does need another update, though - I've noticed the output for the mock data is not quite as expected, and there are a couple of other points to address. Please take a look.

2024-06-25 11:20 UTC, techanvil commented on assets/js/modules/analytics-4/utils/__fixtures__/mocked-pivot-report-multi-dimension-fieldnames.json
> +    "aggregates": [
The number and shape of the aggregates is also not correct. As you can see, for each pivot, we should have effectively have the number of rows (i.e. `limit` in our output) x 3 (TOTAL, MINIMUM and MAXIMUM).

So there should be 2x3 + 3x3 + 3x3 = 24 entries in `aggregates`. As you can see the current output only has 9 entries. Also, the each entry should contain 4 dimension values.

<details>
<summary>Expected shape (taken from my example)</summary>

```json
	"aggregates": [
		{
			"dimensionValues": [
				{
					"value": "new"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				}
			],
			"metricValues": [
				{
					"value": "4892"
				},
				{
					"value": "4892"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "iOS"
				}
			],
			"metricValues": [
				{
					"value": "2104"
				},
				{
					"value": "2104"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "Android"
				}
			],
			"metricValues": [
				{
					"value": "1936"
				},
				{
					"value": "1936"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "Dublin"
				},
				{
					"value": "Ireland"
				},
				{
					"value": "RESERVED_TOTAL"
				}
			],
			"metricValues": [
				{
					"value": "1202"
				},
				{
					"value": "1202"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "Windows"
				}
			],
			"metricValues": [
				{
					"value": "690"
				},
				{
					"value": "690"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "Dublin"
				},
				{
					"value": "Ireland"
				},
				{
					"value": "RESERVED_MAX"
				}
			],
			"metricValues": [
				{
					"value": "551"
				},
				{
					"value": "551"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "iOS"
				}
			],
			"metricValues": [
				{
					"value": "551"
				},
				{
					"value": "551"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "new"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				}
			],
			"metricValues": [
				{
					"value": "551"
				},
				{
					"value": "551"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "returning"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "RESERVED_TOTAL"
				}
			],
			"metricValues": [
				{
					"value": "530"
				},
				{
					"value": "530"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "Android"
				}
			],
			"metricValues": [
				{
					"value": "430"
				},
				{
					"value": "430"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "Cork"
				},
				{
					"value": "Ireland"
				},
				{
					"value": "RESERVED_TOTAL"
				}
			],
			"metricValues": [
				{
					"value": "244"
				},
				{
					"value": "244"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_TOTAL"
				},
				{
					"value": "Sao Paulo"
				},
				{
					"value": "Brazil"
				},
				{
					"value": "RESERVED_TOTAL"
				}
			],
			"metricValues": [
				{
					"value": "196"
				},
				{
					"value": "196"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "Cork"
				},
				{
					"value": "Ireland"
				},
				{
					"value": "RESERVED_MAX"
				}
			],
			"metricValues": [
				{
					"value": "191"
				},
				{
					"value": "191"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "Windows"
				}
			],
			"metricValues": [
				{
					"value": "121"
				},
				{
					"value": "121"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "Sao Paulo"
				},
				{
					"value": "Brazil"
				},
				{
					"value": "RESERVED_MAX"
				}
			],
			"metricValues": [
				{
					"value": "83"
				},
				{
					"value": "83"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "returning"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				},
				{
					"value": "RESERVED_MAX"
				}
			],
			"metricValues": [
				{
					"value": "78"
				},
				{
					"value": "78"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "Dublin"
				},
				{
					"value": "Ireland"
				},
				{
					"value": "RESERVED_MIN"
				}
			],
			"metricValues": [
				{
					"value": "4"
				},
				{
					"value": "4"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "Cork"
				},
				{
					"value": "Ireland"
				},
				{
					"value": "RESERVED_MIN"
				}
			],
			"metricValues": [
				{
					"value": "1"
				},
				{
					"value": "1"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "Android"
				}
			],
			"metricValues": [
				{
					"value": "1"
				},
				{
					"value": "1"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "Windows"
				}
			],
			"metricValues": [
				{
					"value": "1"
				},
				{
					"value": "1"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "iOS"
				}
			],
			"metricValues": [
				{
					"value": "1"
				},
				{
					"value": "1"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "Sao Paulo"
				},
				{
					"value": "Brazil"
				},
				{
					"value": "RESERVED_MIN"
				}
			],
			"metricValues": [
				{
					"value": "1"
				},
				{
					"value": "1"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "new"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				}
			],
			"metricValues": [
				{
					"value": "1"
				},
				{
					"value": "1"
				}
			]
		},
		{
			"dimensionValues": [
				{
					"value": "returning"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				},
				{
					"value": "RESERVED_MIN"
				}
			],
			"metricValues": [
				{
					"value": "1"
				},
				{
					"value": "1"
				}
			]
		}
	],
```

</details>

<details>
<summary>Current output</summary>

```json
    "aggregates": [
      {
        "dimensionValues": [
          {
            "value": "RESERVED_MIN"
          },
          {
            "value": "city"
          }
        ],
        "metricValues": [
          {
            "value": "27"
          },
          {
            "value": "91"
          }
        ]
      },
      {
        "dimensionValues": [
          {
            "value": "RESERVED_MIN"
          },
          {
            "value": "audienceResourceName"
          }
        [...]

2024-06-25 11:20 UTC, techanvil commented on assets/js/modules/analytics-4/utils/__fixtures__/mocked-pivot-report-multi-dimension-fieldnames.json
> +    "rows": [
Lastly, the number of `rows` is not as expected either.

The number of rows should be the product of multiplying the row count for each pivot together. So with pivots returning 2, 3 and 3 rows, the report row count should be 2x3x3 = 18.

However the current output only has 6 rows, so it evidently doesn't have the right combination of values.

<details>
<summary>Expected shape (taken from my example)</summary>

```json
"rows": [
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Dublin"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "iOS"
			}
		],
		"metricValues": [
			{
				"value": "551"
			},
			{
				"value": "551"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Dublin"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Android"
			}
		],
		"metricValues": [
			{
				"value": "430"
			},
			{
				"value": "430"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Cork"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "iOS"
			}
		],
		"metricValues": [
			{
				"value": "191"
			},
			{
				"value": "191"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Dublin"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Windows"
			}
		],
		"metricValues": [
			{
				"value": "121"
			},
			{
				"value": "121"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Sao Paulo"
			},
			{
				"value": "Brazil"
			},
			{
				"value": "iOS"
			}
		],
		"metricValues": [
			{
				"value": "83"
			},
			{
				"value": "83"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Dublin"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Android"
			}
		],
		"metricValues": [
			{
				"value": "78"
			},
			{
				"value": "78"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Dublin"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "iOS"
			}
		],
		"metricValues": [
			{
				"value": "70"
			},
			{
				"value": "70"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Sao Paulo"
			},
			{
				"value": "Brazil"
			},
			{
				"value": "Android"
			}
		],
		"metricValues": [
			{
				"value": "64"
			},
			{
				"value": "64"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Sao Paulo"
			},
			{
				"value": "Brazil"
			},
			{
				"value": "Windows"
			}
		],
		"metricValues": [
			{
				"value": "36"
			},
			{
				"value": "36"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Cork"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "iOS"
			}
		],
		"metricValues": [
			{
				"value": "26"
			},
			{
				"value": "26"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Cork"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Android"
			}
		],
		"metricValues": [
			{
				"value": "21"
			},
			{
				"value": "21"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Dublin"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Windows"
			}
		],
		"metricValues": [
			{
				"value": "14"
			},
			{
				"value": "14"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Sao Paulo"
			},
			{
				"value": "Brazil"
			},
			{
				"value": "Android"
			}
		],
		"metricValues": [
			{
				"value": "12"
			},
			{
				"value": "12"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "new"
			},
			{
				"value": "Cork"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Windows"
			}
		],
		"metricValues": [
			{
				"value": "8"
			},
			{
				"value": "8"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Sao Paulo"
			},
			{
				"value": "Brazil"
			},
			{
				"value": "iOS"
			}
		],
		"metricValues": [
			{
				"value": "7"
			},
			{
				"value": "7"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Cork"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Android"
			}
		],
		"metricValues": [
			{
				"value": "4"
			},
			{
				"value": "4"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Sao Paulo"
			},
			{
				"value": "Brazil"
			},
			{
				"value": "Windows"
			}
		],
		"metricValues": [
			{
				"value": "4"
			},
			{
				"value": "4"
			}
		]
	},
	{
		"dimensionValues": [
			{
				"value": "returning"
			},
			{
				"value": "Cork"
			},
			{
				"value": "Ireland"
			},
			{
				"value": "Windows"
			}
		],
		"metricValues": [
			{
				"value": "1"
			},
			{
				"value": "1"
			}
		]
	}
],
```

<details>
<summary>Current output</summary>

```json
    "rows": [
      {
        "dimensionValues": [
          {
            "value": "properties/12345/audiences/2"
          },
          {
            "value": "Cork"
          },
          {
            "value": "India"
          },
          {
            "value": "India"
          }
        ],
        "metricValues": [
          {
            "value": "98"
          },
          {
            "value": "7"
          }
        ]
      },
      {
        "dimensionValues": [
          {
            "value": "properties/12345/audiences/2"
          },
          {
            "value": "(not set)"
          },
          {
            "value": "United Kingdom"
          },
          {
            "value": "United Kingdom"
          }
        ],
        "metricValues": [
          {
            "value": "89"
          },
          {
            "value": "62"
          }
        ]
      },
      {
        "dimensionValues": [
          {
            "value": "properties/12345/audiences/1"
          },
          {
            "value": "Dublin"
          },
          {
            "value": "United States"
          },
          {
            "value": "United States"
          }
        ],
        "metricValues": [
          {
            "value": "55"
          },
          {
            "value": "14"
          }
        ]
      },
      {
        "dimensionValues": [
          {
            "value": "properties/12345/audiences/1"
          },
          {
            "value": "Cork"
          },
          {
            "value": "India"
          },
          {
            "value": "India"
          }
        ],
        "metricValues": [
          {
            "value": "17"
          },
          {
            "value": "39"
          }
        ]
      },
      {
        "dimensionValues": [
          {
            "value": "properties/12345/audiences/2"
          },
          {
            "value": "Dublin"
          },
          {
            "value": "United States"
          },
          {
            "value": "United States"
          }
        ],
        "metricValues": [
          {
            "value": "10"
          },
          {
            "value": "73"
          }
        ]
      },
      {
        "dimensionValues": [
          {
            "value": "properties/12345/audiences/1"
          },
          {
            "value": "(not set)"
          },
          {
            "value": "United Kingdom"
          },
          {
            "value": "United Kingdom"
          }
        ],
        "metricValues": [
          {
            "value": "3"
          },
          {
            "value": "13"
          }
        ]
      }
    ],
```

</details>

2024-06-25 11:21 UTC, techanvil commented on assets/js/modules/analytics-4/utils/__fixtures__/mocked-pivot-report-multi-dimension-fieldnames.json
Btw, before getting stuck into this I'd suggest making the change to replace `country` in the third pivot as per my comment above: https://github.com/google/site-kit-wp/pull/8870#discussion_r1652483235

It should make it a bit easier to debug!

2024-06-26 16:04 UTC, techanvil requested changes
Thanks @ankitrox, just a few last comments to address and this should be good to go.

2024-06-26 16:04 UTC, techanvil commented on assets/js/modules/analytics-4/utils/data-mock.js
> +			data.pivotHeaders = options.pivots.map( ( { fieldNames } ) => {
I noticed there was still an issue with `pivotHeaders`.

<details>
<summary>The output was as follows:</summary>

```json 
  "pivotHeaders": [
    {
      "pivotDimensionHeaders": [
        {
          "dimensionValues": [
            {
              "value": "properties/12345/audiences/1"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "properties/12345/audiences/2"
            }
          ]
        }
      ],
      "rowCount": 2
    },
    {
      "pivotDimensionHeaders": [
        {
          "value": "Dublin"
        },
        {
          "value": "(not set)"
        },
        {
          "value": "Cork"
        }
      ],
      "rowCount": 3
    },
    {
      "pivotDimensionHeaders": [
        {
          "value": "United States"
        },
        {
          "value": "United Kingdom"
        },
        {
          "value": "India"
        }
      ],
      "rowCount": 3
    },
    {
      "pivotDimensionHeaders": [
        {
          "dimensionValues": [
            {
              "value": "Direct"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "Organic Search"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "Paid Social"
            }
          ]
        },
        {
          "dimensionValues": [
            {
              "value": "(other)"
            }
          ]
        }
      ],
      "rowCount": 4
    }
  ],
```

</details>

<details>
<summary>But the expectation is for the following shape:</summary>

```json
  "pivotHeaders": [
    {
      "pivotDimensionHeaders": [
        { "dimensionValues": [{ "value": "properties/12345/audiences/1" }] },
        { "dimensionValues": [{ "value": "properties/12345/audiences/2" }] }
      ],
      "rowCount": 2
    },
    {
      "pivotDimensionHeaders": [
        {
          "dimensionValues": [
            { "value": "Dublin" },
            { "value": "United States" }
          ]
        },
        {
          "dimensionValues": [
            { "value": "(not set)" },
            { "value": "United Kingdom" }
          ]
        },
        { "dimensionValues": [{ "value": "Cork" }, { "value": "India" }] }
      ],
      "rowCount": 6
    },
    {
      "pivotDimensionHeaders": [
        { "dimensionValues": [{ "value": "Direct" }] },
        { "dimensionValues": [{ "value": "Organic Search" }] },
        { "dimensionValues": [{ "value": "Paid Social" }] },
        { "dimensionValues": [{ "value": "(other)" }] }
      ],
      "rowCount": 4
    }
  ],
```

</details>

I took a look and have found a fix - in the interest of time I have pushed the change directly (see commit 82463974f19634530512bb6b3636bbdda012e23d). Please review it and if you are happy with the change, update the fixture file accordingly.

2024-06-26 16:04 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/utils.js
These utilities are specific to the `AudienceTile` component and this file can be moved to the `AudienceTile` folder.

2024-07-01 12:11 UTC, techanvil approved these changes
LGTM, nice work @ankitrox!

2024-07-01 12:11 UTC, merged