Handle rare occurance of boolean values returned in GA4 totals row in zero data report.
google/site-kit-wp pull request #8892
Opened 2024-06-18 09:36 UTC by benbowler

## Summary

Addresses issue:

- #8442

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-06-19 09:43 UTC, zutigrm requested changes
Thanks @benbowler I left you 1 small comment

2024-06-19 09:43 UTC, zutigrm commented on assets/js/modules/analytics-4/utils/is-zero-report.js
> +		typeof report?.totals !== 'object' ||
This additional check is redundant, as `report?.totals?.every?.( isEmpty )` already effectively handles this, resulting in condition being `false` if `totals` is anything other than `Array`

2024-06-19 15:39 UTC, zutigrm approved these changes
Just saw that we do object iteration on return, so checking for object type is needed. LGTM

2024-06-20 15:36 UTC, eugene-manuilov approved these changes

2024-06-20 16:05 UTC, merged