Implement RRM REST endpoint.
google/site-kit-wp pull request #8947
Opened 2024-07-01 16:05 UTC by ankitrox

## Summary

Addresses issue:

- #8791 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-07-04 10:50 UTC, nfmohit requested changes
Thank you for your excellent work on this, @ankitrox ! Please take at look my comments below:

1. Please address the code review feedback.
2. Please update the QAB.
	1. QA:Eng is not necessary here as the endpoint can simply be tested by using the following script in the browser console in a Site Kit window:
	```js
	googlesitekit.api.get( 'modules', 'reader-revenue-manager', 'publications', undefined, {
	    useCache: false,
	} )
	```
	2. Please add instructions to add publications in the publisher center which can then be seen in the network request response. Multiple publications can be added, some with the URL of the testing site and some without. It should be verified that the response only includes publications with URLs of the testing site.
	
Please let me know if you have any questions, thank you!

2024-07-04 10:50 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +		$this->user_options           = new User_Options( $this->context, $this->user->ID );
As these instances are not used outside the constructor, it isn't necessary to define class properties for them. Simple local variables should be sufficient.

```suggestion
		$options                      = new Options( $this->context );
		$user                         = $this->factory()->user->create_and_get( array( 'role' => 'administrator' ) );
		$user_options                 = new User_Options( $this->context, $this->user->ID );
```

2024-07-04 10:50 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +		$this->user_options           = new User_Options( $this->context, $this->user->ID );
As the user information is not used anywhere else, it isn't necessary to define it, `User_Options` will automatically instantiate an instance of it.

```suggestion
		$this->user_options           = new User_Options( $this->context );
```

2024-07-04 10:50 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +	public function test_get_data_endpoints() {
```suggestion
	public function test_get_datapoints() {
```

2024-07-04 10:50 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +	}
We have built-in test coverage for service entity access, using `Module_With_Service_Entity_ContractTests` trait. Please see its usage in `tests/phpunit/integration/Modules/Analytics_4Test.php` for example.

2024-07-04 10:50 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
Additional to the test coverage, it would be nice to add test coverage for the `GET:publications` endpoint. This can be done by using a fake HTTP handler and verifying an expected response.

2024-07-04 10:50 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +	 * @since 1.30.0
```suggestion
	 * @since n.e.x.t
```

2024-07-04 11:52 UTC, ankitrox commented on includes/Modules/Reader_Revenue_Manager.php
> +		 */
I have added this comment so that editor can direct us to correct method by recognising the object with this comment.

2024-07-04 11:54 UTC, ankitrox commented on includes/Modules/Reader_Revenue_Manager.php
> +				 */
Same as above.

2024-07-04 11:56 UTC, ankitrox commented on includes/Modules/Reader_Revenue_Manager.php
> +		);
It can be like this, but we need to pass

```php
[
  'filter' => $filter,
]

```

in `listPublications` method as parameter.

2024-07-05 05:21 UTC, ankitrox commented
Thank you @nfmohit . 

I've updated the PR as per feedback and left comments on couple of points (regarding var comment).

Assigning over to you for review.

2024-07-05 11:57 UTC, nfmohit requested changes
Thank you for addressing my feedback, @ankitrox ! I've left a few follow-up comments.

Besides, please also take a look at my comment regarding updating the QAB in my last CR feedback.

Thanks!

2024-07-05 11:57 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +		 */
Makes sense 👍 Let's update the comment to enforce naming conventions, e.g. "Google" should be capitalised.

```suggestion
		/**
		 * Get the SubscribewithGoogle service instance.
		 *
		 * @var Google_Service_SubscribewithGoogle
		 */
```

2024-07-05 11:57 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +				 */
Makes sense 👍 Let's update the comment to enforce naming conventions, e.g. "Google" should be capitalised.

```suggestion
				/**
				 * Get the SubscribewithGoogle service instance.
				 *
				 * @var Google_Service_SubscribewithGoogle
				 */
```

2024-07-05 11:57 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +			return true;
This return statement should be added after the try/catch block, see `Google\Site_Kit\Modules\Analytics_4::check_service_entity_access()` for reference.

2024-07-05 11:57 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +	 * @return array Permutations for site hosts or URL.
The function now returns a string.

```suggestion
	 * @return string Permutations for site hosts or URL.
```

2024-07-05 11:57 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
>  		$this->context                = new Context( GOOGLESITEKIT_PLUGIN_MAIN_FILE );
Sorry for not pointing this out earlier, but it looks like a class property isn't required for the context and is not used outside the constructor. A simple local variable should be sufficient.

2024-07-05 11:57 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +		$this->enable_feature( 'rrmModule' );
The feature flag shouldn't be required for the module internals to work.

```suggestion
```

2024-07-05 11:57 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +	 * @return Reader_Revenue_Manager
We usually reference the `Module_With_Service_Entity` class here.

```suggestion
	 * @return Module_With_Service_Entity
```

2024-07-05 11:57 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
Excellent work here, thanks!

2024-07-05 11:57 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +use Google\Site_Kit_Dependencies\Google\Service\SubscribewithGoogle as Google_Service_SubscribewithGoogle;
While we're at it, could we ensure that these are alphabetically ordered? Thanks!

2024-07-05 11:57 UTC, nfmohit commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +use Google\Site_Kit_Dependencies\Google\Service\SubscribewithGoogle\Publication;
While we're at it, could we ensure that these are alphabetically ordered? Thanks!

2024-07-05 13:42 UTC, ankitrox commented
> Thank you for addressing my feedback, @ankitrox ! I've left a few follow-up comments.
> 
> Besides, please also take a look at my comment regarding updating the QAB in my last CR feedback.
> 
> Thanks!

Thank you @nfmohit for re-review. 

I've updated the PR as per feedback and updated the QAB as well.

2024-07-05 21:01 UTC, nfmohit requested changes
Thank you for all your patience here, @ankitrox ! This looks brilliant now. I've left a couple more very minor comments, so minor that I'll address them myself, I hope that's okay. Thanks!

2024-07-05 21:31 UTC, nfmohit requested changes
@ankitrox , I just found out a few instances of the `@since` tag which were changed to `n.e.x.t` even though their respective methods were already released. I'm updating them as this is a very small change. Let's be mindful of them in the future, thank you!

2024-07-05 21:31 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +	 * @since n.e.x.t
This shouldn't have been changed. This methods was already released as part of 1.130.0.

```suggestion
	 * @since 1.130.0
```

2024-07-05 21:31 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +	 * @since n.e.x.t
Same here.

```suggestion
	 * @since 1.130.0
```

2024-07-05 21:50 UTC, nfmohit approved these changes
LGTM 👍

2024-07-05 22:04 UTC, merged

2024-07-12 19:14 UTC, aaemnnosttv commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +										'canSell'         => true,
I don't think these exist any more, do they?

2024-07-12 19:14 UTC, aaemnnosttv commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +								'verifiedDomains'       => 'example.com',
The value here should be an array

2024-07-12 19:14 UTC, aaemnnosttv commented on tests/phpunit/integration/Modules/Reader_Revenue_ManagerTest.php
> +								'publicationId'         => 'ABCDEFGH',
I find it's best to create the response using model instances, that way it's less likely to be able to return an invalid shape as we may be here.