RRM: getPublications selector
google/site-kit-wp pull request #8950
Opened 2024-07-02 06:19 UTC by ankitrox

## Summary

Addresses issue:

- #8794 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-07-09 21:08 UTC, nfmohit requested changes
Excellent work on this, thank you @ankitrox ! I've left a few comments, after addressing which, we should be able to get this merged.

Also, could you please update the QAB and mention activating the `rrmModule` feature flag and the Reader Revenue Manager module, otherwise, the request won't work.

Please take a look and feel free to let me know if you have any questions. Thank you!

2024-07-09 21:08 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/datastore/publications.test.js
> +				const initialProperties = registry
The variable name here appears wrong.

```suggestion
				const initialPublications = registry
```

2024-07-09 21:08 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/datastore/publications.test.js
> +			it( 'should not make a network request if properties for this account are already present', async () => {
```suggestion
			it( 'should not make a network request if publications are already present', async () => {
```

2024-07-09 21:08 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/datastore/__fixtures__/publications.json
While we're at it, it'd be nice to have a few more publication fixtures with different `onboardingState` values, e.g. `ONBOARDING_ACTION_REQUIRED` and `ONBOARDING_COMPLETE`.

2024-07-10 07:06 UTC, ankitrox commented
> Excellent work on this, thank you @ankitrox ! I've left a few comments, after addressing which, we should be able to get this merged.
> 
> Also, could you please update the QAB and mention the following:
> 
> 1. Activating the `rrmModule` feature flag and the Reader Revenue Manager module, otherwise, the request won't work.
> 2. It is not guaranteed that the response will be empty. The Google account used to test this may actually have publications.
> 
> Please take a look and feel free to let me know if you have any questions. Thank you!

Thanks @nfmohit .

I've updated the QAB and addressed the feedback.

Over to you for re-review.

2024-07-11 06:07 UTC, nfmohit requested changes
Thank you for addressing my feedback, @ankitrox ! Please take a look at the following additional points:

1. I have left two very minor comments below.
2. We need to update the PR branch my merging `develop` into it and fixing conflicts.
3. I should've mentioned this earlier, but the QAB should be updated to mention that the response will only include publications that are associated with the site URL.

As the above feedback is quite minor, I'll go ahead and apply them myself, I hope that's okay, thank you!

2024-07-11 06:07 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/datastore/__fixtures__/publications.json
It looks like a publication with `ONBOARDING_COMPLETE` was not added, and one with `ONBOARDING_STATE_UNSPECIFIED` was added twice. Let's change the other one to have `ONBOARDING_COMPLETE`.

2024-07-11 06:25 UTC, nfmohit approved these changes
LGTM 👍

2024-07-11 06:25 UTC, merged