Enhancement/8974 Dismiss Notifications Infrastructure
google/site-kit-wp pull request #9036
Opened 2024-07-18 13:18 UTC by jimmymadon

## Summary

Addresses issue:

- #8974 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-07-18 15:01 UTC, zutigrm requested changes
Thanks @jimmymadon, looks good overall, I left you a few suggestions.

Also for the QAB, doesn't seem necessary to go through QA:Eng, for two console log calls, it can be either done as MR, or also as part of regular QA, since QA can also test the console snippets, they have covered such tests in the past

2024-07-18 15:29 UTC, jimmymadon commented on assets/js/googlesitekit/notifications/datastore/notifications.js
> +	 * We can potentially add more notification-specific dismissal logic here in the future.
This comment was included to justify the addition of a wrapper function which is not something we usually do.

2024-07-18 15:30 UTC, jimmymadon commented on assets/js/googlesitekit/notifications/datastore/notifications.js
> +	 * We can potentially add more notification-specific logic here in the future.
Same as above - it just makes it clearer why we want to duplicate and create a wrapper function here.

2024-07-18 18:02 UTC, jimmymadon commented on assets/js/googlesitekit/notifications/datastore/notifications.test.js
> +		} );
Thanks - have refactored and added more tests to cover invalid and default params.

2024-07-18 18:06 UTC, jimmymadon commented
> Also for the QAB, doesn't seem necessary to go through QA:Eng, for two console log calls, it can be either done as MR, or also as part of regular QA, since QA can also test the console snippets, they have covered such tests in the past

@zutigrm Yeah - I prefer it being QA:Eng as an engineer might be able to do a bit more testing than just using the two console scripts, say, using the Redux toolkit. And yes, it the Merge Reviewer decides, they can QA it themselves like Matt has in the past and move the issue straight to Approval from MR. But I don't want to remove the label just in case that does not happen.

2024-07-19 11:01 UTC, zutigrm approved these changes
Thanks @jimmymadon LGTM

> Yeah - I prefer it being QA:Eng as an engineer might be able to do a bit more testing than just using the two console scripts, say, using the Redux toolkit. And yes, if the Merge Reviewer decides, they can QA it themselves like Matt has in the past and move the issue straight to Approval from MR. But I don't want to remove the label just in case that does not happen.

Got it, thanks

2024-07-19 13:58 UTC, eugene-manuilov approved these changes

2024-07-19 13:59 UTC, merged