Add the Audience Creation Notice Success component.
google/site-kit-wp pull request #9046
Opened 2024-07-19 12:45 UTC by techanvil

## Summary

Addresses issue:

- #8987 

## Relevant technical choices

Reused the `googlesitekit-subtle-notification` styling, adding modifier-level variations as appropriate.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-07-23 17:26 UTC, hussain-t requested changes
Excellent work on reusing the subtle notifications, @techanvil. However, it looks odd on smaller screens (below 450px). We should maintain the same design, including the icon, across all screen sizes, similar to `AudienceSelectionPanel/ErrorNotice`. Please note that the error notice does not have an icon.

![Screenshot 2024-07-23 at 10 54 14 PM](https://github.com/user-attachments/assets/7ddb9512-4623-4461-8a00-9eb3ec68bf4f)

2024-07-23 21:31 UTC, techanvil commented
> Excellent work on reusing the subtle notifications, @techanvil. However, it looks odd on smaller screens (below 450px). We should maintain the same design, including the icon, across all screen sizes, similar to `AudienceSelectionPanel/ErrorNotice`. Please note that the error notice does not have an icon.
> 
> ...
> 
> Update: We can hide the icon and keep the text and button inline on smaller screens.

Thanks for pointing that out, @hussain-t. I must admit I got a little carried away with the idea of reusing the subtle notification styling - when you put the two components next to each other like that the difference is pretty stark.

I've therefore reworked it to basically borrow from the Error Notice styles. In the end I've kept the icon on smaller screens as it looks OK; we can always revisit this at bug bash time if needs be.

Note that the button styling and alignment will still look inconsistent with the Error Notice - that's because this component uses the new callout button styling. I've created https://github.com/google/site-kit-wp/issues/9068 to update the Error Notice links/buttons accordingly.

2024-07-24 12:56 UTC, hussain-t approved these changes
Great work. Thanks, @techanvil. LGTM 👍

2024-07-24 16:58 UTC, tofumatt approved these changes

2024-07-24 16:59 UTC, merged