Add Setup CTA Banner for RRM
google/site-kit-wp pull request #9079
Opened 2024-07-26 15:25 UTC by ankitrox

## Summary

Addresses issue:

- #8846 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-07-31 17:01 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.test.js
> +		registry.dispatch( CORE_USER ).receiveGetDismissedItems( [] );
Since mocking with an empty array being called several times, we could move it to the `beforeEach`.

2024-07-31 17:02 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.test.js
> +		registry.dispatch( CORE_USER ).receiveGetDismissedItems( [] );
Let's move it to the `beforeEach`.

2024-07-31 17:02 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.test.js
> +		registry.dispatch( CORE_USER ).receiveGetDismissedItems( [] );
Let's move it to the `beforeEach`.

2024-07-31 17:04 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/setup/SetupMain.test.js
>  	MODULES_READER_REVENUE_MANAGER,
```suggestion
	MODULES_READER_REVENUE_MANAGER,
	READER_REVENUE_MANAGER_MODULE_SLUG,
```

2024-07-31 17:05 UTC, hussain-t commented on assets/js/components/DashboardMainApp.js
> +	const readerRevennueManagerEnabled = useFeature( 'rrmModule' );
There is a type.
```suggestion
	const readerRevenueManagerEnabled = useFeature( 'rrmModule' );
```

2024-07-31 17:06 UTC, hussain-t commented on assets/js/components/DashboardMainApp.js
> +					{ readerRevennueManagerEnabled && (
```suggestion
					{ readerRevenueManagerEnabled && (
```

2024-07-31 17:15 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.stories.js
> +}
```suggestion
const WidgetWithComponentProps = withWidgetComponentProps(
	'readerRevenueManagerSetupCTABanner'
)( ReaderRevenueManagerSetupCTABanner );

function Template() {
	return <WidgetWithComponentProps />;
}
```

2024-07-31 17:15 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.stories.js
> +				</div>
We can remove the `div`.
```suggestion
				<WithRegistrySetup func={ setupRegistry }>
					<Story />
				</WithRegistrySetup>
```

2024-08-02 10:39 UTC, hussain-t requested changes
Thanks for addressing the feedback, @ankitrox. It's mostly looking good. However, there are a couple of concerns to address.

2024-08-02 10:39 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.stories.js
> +	delay: 250,
The `label` property is missing. We don't need a `delay` unless it's necessary.
```suggestion
	label: 'Modules/ReaderRevenueManager/Components/Dashboard/ReaderRevenueManagerSetupCTABanner/Default',
```

2024-08-02 10:39 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.js
> +	WidgetNull: PropTypes.elementType,
Let's make it a required prop.
```suggestion
	WidgetNull: PropTypes.elementType.isRequired,
```

2024-08-02 10:39 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.stories.js
> +			};
We don't need the `fetchMock` since we mock with the `receiveGetDismissedItems` action.

2024-08-02 10:39 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.stories.js
> +				}
We don't need this since we have a single story that doesn't have the `args.setupRegistry` property.

2024-08-02 15:04 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.stories.js
> +	delay: 250,
As per this [comment](https://github.com/google/site-kit-wp/pull/9037#discussion_r1697204669), the `label` property is unnecessary.

2024-08-02 15:21 UTC, hussain-t requested changes
Thanks, @ankitrox. The changes almost look good. However, the mobile viewport SVG is incorrect and should be changed. Please take a look at my comments.

2024-08-02 15:21 UTC, hussain-t commented on assets/svg/graphics/reader-revenue-manager-setup-mobile.svg
@ankitrox, sorry about not flagging earlier; this is an incorrect SVG for the mobile viewport. Please get the correct one from the [Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=545-3043&t=pJxY9SvJwU7w0ax2-0).

2024-08-02 15:21 UTC, hussain-t commented on assets/js/modules/reader-revenue-manager/components/ReaderRevenueManagerSetupCTABanner.js
> +import SetupMobileSVG from '../../../../svg/graphics/reader-revenue-manager-setup-mobile.svg';
As mentioned in the other comment, this SVG is for the [intro banner](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=584-3865&t=wi3fA275mWhXfOip-4). Please use the correct one from the [Figma designs](https://www.figma.com/design/f2AFGUqfH8rqi9BpJAwhHi/Reader-Revenue-Manager?node-id=545-3043&t=pJxY9SvJwU7w0ax2-0).

2024-08-02 16:42 UTC, ankitrox commented
Sorry for missing the SVG comment @hussain-t 

I've updated the SVG and VRT for this change.

Thanks

2024-08-05 10:57 UTC, hussain-t requested changes
Thanks, @ankitrox. There are a few inconsistencies between the implementation and the Figma designs that need to be addressed. Please fix the following issues before we proceed:

1. The SVG is broken between `960px` and `~1200px` viewport:

![Screenshot 2024-08-05 at 3 36 17 PM](https://github.com/user-attachments/assets/85f466d8-260b-4866-bd97-2626aa7d0a7b)

---

2. The CTA buttons need more bottom spacing. Refer to the Figma design for the correct spacing:
**Figma**:

![Screenshot 2024-08-05 at 4 24 55 PM](https://github.com/user-attachments/assets/2241f94c-94be-4bc1-9936-7c8ba30873b4)

**Implementation**:

![Screenshot 2024-08-05 at 4 03 39 PM](https://github.com/user-attachments/assets/9155be58-9bfa-43fa-a5fe-96cdae259bc3)

---

3. The font styles for the title and description need to be corrected in the tablet designs. Please verify the styles with the Figma design for both mobile and tablet.

All these styles and fixes can be referenced from the `googlesitekit-ads-setup-cta-widget` class and applied to the `googlesitekit-reader-revenue-manager-setup-cta-widget` class in a new stylesheet.

2024-08-06 16:51 UTC, ankitrox commented
Thanks for the feedback @hussain-t .

I have addressed these styling issues by creating a separate stylesheet for the CTA banner and tested.

Over to you for CR.

Thanks again.

2024-08-06 17:21 UTC, hussain-t requested changes
Thanks for addressing the feedback, @ankitrox. This almost looks good. Let's address minor feedback on using the predefined variables for the media query. Please update the QAB to verify the mobile and tablet screens with the related Figma links.

2024-08-06 17:21 UTC, hussain-t commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-cta-banner.scss
> +			@media (min-width: $width-xlarge + px) {
Let's use the `$bp-xlarge` variable.
```suggestion
			@media (min-width: $bp-xlarge) {
```

2024-08-06 17:21 UTC, hussain-t commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-cta-banner.scss
> +				@media (min-width: $width-xlarge + px) {
```suggestion
				@media (min-width: $bp-xlarge) {
```

2024-08-06 17:21 UTC, hussain-t commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-cta-banner.scss
> +			@media (min-width: $width-desktop + 1 + px) {
```suggestion
			@media (min-width: $bp-nonTablet) {
```

2024-08-06 17:21 UTC, hussain-t commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-cta-banner.scss
> +				@media (min-width: $width-desktop + 1 + px) {
```suggestion
				@media (min-width: $bp-nonTablet) {
```

2024-08-07 04:53 UTC, ankitrox commented
Thanks @hussain-t .

Thanks for directing me to those variables, I was not aware that we have those available. I have changed the scss file to use these variables.

2024-08-07 10:01 UTC, hussain-t approved these changes
Great work, @ankitrox. LGTM 👍

2024-08-07 10:02 UTC, merged