Implement RRM setup flow
google/site-kit-wp pull request #9098
Opened 2024-07-30 21:56 UTC by nfmohit

## Summary

Addresses issue:

- #8800 

## Relevant technical choices

This PR includes one unrelated change: It stops using cache when fetching publications, as described [here](https://github.com/google/site-kit-wp/pull/9017#discussion_r1693353075).

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-02 21:25 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/components/common/PublicationCreate.js
> +		await selectPublication( publications[ 0 ] );
The change in this component ensures that the created publication is selected in store before saving settings.

2024-08-02 21:25 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/datastore/publications.js
> -			yield baseActions.syncPublicationOnboardingState();
This has been removed based on the discussion [here](https://github.com/google/site-kit-wp/pull/9017#discussion_r1693356104).

2024-08-05 13:53 UTC, kuasha420 requested changes
Excellent work @nfmohit ! This is good to go, I have a couple of nitpicks, and they're super minor so I'll push a commit to address those and get it merged to unblock other tickets. Cheers.

2024-08-05 13:53 UTC, kuasha420 commented on assets/js/modules/reader-revenue-manager/components/setup/SetupMain.stories.js
> +	// No parameters are needed for this scenario, but we still need to define the scenario object to include the story in the VRT suite.
I don't feel like this comment is needed. As time goes on, we should have the collective knowledge that the parameter doesn't need that label or anything. While this is useful comment now, it's also kind of repetitive and bloat-y.

2024-08-05 13:53 UTC, kuasha420 commented on assets/js/modules/reader-revenue-manager/index.js
> -	};
The explained rationale for this removal in the PR description SGTM :+1:

2024-08-05 14:15 UTC, kuasha420 approved these changes
Nice work @nfmohit. LGTM :tada:

2024-08-05 14:20 UTC, merged