Enhancement/8838 Use subtle notification component
google/site-kit-wp pull request #9177
Opened 2024-08-08 12:05 UTC by ankitrox

## Summary

Addresses issue:

- #8838 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-08 22:04 UTC, nfmohit requested changes
Thank you for your excellent work on this, @ankitrox. I have left a few comments, please let me know if you have any questions.

2024-08-08 22:04 UTC, nfmohit commented on assets/js/components/notifications/SubtleNotification.js
It looks like the `Grid` wrapper in this component is resulting in the notification having an unexpected horizontal padding.

Ideally, a re-usable component should not use `Grid`, `Row`, and `Cell` as wrappers. I would suggest replacing these with a simple `div`, and refactoring the usage of this component in `assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.js` such that it is wrapped with the `Grid`, `Row`, and `Cell`.

What do you think?

2024-08-09 06:10 UTC, ankitrox commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-publication-onboarding-state-notice.scss
On small screen, `SubtleNotification` hides the icon, but we need to display it for our component, so I kept it that single rule in this stylesheet. All other things are not required, so removed.

2024-08-09 10:36 UTC, ankitrox commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-publication-onboarding-state-notice.scss
Actually, I realised that some more rules are required, so added in the file.

2024-08-09 11:19 UTC, ankitrox commented on assets/js/components/notifications/SubtleNotification.js
I think that is a valid point. I've removed the use of Grid, Row, and Cell as wrappers from `SubtleNotification` component and added those wrappers in `assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.js`.

2024-08-09 11:46 UTC, ankitrox commented
@nfmohit I've made the suggested changes. Please note that because we have made changes in `SubtleNotification` component, I had to make changes in couple of more places like in `RRMSetupSuccessSubtleNotification`, `SettingsEdit` and `SettingsView`. Also, added an additional CSS rule for `SettingsEdit` to separate select and notice component with the margin.

Assigning this to you for review. Please let me know in case of any query.

Thanks

2024-08-20 11:33 UTC, nfmohit requested changes
Thank you for your work and patience on this, @ankitrox! Could you please update the branch with `develop`? Besides, I've also left a comment below. Thanks!

2024-08-20 11:33 UTC, nfmohit commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-publication-onboarding-state-notice.scss
With the recent updates to the `SubtleNotification` component, I believe this stylesheet is no longer necessary. Could you reevaluate?

2024-08-21 22:56 UTC, nfmohit requested changes
Thank you for your excellent work on this, @ankitrox! I've pointed out a few suggestions and issues in the PR.

For time constraints, I'm going to go ahead and make the updates myself. I hope that is okay with you.

Thank you!

2024-08-21 22:56 UTC, nfmohit commented on assets/js/components/notifications/SubtleNotification.js
> +		>
Thank you for making this change. It looks like this change has removed the top margin of the publication onboarding state notice in settings view. We will need to add that as part of the CSS styles.

2024-08-21 22:56 UTC, nfmohit commented on assets/js/components/notifications/SubtleNotification.js
> +	isDismissible = true,
On further thought, I think we can achieve this without introducing a new prop and just checking if `dismissLabel` is defined, similar to how we check if `ctaLabel` is defined.

2024-08-21 22:56 UTC, nfmohit commented on assets/js/components/notifications/SubtleNotification.js
>  	dismissLabel = __( 'Ok, got it', 'google-site-kit' ),
If we rely on if `dismissLabel` is defined, we need to remove the default value here. This should be fine as all current usages of this component (including stories) already specify this prop value.

```suggestion
	dismissLabel,
```

2024-08-21 22:56 UTC, nfmohit commented on assets/js/components/notifications/SubtleNotification.js
> +	onDismiss = () => {},
On further thought, I don't think this default value is required as well.

```suggestion
	onDismiss,
```

2024-08-21 22:56 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/components/dashboard/RRMSetupSuccessSubtleNotification.js
> +		dismissNotice();
It looks like this was mistakenly added back from the merge conflict. This was removed as part of a recent PR.

```suggestion
```

2024-08-21 22:56 UTC, nfmohit commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-module.scss
> +		}
This is no longer needed anymore as the publication select now has horizontal spacing around it. Instead, we need some top spacing for this in the settings view screen.

2024-08-21 22:56 UTC, nfmohit commented on assets/sass/components/reader-revenue-manager/_googlesitekit-rrm-setup-module.scss
>  		}
This should only be applied to the module setup screen.

2024-08-21 22:56 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/components/settings/SettingsEdit.js
> +		<div className="googlesitekit-setup-module googlesitekit-setup-module-edit googlesitekit-setup-module--reader-revenue-manager">
This additional class name should not be needed as we should be able to determine the screen based on already available selectors.

2024-08-21 22:56 UTC, nfmohit commented on assets/js/modules/reader-revenue-manager/components/settings/SettingsView.js
> +		<div className="googlesitekit-setup-module googlesitekit-setup-module-view googlesitekit-setup-module--reader-revenue-manager">
This additional class name should not be needed as we should be able to determine the screen based on already available selectors.

2024-08-22 00:31 UTC, nfmohit commented
Note: The failing VRT reference is unrelated to this PR.

2024-08-22 00:33 UTC, merged