Enhancement/8847 RRM GA tracking
google/site-kit-wp pull request #9179
Opened 2024-08-09 17:43 UTC by ankitrox

## Summary

Addresses issue:

- #8847

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-15 17:11 UTC, techanvil requested changes
Thanks @ankitrox, this is off to a good start. I've left a few comments for your consideration.

Furthermore, please can you add a QAB?

2024-08-16 07:05 UTC, ankitrox commented
Thank you @techanvil for reviewing the PR.

I've addressed the feedback and sending it your way for another review.

2024-08-16 11:16 UTC, techanvil requested changes
Thanks @ankitrox! This is looking good, just one last minor point to address in the PR - I would have simply applies this myself, but the issue also still needs a QAB so I am sending it back your way.

2024-08-16 11:16 UTC, techanvil commented on assets/js/modules/reader-revenue-manager/components/common/PublicationOnboardingStateNotice.test.js
> +			} );
Hmm, I didn't notice this the first time round, but it doesn't look like this needs to be async either.

More importantly though - as per my previous [comment](https://github.com/google/site-kit-wp/pull/9179#pullrequestreview-2240750196), the issue still needs a QAB. Please can you add one?

```suggestion
			act( () => {
				fireEvent.click( getByText( ctaText ) );
			} );
```

2024-08-16 13:18 UTC, ankitrox commented
@techanvil Thank you. I've updated the QAB and removed async await mentioned.

2024-08-19 12:21 UTC, techanvil approved these changes
LGTM, nice one @ankitrox!

2024-08-19 12:21 UTC, merged