VRT test failing issue
google/site-kit-wp pull request #9193
Opened 2024-08-14 07:50 UTC by zutigrm

## Summary

Addresses issue:

- #7965 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-14 15:26 UTC, eugene-manuilov requested changes
Thanks, @zutigrm. Added a few comments for you.

2024-08-14 15:26 UTC, eugene-manuilov commented on docker/backstopjs/Dockerfile
> +RUN apk add --no-cache openrc dbus
Add this to the `apk add` command that we have above.

2024-08-14 15:26 UTC, eugene-manuilov commented on docker/backstopjs/Dockerfile
> +RUN rc-update add dbus
Call this at the end of the first `RUN` command.

2024-08-14 15:26 UTC, eugene-manuilov commented on docker/backstopjs/Dockerfile
We need to update the version of the image that we generate to get it automatically re-built for everyone.

Also, it is probably worth trying to upgrade the version of the backstopjs package itself. The version that we use is `6.1.1`, the latest version is `6.3.23`. Let's upgrade it to the latest one if it doesn't cause any failure.

2024-08-15 06:54 UTC, eugene-manuilov commented on docker/backstopjs/Dockerfile
@zutigrm don't forget to upgrade the version of the image that we build as well.

2024-08-15 13:28 UTC, zutigrm commented on docker/backstopjs/Dockerfile
We don't version the image when we run the build currently. Although it doesn't seem necessary since this issue only affects CI, and locally whenver we run `env:start` it will rebuild everything with new config.

> Also, it is probably worth trying to upgrade the version of the backstopjs package itself. The version that we use is 6.1.1, the latest version is 6.3.23. Let's upgrade it to the latest one if it doesn't cause any failure.

I tried with new version, but had to revert it, as it causes constant failures in CI, although it still works fine locally.

2024-08-15 14:29 UTC, eugene-manuilov commented on docker/backstopjs/Dockerfile
Ok, thanks, @zutigrm.

2024-08-15 14:29 UTC, eugene-manuilov approved these changes

2024-08-15 14:29 UTC, merged