Improve RRM entity access check
google/site-kit-wp pull request #9198
Opened 2024-08-15 10:08 UTC by nfmohit

## Summary

Addresses issue:

- #9150 

## Relevant technical choices

This PR improves the RRM entity access checks by ensuring that the saved publication exists in the current user's publisher center.

### Unrelated changes

- While working on this issue, I noticed that the test suite for `Reader_Revenue_Manager` was missing test coverage for `Module_With_Owner` and `Module_With_Scopes` traits. I've added them.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-15 15:46 UTC, techanvil requested changes
Hey @nfmohit, the code looks good with regard to the IB, but I have a question as to whether the AC as actually correct here. Please see my comment on the issue: https://github.com/google/site-kit-wp/issues/9150#issuecomment-2291570424

2024-08-16 06:54 UTC, nfmohit commented on includes/Modules/Reader_Revenue_Manager.php
> +		return $subscribewithgoogle->publications->listPublications( array( 'filter' => $this->get_publication_filter() ) );
Updated to remove filters from service entity access check, thank you!

2024-08-16 07:37 UTC, nfmohit commented
> Hey @nfmohit, the code looks good with regard to the IB, but I have a question as to whether the AC as actually correct here. Please see my comment on the issue: [#9150 (comment)](https://github.com/google/site-kit-wp/issues/9150#issuecomment-2291570424)

Responded, thank you @techanvil !

2024-08-16 10:35 UTC, techanvil commented on includes/Modules/Reader_Revenue_Manager.php
> +		return $subscribewithgoogle->publications->listPublications( array( 'filter' => $this->get_publication_filter() ) );
Nevermind, as per https://github.com/google/site-kit-wp/issues/9150#issuecomment-2293264538 this is a false alarm :)

2024-08-16 10:48 UTC, techanvil approved these changes
LGTM, nice work @nfmohit!

2024-08-16 10:51 UTC, merged