Fix/8840 follow up fixes
google/site-kit-wp pull request #9207
Opened 2024-08-19 08:56 UTC by kuasha420

## Summary

Addresses issue:

- #8840

## Relevant technical choices

This fixes the QA observations by @hussain-t, @nfmohit and @kelvinballoo on #8840.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-19 13:17 UTC, kuasha420 commented
Note for Code Reviewer, the VRT is passing locally.

2024-08-19 21:31 UTC, nfmohit requested changes
Thank you for your work on this, @kuasha420!

I have left one small comment in my review. Apart from that, I agree with @techanvil [here](https://github.com/google/site-kit-wp/issues/8840#issuecomment-2296821101):

> Hmm, actually I am not sure it's such a good idea to dismiss a notification when the CTA is an external link.
> 
> There's no way of knowing for sure if the user successfully navigated to the link when clicking on the CTA, so it would be useful to keep the notification open in case they need to click on it again. That's my 2p on the issue, anyway.

While you're at it, would you mind removing the dismissal action from the CTA click?

Let me know what you think, thank you!

2024-08-19 21:31 UTC, nfmohit commented on assets/sass/components/dashboard/_googlesitekit-subtle-notification.scss
> +		gap: 8px;
I think we should not change the gap here and adhere to the designs to use a 16px gap. Instead, what do you think about using `flex-wrap: wrap` to let the buttons stack in extremely shrunk viewports?

2024-08-20 10:37 UTC, nfmohit approved these changes
LGTM, thank you @kuasha420 !

2024-08-20 10:38 UTC, merged