Enhance/8130 audience setup for secondary users
google/site-kit-wp pull request #9219
Opened 2024-08-21 14:20 UTC by kuasha420

## Summary

Addresses issue:

- #8130

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-26 10:28 UTC, kuasha420 commented
The failing VRT test (`google-site-kit_Modules_Analytics4_Widgets_DashboardOverallPageMetricsWidgetGA4_LoadedEntityURL_0_document_0_small.png`) is unrelated and will be fixed in #9101

2024-08-28 12:22 UTC, techanvil requested changes
Hi @kuasha420, nice work so far, it's a complicated beast this one. However, a few changes are needed. Most critically, the widget is not actually appearing on the view-only dashboard at present.

2024-09-04 13:42 UTC, kuasha420 commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationErrorWidget.js
> +								}
Thanks @techanvil. This all makes sense, but not using `ReportErrorActions` has the drawback of the "Retry didn't work? Get help" part not rendering. Not sure if that is an issue. 

I have made the changes you suggested in this [commit](https://github.com/google/site-kit-wp/pull/9219/commits/86cefd377486ea44fd7337e3c891516eee168247). Let me know if this is preferred, or we can revert and tackle this in a future issue. 

Cheers.

2024-09-04 14:47 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationErrorWidget.js
> +								}
Thanks @kuasha420. As per the [design](https://www.figma.com/design/7pSrkEy8t00BcYRAi9LjjH/Audience-Segmentation?node-id=2258-36640&node-type=FRAME&m=dev) and [current implementation](https://google.github.io/site-kit-wp/storybook/develop/?path=/story/modules-analytics4-components-audiencesegmentation-dashboard-audiencesegmentationerrorwidget--default) of the error tile, we don't actually need to show "Retry didn't work? Get help".

However, we _do_ need to show the **Request access** button for the insufficient permissions variant.

That being the case, I think we can keep the code as committed but add the following change in `SecondaryUserSetupWidget` to ensure the **Retry** button is only shown when it's _not_ an insufficient permission error:

```js
showRetryButton={ ! isInsufficientPermissionsError( setupError ) }
```

![image](https://github.com/user-attachments/assets/14afb3b1-c697-43bb-a650-c4afc9b73819)

![image](https://github.com/user-attachments/assets/28a964de-dad5-4e87-8e28-fb58e76a6cce)

2024-09-05 13:31 UTC, techanvil approved these changes
Thanks @kuasha420! Nice work. Although, while testing this during CR, I came across a few, hopefully final issues.

- The audience sync was being triggered from the `AudienceTile` while the initial setup was still in progress and this resulted in the `audienceSegmentationSetupComplete` being overridden from `false` to an empty string.
- The `AudienceSegmentationSetupCTAWidget` was still appearing for secondary users even though the primary admin had set the feature up.
- There were a couple of tests that were proving flaky in CI.

I pushed fixes for all of these issues to save another round trip.

With that all said and done, this LGTM!

2024-09-05 13:31 UTC, merged