Enhancement/#8154 - Implement the “Top content” metric handling OAuth flow
google/site-kit-wp pull request #9243
Opened 2024-08-27 09:34 UTC by hussain-t

## Summary

Addresses issue:

- #8154 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-09-02 11:19 UTC, techanvil requested changes
Thanks @hussain-t - this is mostly working, but needs a bit of further attention as per my comments.

2024-09-02 11:19 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js
This file needs a bit more attention - I've noticed a couple of glitches.

_Note that I'm using the staging environment for the service because the fix for the [`missing parameter: 'code'` issue](https://app.asana.com/0/1207894970935603/1208145446698544/f) hasn't reached production at the time of writing._

1. After pressing Cancel to close the OAuth error modal, pressing Update will briefly show the modal again before navigating back to the OAuth flow.

https://github.com/user-attachments/assets/bf34eedc-78c7-49e1-9124-c2c1e01cea94

2. When retrying after an error, proceeding to grant the permissions and retrying again, the error modal briefly appears while the custom dimension is being created.

https://github.com/user-attachments/assets/741b9893-7c42-48d3-b6f3-188ca49ab029

I've dug in and have a proposed fix, please take a look and see what you think.

```diff
diff --git a/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js b/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js
index 0eaae22ce4..56e345d995 100644
--- a/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js
+++ b/assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js
@@ -127,6 +127,7 @@ export default function AudienceTilePagesMetric( {
 	const setupErrorCode = useSelect( ( select ) =>
 		select( CORE_SITE ).getSetupErrorCode()
 	);
+	const { setSetupErrorCode } = useDispatch( CORE_SITE );
 
 	const hasOAuthError = autoSubmit && setupErrorCode === 'access_denied';
 
@@ -167,11 +168,18 @@ export default function AudienceTilePagesMetric( {
 			autoSubmit: false,
 		} );
 		clearPermissionScopeError();
+		setSetupErrorCode( null );
 		clearError( 'createCustomDimension', [
 			propertyID,
 			CUSTOM_DIMENSION_DEFINITIONS.googlesitekit_post_type,
 		] );
-	}, [ clearError, clearPermissionScopeError, propertyID, setValues ] );
+	}, [
+		clearError,
+		clearPermissionScopeError,
+		propertyID,
+		setSetupErrorCode,
+		setValues,
+	] );
 
 	const isMobileBreakpoint = [ BREAKPOINT_SMALL, BREAKPOINT_TABLET ].includes(
 		breakpoint
@@ -208,7 +216,8 @@ export default function AudienceTilePagesMetric( {
 					isSaving={ isSaving }
 				/>
 				{ ( ( customDimensionError && ! isSaving ) ||
-					isRetryingCustomDimensionCreate ||
+					( isRetryingCustomDimensionCreate &&
+						! isAutoCreatingCustomDimensionsForAudience ) ||
 					hasOAuthError ) && (
 					<AudienceErrorModal
 						apiErrors={ [ customDimensionError ] }

```

2024-09-05 08:21 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js
Thanks, @techanvil. I've applied the fixes as you suggested.

2024-09-05 08:21 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			await act( waitForDefaultTimeouts );
Updated.

2024-09-05 08:21 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			await act( waitForDefaultTimeouts );
Updated.

2024-09-05 08:21 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			await act( waitForDefaultTimeouts );
Updated.

2024-09-05 08:22 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			await waitFor( () => {
Removed.

2024-09-05 08:22 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			await waitFor( () => {
Removed.

2024-09-05 08:22 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			await waitFor( () => {
Removed.

2024-09-05 08:22 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			} );
Updated.

2024-09-05 08:22 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			} );
Updated.

2024-09-05 08:23 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +				screen.getByRole( 'button', { name: /update/i } )
Removed.

2024-09-05 08:23 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +			} );
I have updated the tests. However, we need to keep `waitFor` for a couple of tests.

2024-09-05 08:24 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +				'Test Post 1 - This is a very long title to test the audience segmentation tile that it wraps up and doesn not extend to the next line. It should show ellipsis instead. It must also have some gap
Updated.

2024-09-05 08:24 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +
Removed.

2024-09-05 08:24 UTC, hussain-t commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/index.test.js
> +
Removed.

2024-09-06 15:00 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/AudienceTile/AudienceTilePagesMetric.js
Great, thanks!

2024-09-06 15:02 UTC, techanvil approved these changes
That's great, thanks @hussain-t. LGTM!

2024-09-06 15:02 UTC, merged