Enhancement/8978 Refactor UnsatisfiedScopesAlert
google/site-kit-wp pull request #9252
Opened 2024-08-28 22:01 UTC by jimmymadon

## Summary

Addresses issue:

- #8978 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-08-30 19:49 UTC, tofumatt requested changes
I just have a few comments on the code itself, all quite minor.

But when I tried to get the Gathering data notification to appear by setting up Site Kit on my development site with the Tester Plugin, I never saw the notification 🤔 

Based on the QA Brief I expected it to appear, but nothing did.

2024-08-31 20:40 UTC, jimmymadon commented on assets/js/components/notifications/ErrorNotifications.js
> +				viewContext={ viewContext }
This has been lingering on from my first issue - I wanted to refactor this and kept postponing it! But just did this now! Thanks!

2024-08-31 20:47 UTC, jimmymadon commented on assets/js/components/notifications/UnsatisfiedScopesAlert.js
> +				description={ <Description description={ message } /> }
Haha - renamed to text!

2024-08-31 20:47 UTC, jimmymadon commented on assets/js/googlesitekit/notifications/components/common/ActionsCTALinkDismiss.js
> +			></CTALink>
Thanks!

2024-08-31 21:58 UTC, jimmymadon commented
@tofumatt Thanks for the review. This seems better now. Was going crazy with all the testing so missed checking the remaining notifications after my last few modifications.

2024-09-02 15:01 UTC, tofumatt approved these changes
Looks good 👍🏻

2024-09-02 15:43 UTC, tofumatt commented
![Screenshot 2024-09-02 at 16 40 13](https://github.com/user-attachments/assets/ddcc62e9-7386-45c8-87b3-0966b3cb09e8)

VRT failure here is totally unrelated, so I'm fixing it here then merging this. 😅

2024-09-02 16:19 UTC, merged