Do not load banner till dismiss count is available.
google/site-kit-wp pull request #9270
Opened 2024-09-02 13:50 UTC by ankitrox

## Summary

Addresses issue:

- #9231

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-09-03 12:34 UTC, techanvil requested changes
Thanks @ankitrox, a few changes are needed here - please see my comments.

2024-09-03 12:34 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js
>  			await act( () => waitForTimeouts( 30 ) );
We can verify the widget is no longer rendered, and remove the `waitForTimeouts()` at the end:

```suggestion

				expect( container ).toBeEmptyDOMElement();
			} );
```

2024-09-03 12:34 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js
> +			).not.toBeInTheDocument();
I'd suggest checking `container` is empty, it's a bit more of a complete test:

```suggestion
			const { container } = render(
				<AudienceSegmentationSetupCTAWidget
					Widget={ Widget }
					WidgetNull={ WidgetNull }
				/>,
				{
					registry,
				}
			);

			expect( container ).toBeEmptyDOMElement();
```

2024-09-03 12:34 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js
> +				await dismissPrompt(
Hmm, maybe we should _not_ make this async so the dismissal requests can potentially fire in parallel:

```suggestion
			onSuccess: () => {
				dismissPrompt(
```

2024-09-03 12:34 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js
> +
`getPromptDismissCount` doesn't have a resolver, so it doesn't make sense to try to wait for it to resolve - `dismissCountLoaded` will only ever be `false`. We can instead check the `getDismissedPrompts` resolver.

```suggestion
	const dismissedPromptsLoaded = useSelect( ( select ) =>
		select( CORE_USER ).hasFinishedResolution( 'getDismissedPrompts', [] )
	);
```

2024-09-03 12:34 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.js
> +		! dismissCountLoaded
As per the above name change:

```suggestion
		! dismissedPromptsLoaded
```

2024-09-03 12:34 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js
> +
As above, `getPromptDismissCount` doesn't have a resolver so it doesn't make sense to try to interact with it.

You should instead populate and resolve `getDismissedPrompts()`.

```suggestion
		const currentTimeInSeconds = Math.floor( Date.now() / 1000 );

		registry.dispatch( CORE_USER ).receiveGetDismissedPrompts( {
			[ AUDIENCE_SEGMENTATION_SETUP_CTA_NOTIFICATION ]: {
				expires: currentTimeInSeconds - 10,
				count: 0,
			},
		} );

		registry
			.dispatch( CORE_USER )
			.finishResolution( 'getDismissedPrompts', [] );
```

2024-09-03 12:34 UTC, techanvil commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget.test.js
> +				] );
As above:

```suggestion
				.startResolution( 'getDismissedPrompts', [] );
```

2024-09-03 15:44 UTC, ankitrox commented
Thanks so much @techanvil for looking into this and adding the feedback.

I've made the changes and assigning back to you for re-review.

2024-09-04 08:58 UTC, techanvil approved these changes
That's great, thanks @ankitrox. LGTM!

2024-09-04 08:59 UTC, merged