Enhancement/8979 Refactor Unsatisfied Scopes Alert GTE
google/site-kit-wp pull request #9272
Opened 2024-09-02 21:05 UTC by jimmymadon

## Summary

Addresses issue:

- #8979 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-09-02 22:58 UTC, tofumatt requested changes
There are several tests _removed_ from this PR without being reinstated elsewhere. Mainly the one that tests that a notification appears when missing scopes.

It'd be valuable to add that back, I think—it's actually probably more useful than the VRT, which frankly I'd be fine if you just removed (the story itself is useful, but probably doesn't warrant its own VRT 🤷🏻‍♂️ )

2024-09-02 23:07 UTC, jimmymadon commented
> There are several tests _removed_ from this PR without being reinstated elsewhere. Mainly the one that tests that a notification appears when missing scopes.
> 
> It'd be valuable to add that back, I think—it's actually probably more useful than the VRT, which frankly I'd be fine if you just removed (the story itself is useful, but probably doesn't warrant its own VRT 🤷🏻‍♂️ )

@tofumatt I've created https://github.com/google/site-kit-wp/issues/9273 specifically for the reason mentioned in the Feature Description there. This will require some thinking and a nice pattern of its own. I discussed if there was any way to "quick-fix" or hack tests here with @techanvil but we couldn't come up with one easy way for now - so we decided to create a new issue instead of delaying these. The tests actually cover some very simple selectors for now - so if we can test those conditions in runtime, we should be fine.

2024-09-03 09:30 UTC, tofumatt approved these changes

2024-09-03 09:30 UTC, tofumatt approved these changes
Fair enough, I've reviewed the other issue's ACs and moved it to IB. This looks good to go then 🙂

2024-09-03 09:33 UTC, merged