Reduce frequency of AdsLinks checks.
google/site-kit-wp pull request #9275
Opened 2024-09-03 10:24 UTC by ankitrox

## Summary

Addresses issue:

- #9141

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-09-03 14:35 UTC, benbowler approved these changes
Looking good, and tested, thanks @ankitrox. Moving to MR.

2024-09-03 21:01 UTC, aaemnnosttv requested changes
Thanks @ankitrox ! This one is almost there, but we can simplify this a fair bit with an alternate approach.

2024-09-04 08:38 UTC, ankitrox commented on includes/Modules/Analytics_4/Synchronize_AdsLinked.php
> +		}
Thank you @aaemnnosttv . I have made this change.

2024-09-04 08:38 UTC, ankitrox commented on includes/Modules/Analytics_4/Synchronize_AdsLinked.php
> +	 * @param Context      $context      Context instance.
Noted.

2024-09-06 16:32 UTC, aaemnnosttv requested changes
@ankitrox Sorry if this wasn't clear, but given that the added `Context` instance is no longer necessary since we aren't accessing query parameters, those related additions/changes here should be reverted. Thanks!

2024-09-09 04:10 UTC, ankitrox commented
> @ankitrox Sorry if this wasn't clear, but given that the added `Context` instance is no longer necessary since we aren't accessing query parameters, those related additions/changes here should be reverted. Thanks!

Hi @aaemnnosttv ,

Sorry for the confusion, I did not get it at the first place.

You are right, `$context` is no longer required, so I have removed it and pushed the changes.

Thanks

2024-09-11 02:54 UTC, aaemnnosttv approved these changes
LGTM, thanks @ankitrox !

2024-09-11 03:18 UTC, merged