Setup multiple dismissals for CTA banner along with tooltip.
google/site-kit-wp pull request #9306
Opened 2024-09-05 12:04 UTC by ankitrox

## Summary

Addresses issue:

- #9257 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-09-09 12:25 UTC, techanvil requested changes
Thanks @ankitrox, this is looking good, but is missing the requirement to change the dismissal CTA to "Don’t show again" on the second showing of the banner.

2024-09-10 14:04 UTC, ankitrox commented
@techanvil Thanks for looking into it.

I've updated the condition for displaying the CTA text. Moving it to CR.

2024-09-10 15:53 UTC, techanvil approved these changes
LGTM, nice one @ankitrox!

2024-09-10 15:57 UTC, techanvil commented on assets/js/modules/reader-revenue-manager/components/dashboard/ReaderRevenueManagerSetupCTABanner.js
> +						'You can always enable reader revenue manager from Settings later',
Whoops - I completely missed this, "Reader Revenue Manager" should have capital initials.

I'll apply the change myself to save the round trip.

```suggestion
						'You can always enable Reader Revenue Manager from Settings later',
```

2024-09-10 16:24 UTC, merged