Implement the “no audiences” banner error state.
google/site-kit-wp pull request #9387
Opened 2024-09-20 15:59 UTC by ankitrox

## Summary

Addresses issue:

- #8190

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-09-25 09:14 UTC, benbowler approved these changes
Thanks @ankitrox, tested and reviewed and the implementation is simple and works well.

2024-09-26 04:21 UTC, nfmohit requested changes
Nice work here, thank you @ankitrox.

I've added a few comments, particularly with a focus on the incorrect error variants due to usage of an incorrect prop.

As we're under a time-constraint, I hope you don't mind if I go ahead and make these changes myself.

Thanks!

2024-09-26 04:21 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceTilesWidget/index.test.js
> +		} );
Instead of mocking the action, we should be able just to mock the POST request. This would be a simpler and arguably more accurate approach.

2024-09-26 05:09 UTC, nfmohit approved these changes
LGTM, nice work, @ankitrox ! 👍 

_Note: I've verified that the failing tests in CI are unrelated to this PR and are being addressd as part of other issues._

2024-09-26 05:11 UTC, merged