Enhancement/9281 refactor audience segementation setup success notification
google/site-kit-wp pull request #9434
Opened 2024-09-29 21:21 UTC by jimmymadon

## Summary

Addresses issue:

- #9281 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-10-09 09:19 UTC, benbowler requested changes
Hey @jimmymadon, the implementation looks good and tests well.

Looking at the failing checks it appears there are E2E tests and perhaps JS test failures which are directly related to these changes. Can you check those?

2024-10-09 23:30 UTC, jimmymadon commented
@benbowler Thanks - I think the E2E test failures are now just related to the cron issue. Adding the feature flag helped everything else.

2024-10-10 11:18 UTC, benbowler approved these changes
Thanks @jimmymadon, good update to wrap the notification in the feature flag. I've looked through the changes and re-tested and moving to MR.

2024-10-13 12:07 UTC, eugene-manuilov approved these changes

2024-10-13 12:09 UTC, merged