Issue / 9439 Logic to Trigger Old vs New Conversion Metrics Modal
google/site-kit-wp pull request #9585
Opened 2024-10-31 06:58 UTC by 10upsimon

## Summary

Addresses issue:

- #9439

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-10-31 07:05 UTC, 10upsimon commented
Adding an update following internal sync and comms with @zutigrm:

The logic needed to be tweaked as the current user input options are saved to the user input settings store, they're just not persisted. This affects the modal logic (specifically due to how we retrieve the user input values) as the old vs new would always be the same in this case.

The solution was to introduce a temporary form and set the old/current site purpose. This value is in turn used in the modal to get the current values against the existing purpose slug stored in the temporary form store. The temporary form is reset on modal save so the logic can be repeated for future changes.

2024-11-06 17:57 UTC, tofumatt approved these changes

2024-11-06 18:03 UTC, tofumatt requested changes
It looks like this is failing VRTs even after I updated it with `develop`. Can you take a look ?

(It looks like the current metrics aren't visible in the story anymore:)

![google-site-kit_KeyMetrics_ConfirmSitePurposeChangeModal_0_document_1_medium](https://github.com/user-attachments/assets/819d130e-5867-4b98-9b2f-2acdaa781ad1)

2024-11-07 16:39 UTC, tofumatt approved these changes

2024-11-07 16:39 UTC, merged