Update Selection Panels to be in-view aware
google/site-kit-wp pull request #9631
Opened 2024-11-07 08:52 UTC by ankitrox

## Summary

Addresses issue:

- #9312 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-11-07 09:02 UTC, ankitrox commented on assets/js/components/DashboardMainApp.js
> +			{ showKeyMetricsSelectionPanel && <MetricsSelectionPanel /> }
This will be removed when https://github.com/google/site-kit-wp/pull/9630 will be merged.

2024-11-07 09:02 UTC, ankitrox commented on assets/js/components/DashboardMainApp.js
This will be removed when https://github.com/google/site-kit-wp/pull/9630 will be merged.

2024-11-13 21:43 UTC, nfmohit requested changes
Brilliant work on this, @ankitrox, thank you! Please see the following notes:

1. In the QAB, it might be worth specifying the following AC:
> The flicker that PR https://github.com/google/site-kit-wp/pull/7779 fixed in the Metrics Selection Panel should not return as a result of these changes.
2. Additionally, I think it might also be worth doing a `QA:Eng` on this one in addition to general QA to ensure the following AC is met:
> An observable result of this is that the panels should not trigger any API requests upon page load, unless the request is explicitly determined to be required.
3. I've left a few comments in the code, please take a look, thank you!

Please let me know if you have any questions, thanks!

2024-11-13 21:43 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.test.js
> +			afterEach( async () => {
I think I understand what you're doing here, but this feels quite unorthodox compared to how we usually compose tests, namely:

1. We usually do not do assertions in `beforeEach` or `afterEach`.
2. All test cases usually read as natural language, e.g. "it should do something".

Could you possibly enlighten why we can't stick to the previous `it.each()` approach which was much cleaner?

2024-11-13 21:43 UTC, nfmohit commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSelectionPanel/index.test.js
> +			afterEach( async () => {
Same question as above.

2024-11-13 21:43 UTC, nfmohit commented on assets/js/components/KeyMetrics/MetricsSelectionPanel/Panel.js
> + * Site Kit by Google, Copyright 2023 Google LLC
Very nitpicky, but as this is a newer component, should we update the year?

```suggestion
 * Site Kit by Google, Copyright 2024 Google LLC
```

2024-11-15 08:33 UTC, ankitrox commented
Thank you @nfmohit for reviewing the PR.

I have made the requested changes and also changed tests to use `it.each()` by consolidating some common steps.

Over to you for another check.

2024-11-16 17:24 UTC, merged