Enhancement/9568 Improve rendering time for SiwG Setup CTA
google/site-kit-wp pull request #9684
Opened 2024-11-13 20:45 UTC by jimmymadon

## Summary

Addresses issue:

- #9568 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-11-18 14:48 UTC, aaemnnosttv requested changes
Thanks @jimmymadon – I made a few changes in trying to work out the test instabilities which I elaborated on in our DM, just a few outstanding points to address.

2024-11-19 16:35 UTC, jimmymadon commented on assets/js/modules/analytics-4/components/audience-segmentation/dashboard/AudienceSegmentationSetupCTAWidget/index.js
> +					NOTIFICATION_GROUPS.DEFAULT,
The notification to render is actually the "Audience Segmentation Setup Success Subtle Notification" which renders when the setup is successful. This Setup CTA Component itself is not yet 'refactored' to use the new Notifications infrastructure. 

On a side note, this is still a "hack" which should be removed with #9453

2024-11-19 23:38 UTC, jimmymadon commented
@aaemnnosttv Thanks for the great clean up here and for introducing this new pattern to focus on testing `checkRequirements` alone. I've added a JS test for the groupID filtering.

The VRT failure seems to be unrelated to this PR.

2024-11-20 20:29 UTC, aaemnnosttv approved these changes
LGTM, thanks @jimmymadon !

2024-11-20 20:29 UTC, merged