Issue / 9375 Full Screen KMW Selection Panel
google/site-kit-wp pull request #9715
Opened 2024-11-20 12:41 UTC by 10upsimon

## Summary

Addresses issue:

- #9375

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-11-20 19:01 UTC, eugene-manuilov requested changes
Thanks, @10upsimon. Added some comments for you. Please, take a look.

2024-11-26 09:21 UTC, 10upsimon commented on tests/backstop/reference/google-site-kit_KeyMetrics_FullScreenMetricsSelectionPanel_0_document_1_medium.png
@eugene-manuilov resolved in recent commits, thank you.

2024-11-26 09:21 UTC, 10upsimon commented on tests/backstop/reference/google-site-kit_KeyMetrics_FullScreenMetricsSelectionPanel_0_document_0_small.png
@eugene-manuilov resolved in recent commits, thank you.

2024-11-26 09:21 UTC, 10upsimon commented on includes/Core/Assets/Assets.php
> +			new Script(
@eugene-manuilov resolved in recent commits, thank you.

2024-11-26 10:27 UTC, 10upsimon commented on assets/js/components/KeyMetrics/MetricsSelectionPanel/PanelContent.js
> +} ) {
Thanks @eugene-manuilov this has been resolved in recent commits.

2024-11-26 12:37 UTC, eugene-manuilov commented on tests/backstop/reference/google-site-kit_KeyMetrics_FullScreenMetricsSelectionPanel_0_document_1_medium.png
This layout seems to be still broken. Could you please fix style issues?

2024-11-26 12:37 UTC, eugene-manuilov commented on tests/backstop/reference/google-site-kit_KeyMetrics_FullScreenMetricsSelectionPanel_0_document_0_small.png
Footer here is also broken, we need to adjust styles to make footer elements be properly aligned.

2024-11-26 12:37 UTC, eugene-manuilov commented on tests/backstop/reference/google-site-kit_KeyMetrics_FullScreenMetricsSelectionApp_0_document_0_small.png
Same here. Footer should be at the very bottom of the page, right?

2024-11-26 12:37 UTC, eugene-manuilov commented on assets/js/components/metric-selection/FullScreenMetricSelectionApp.js
> +														"Site Kit will start collecting data and add them on your dashboard. You can change your selection later on from Site Kit's main dashboard.",
@10upsimon, did you miss this change? We need to use `’` instead of `'` in our translatable text.

2024-11-26 12:46 UTC, eugene-manuilov requested changes
Thanks, @10upsimon. A few more comments from me. We still need to adjust styles to make it look correct on all breakpoints and after that it will be good to go.

2024-11-26 12:46 UTC, eugene-manuilov commented on assets/js/components/KeyMetrics/MetricsSelectionPanel/SelectionPanelFooter.js
> +				{ 'fullscreen' !== variation && itemCountElement }
How many variations are we going to have? Just two: `default` and `fullscreen`, right? Then let's probably use `isFullscreen` instead of `variation`.

2024-11-26 12:46 UTC, eugene-manuilov commented on assets/js/components/KeyMetrics/MetricsSelectionPanel/PanelContent.js
> +import classnames from 'classnames';
This should be in the external dependencies list.

2024-11-27 15:04 UTC, eugene-manuilov approved these changes
Thanks, @10upsimon. LGTM.

2024-11-27 15:04 UTC, merged