Output consent mode JS via `wp_print_inline_script_tag()`
google/site-kit-wp pull request #9726
Opened 2024-11-21 02:09 UTC by westonruter

## Summary

Addresses issue:

- #9725

## Relevant technical choices

Use `wp_print_inline_script_tag()`

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [x] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-11-21 17:46 UTC, felixarntz approved these changes
@westonruter This looks good to me, but it would be great to get someone more active in the project to approve as a 2nd sign-off.

@aaemnnosttv Would you be able to get this into one of the next releases? It blocks https://github.com/WordPress/performance/pull/1686 that we're exploring to improve performance implications of `gtag`.

(I believe Site Kit may have a few more spots where it would ideally use `wp_print_inline_script_tag()` rather than direct output of the script. Maybe that's something to do in a separate PR, if you agree.)

2024-11-25 22:12 UTC, aaemnnosttv requested changes
Thanks @westonruter – this looks like a nice improvement, although like I mentioned on the issue, our minimum supported version of WP is 5.2 but this function wasn't added until 5.7. We do have a BC helper class which makes this available, but without it, this is breaking E2E in the older version.
https://github.com/google/site-kit-wp/actions/runs/11945338420/job/33297846941?pr=9726#step:11:387

I also noted another instance where this could be applied which may not have been there when you opened this, I'm not sure. LMK if you have any questions 👍

2024-11-26 00:21 UTC, westonruter commented
Note: I do not have Site Kit set up for local development, so these changes I applied via the GitHub UI and thus I'm relying on GHA to check for any problems.

2024-11-26 00:34 UTC, westonruter commented
The E2E tests are passing for WordPress 5.2.21, AMP 1.5.5.

But they're failing for latest and trunk. The errors don't seem to indicate they're related to the code in this PR, however, so perhaps they just need to be restarted.

2024-11-26 01:00 UTC, felixarntz approved these changes

2024-11-26 20:48 UTC, aaemnnosttv approved these changes
Great, thanks @westonruter !

2024-11-26 20:55 UTC, merged