Enhancement/9600 cta banner spacing
google/site-kit-wp pull request #9849
Opened 2024-12-09 14:37 UTC by ankitrox

## Summary

Addresses issue:

- #9600 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-12-09 20:00 UTC, aaemnnosttv requested changes
Thanks @ankitrox – it's great to see some consistency come to these 😄 Aside from the few comments, I noticed one of the cases in AdBlocking Recovery looks off still. Would you have a look?
<img width="889" alt="image" src="https://github.com/user-attachments/assets/0af974d5-2fc4-47a8-b6b9-27e49cbfc771">

2024-12-10 07:11 UTC, ankitrox commented on assets/sass/components/ads/_googlesitekit-ads-setup-banner.scss
> +			@media (min-width: $width-tablet + 1 + px) {
Thanks @aaemnnosttv. 

I have updated all instances in PR to use the `$bp-nonMobile` variable.

2024-12-10 07:14 UTC, ankitrox commented on assets/sass/components/adsense/_googlesitekit-adsense-ad-blocking-recovery.scss
> +				gap: 10px;
That's a nice suggestion. I have [added two variables](https://github.com/google/site-kit-wp/pull/9849/files#diff-71fa429f5fb0c3b90b41166e67b2847b0c1ac178a4a19d3d61a2dbd66e684abdR359-R360) `$cta-gap-phone` and `$cta-gap-tablet` to be used for CTA flex gap.

2024-12-10 07:18 UTC, ankitrox commented
> Thanks @ankitrox – it's great to see some consistency come to these 😄 Aside from the few comments, I noticed one of the cases in AdBlocking Recovery looks off still. Would you have a look? <img alt="image" width="889" src="https://private-user-images.githubusercontent.com/1621608/393986737-0af974d5-2fc4-47a8-b6b9-27e49cbfc771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTQwMzQsIm5iZiI6MTczMzgxMzczNCwicGF0aCI6Ii8xNjIxNjA4LzM5Mzk4NjczNy0wYWY5NzRkNS0yZmM0LTQ3YTgtYjZiOS0yN2U0OWNiZmM3NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMDY1NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGExNWY4ODI0ZDZkYmE4MzVhZWFlMjUyOTBhYWRiMGUwZTcwNDEzZTgyZThjNTYyOTdmODIxNjU1MGQxMTc2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MSuJreKSgRXqmLdbJzbTMOldITY7dloZlunz60dVclA">

Thank you for reviewing the PR @aaemnnosttv.

For AdBlocking Recovery, I've added the gap of 30px and for tablet and above, it can be 10px as for the other setup CTA banners.

I have made this change and tested on mobile screen which looks fine to me (like the previous one).

Can you please let me know if these changes looks fine or if there is any further suggestion.

Thank you.

2024-12-10 21:17 UTC, aaemnnosttv approved these changes
Great, thanks @ankitrox !

2024-12-10 21:18 UTC, merged