Schedule cron task only if FPM is enabled
google/site-kit-wp pull request #9850
Opened 2024-12-09 21:36 UTC by nfmohit

## Summary

Addresses issue:

- #9842 

## Relevant technical choices

This PR schedules the cron task to obtain FPM server requirement status only if FPM is enabled.

### Deviations from IB

> * Replace the `getFirstPartyModeSettings` selector call with the `fetchGetFPMServerRequirementStatus` action

This PR persists the `getFirstPartyModeSettings` selector call as it is needed to see if FPM is enabled or if server requirement status fields are not set.

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-12-10 12:12 UTC, techanvil requested changes
Thanks @nfmohit, this is looking good and working well in my testing.

I would however suggest a small but significant change from the IB, and have left another, minor comment. Please take a look.

2024-12-10 20:13 UTC, nfmohit commented on includes/Core/Tags/First_Party_Mode/First_Party_Mode_Cron.php
> +		First_Party_Mode_Settings $first_party_mode_settings
Updated, thank you!

2024-12-10 20:17 UTC, nfmohit commented
> Thanks @nfmohit, this is looking good and working well in my testing.
> 
> I would however suggest a small but significant change from the IB, and have left another, minor comment. Please take a look.

Back to you for another pass, thank you @techanvil !

2024-12-11 10:31 UTC, techanvil approved these changes

2024-12-11 10:37 UTC, merged