Setup CTA banners momentarily appear again when dismissing their Admin Settings Tooltip
google/site-kit-wp pull request #9890
Opened 2024-12-16 09:35 UTC by ankitrox

## Summary

Addresses issue:

- #9791 

## Relevant technical choices

## PR Author Checklist

- [x] My code is tested and passes existing unit tests.
- [x] My code has an appropriate set of unit tests which all pass.
- [x] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [x] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [x] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2024-12-19 10:27 UTC, benbowler requested changes
Hey @ankitrox, this is looking good, especially the additional implementation on the dismiss-items store and the addition of test coverage across the CTAs.

I have added one key change inline.

Can you also add a QA Brief to the main ticket.

2024-12-19 10:27 UTC, benbowler commented on assets/js/googlesitekit/datastore/user/dismissed-items.js
> +					[ stringifyObject( slug ) ]: isDismissing,
Evan actually mentioned in comments on the IB that the slugs are unique so we don't have to use `stringifyObject` here we can just set the is dismissing state on for the slug as passed.

2024-12-19 10:27 UTC, benbowler commented on assets/js/googlesitekit/datastore/user/dismissed-items.js
> +		return !! state.isDismissingItems[ stringifyObject( slug ) ];
Then you can remove the use of `stringifyObject` here too.

2024-12-19 10:27 UTC, benbowler commented on assets/js/googlesitekit/datastore/user/prompts.js
> +					[ stringifyObject( slug ) ]: isDismissing,
Another `stringifyObject` that can be removed.

2024-12-19 10:27 UTC, benbowler commented on assets/js/googlesitekit/datastore/user/prompts.js
> +		return !! state.isDismissingPrompts[ stringifyObject( slug ) ];
Another `stringifyObject` that can be removed.

2024-12-19 10:27 UTC, benbowler commented on assets/js/googlesitekit/datastore/user/dismissed-items.test.js
> +		} );
In `prompts.test.js` you have tests to confirm the main `dismissPrompt` action sets and unsets the dismissing state correctly, you could add similar tests here to make sure this functionality is not broken future updates to `dismissItem`.

2024-12-19 13:45 UTC, ankitrox commented
Thanks for reviewing the PR @benbowler and adding your valuable suggestions.

I've made the suggested changes and added couple of tests as mentioned into dismiss-items tests suite.

Over to you for another review.

Thank you.

2024-12-20 09:39 UTC, benbowler approved these changes
Thanks for the updates, reviewed, re-tested and moving to MR.

2025-01-02 18:10 UTC, techanvil requested changes
Hi @ankitrox, this is looking good but could use a few tweaks, please see my comments.

2025-01-02 18:10 UTC, techanvil commented on assets/js/googlesitekit/datastore/user/dismissed-items.js
> +			const { slug, state: isDismissing } = payload;
I realise this is following the approach outlined in the IB, but using "state" in the names here is really quite confusing, as "state" is such a fundamental Redux concept. Passing an argument called `state` to an action makes it look like a selector at first glance.

Rather than overloading this term I'd suggest we make the following changes:

```suggestion
	setIsItemDimissing( slug, isDismissing ) {
		return {
			payload: { slug, isDismissing },
			type: 'SET_IS_ITEM_DISMISSING',
		};
	},
};

const baseReducer = ( state, { type, payload } ) => {
	switch ( type ) {
		case 'SET_IS_ITEM_DISMISSING':
			const { slug, isDismissing } = payload;
```

2025-01-02 18:10 UTC, techanvil commented on assets/js/googlesitekit/datastore/user/prompts.js
> +			type: 'SET_PROMPT_DISMISSING_STATE',
As above:

```suggestion
	setIsPromptDimissing( slug, isDismissing ) {
		return {
			payload: { slug, isDismissing },
			type: 'SET_IS_PROMPT_DISMISSING',
```

2025-01-02 18:10 UTC, techanvil commented on assets/js/googlesitekit/datastore/user/prompts.js
> +			const { slug, state: isDismissing } = payload;
As above:

```suggestion
		case 'SET_IS_PROMPT_DISMISSING':
			const { slug, isDismissing } = payload;
```

2025-01-02 18:10 UTC, techanvil commented on assets/js/modules/adsense/components/dashboard/AdSenseConnectCTAWidget.js
> +		! isDismissingItem
It would be more consistent with the surrounding code to check `=== false` here too:

```suggestion
		isDismissingItem === false
```

2025-01-03 11:02 UTC, techanvil approved these changes
LGTM, nice one @ankitrox!

2025-01-03 11:03 UTC, merged