Add no scenario label test for storybook for newly staged changes only.
google/site-kit-wp pull request #9912
Opened 2024-12-18 11:40 UTC by benbowler

## Summary

Addresses issue:

- #9865

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2025-01-03 21:01 UTC, aaemnnosttv requested changes
Thanks @benbowler – just one thing really to change here. The AC wasn't specific about this so no worries 👍

2025-01-06 08:37 UTC, benbowler commented on .eslintrc.json
> +        "sitekit/storybook-no-label": "off"
I created a follow up issue #9975

2025-01-06 17:30 UTC, aaemnnosttv commented on packages/eslint-plugin/configs/main.js
> +		'sitekit/no-storybook-scenario-label': [ 'error' ],
We actually don't need to add it here yet as we just want the rule to be enabled in the staged config right now. I gave this a quick test and it works, so I'll remove this and the related "off" above 👍

2025-01-06 17:39 UTC, aaemnnosttv approved these changes
Great, thanks @benbowler !

2025-01-06 18:25 UTC, merged