Feature/fpm survey triggers
google/site-kit-wp pull request #9939
Opened 2024-12-23 15:00 UTC by eugene-manuilov

## Summary

Addresses issue:

- #

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2025-01-08 18:02 UTC, techanvil requested changes
Nice work @hussain-t, this is working well. It could use some minor tweaks, please take a look.

2025-01-09 05:34 UTC, hussain-t commented on assets/js/googlesitekit/notifications/components/Notification/index.js
> +	onView = () => {},
Removed.

2025-01-09 05:35 UTC, hussain-t commented on assets/js/googlesitekit/datastore/site/first-party-mode.test.js
> +						isScriptAccessEnabled: false,
Updated.

2025-01-09 05:35 UTC, hussain-t commented on assets/js/googlesitekit/datastore/site/first-party-mode.test.js
> +				);
Updated.

2025-01-09 05:35 UTC, hussain-t commented on assets/js/googlesitekit/datastore/site/first-party-mode.test.js
> +						isScriptAccessEnabled: false,
Updated.

2025-01-09 16:08 UTC, techanvil commented on assets/js/googlesitekit/datastore/site/first-party-mode.test.js
> +				);
Thanks @hussain-t, you didn't remove the `waitFor()` though. I've pushed that change myself to save the round trip.

2025-01-09 16:49 UTC, techanvil reviewed
LGTM, thanks @eugene-manuilov and @hussain-t!

:white_check_mark:

2025-01-09 16:49 UTC, merged