Continue to refactor legacy stories.
google/site-kit-wp pull request #9941
Opened 2024-12-23 15:57 UTC by benbowler

## Summary

Addresses issue:

- #9882

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [ ] I have added a QA Brief on the issue linked above.
- [ ] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2025-01-06 11:31 UTC, benbowler commented
Awaiting the dependent branch to be merged.

2025-01-10 14:41 UTC, techanvil requested changes
Hi @benbowler, great work on this migration, it's quite a task.

I've identified a number of scenarios that we should fix and retain in some form. I've also left a handful of other comments. Please take a look.

Also noting that I've again been doing QA:Eng testing as part of the CR process, so once you've addressed the review comments I can review the new/affected stories and wrap up the QA as well.

2025-01-13 11:54 UTC, benbowler commented on stories/module-adsense-setup.stories.js
Looking into this:

1. `Account without AFC client:` is `Account: No Client`
2. Added back in as "Site - Ready w Ads Enabled + Existing Tag - Without Permission"
3. Fixed.

2025-01-13 12:51 UTC, benbowler commented on assets/js/modules/tagmanager/components/settings/SettingsForm.stories.js
The "Create an account" legacy CTA is handled in the parent `SettingsEdit` so I created a new story for this, otherwise I added all other stories to the `SettingsForm` story.

2025-01-17 10:20 UTC, benbowler commented on assets/js/modules/tagmanager/components/settings/SettingsForm.stories.js
I have brought them all to SettingsEdit and I realised No Accounts was actually the same as Set Up New Account and Create an Account so I've merged these all.

2025-01-17 12:35 UTC, techanvil requested changes
Thanks @benbowler!

Looks like you missed this comment on my previous review though, https://github.com/google/site-kit-wp/pull/9941#discussion_r1918916878

Once that is addressed this will be good to go.

2025-01-20 19:37 UTC, techanvil approved these changes
Thanks @benbowler, that's great!

Please note, I pushed a commit to address the last stories referenced in this [comment](https://github.com/google/site-kit-wp/pull/9941#discussion_r1918916878) which needed an update to ensure the snippet toggle was displayed.

I've confirmed the failing JS and E2E tests are unrelated to the changes in this PR.

Top work, LGTM, and good to go!

:white_check_mark:

2025-01-20 19:39 UTC, merged