Exclude (not set) city and country from reports.
google/site-kit-wp pull request #9943
Opened 2024-12-23 17:28 UTC by ankitrox

## Summary

Addresses issue:

- #7884 

## Relevant technical choices

## PR Author Checklist

- [ ] My code is tested and passes existing unit tests.
- [ ] My code has an appropriate set of unit tests which all pass.
- [ ] My code is backward-compatible with WordPress 5.2 and PHP 7.4.
- [ ] My code follows the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards.
- [ ] My code has proper inline documentation.
- [x] I have added a QA Brief on the issue linked above.
- [x] I have signed the Contributor License Agreement (see <https://cla.developers.google.com/>).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Code Reviewer Checklist

- [ ] Run the code.
- [ ] Ensure the acceptance criteria are satisfied.
- [ ] Reassess the implementation with the IB.
- [ ] Ensure no unrelated changes are included.
- [ ] Ensure CI checks pass.
- [ ] Check Storybook where applicable.
- [ ] Ensure there is a QA Brief.
- [ ] Ensure there are no unexpected significant changes to file sizes.

## Merge Reviewer Checklist

- [ ] Ensure the PR has the correct target branch.
- [ ] Double-check that the PR is okay to be merged.
- [ ] Ensure the corresponding issue has a ZenHub release assigned.
- [ ] Add a changelog message to the issue.

2025-01-02 17:05 UTC, techanvil requested changes
Hi @ankitrox, this needs a revision, please see my comments.

2025-01-02 17:05 UTC, techanvil commented on assets/js/modules/analytics-4/utils/data-mock.js
> +		'Portugal',
Please revert this change. We still want to mock the `(not set)` value being returned in the mock report data, as we don't filter it out in all of our reports.

```suggestion
		'(not set)',
```

2025-01-02 17:05 UTC, techanvil commented on assets/js/modules/analytics-4/utils/data-mock.js
> +		'Mumbai',
As above:

```suggestion
		'(not set)',
```

2025-01-02 17:05 UTC, techanvil commented on assets/js/modules/analytics-4/components/widgets/TopCitiesWidget.js
> +		},
This is not the correct approach and doesn't follow the IB.

In fact, this filtering approach is what was specified in the original IB, and it won't meet the AC for the reasons discussed in https://github.com/google/site-kit-wp/issues/7884#issuecomment-2459450700.

Please review the IB and amend the implementation appropriately.

2025-01-02 17:05 UTC, techanvil commented on assets/js/modules/analytics-4/components/widgets/TopCountriesWidget.js
> +		},
The same comment applies here as the one for the `TopCitiesWidget`.

2025-01-03 10:44 UTC, techanvil requested changes
Thanks @ankitrox, that's working nicely. There's one more update needed, please see my comment.

2025-01-03 10:44 UTC, techanvil commented on assets/js/modules/analytics-4/components/widgets/TopCitiesWidget.js
> +			: cityRows.slice( 0, 3 );
As per this comment, https://github.com/google/site-kit-wp/issues/7884#issuecomment-2548444615, we should create a reusable function for this logic, please can you lift this out as a common helper and reuse it in `TopCountriesWidget`.

We can also simplify it a bit:


```suggestion
	const filteredCities = ( cityRows ) => {
		const setCities = cityRows.filter(
			( { dimensionValues } ) =>
				dimensionValues[ 0 ].value !== '(not set)'
		);
		
		// If there are still 4 rows in the list, we only want the top 3:
		return setCities.slice( 0, 3 );
	};
```

2025-01-03 14:28 UTC, ankitrox commented
Thank you @techanvil . I have created a separated utility function so that we can use it in both places. Also added tests for the function.

2025-01-06 09:38 UTC, techanvil commented on assets/js/modules/analytics-4/utils/report-rows-with-set-values.js
> + * Analytics 4 filter rows having (not set) values.
Utility to filter out Analytics report rows which don't have a value set.

2025-01-06 09:41 UTC, techanvil commented on assets/js/modules/analytics-4/utils/report-rows-with-set-values.test.js
> + * Site Kit by Google, Copyright 2022 Google LLC
As above, and also fix the date:

```suggestion
 * Tests for utility to filter out Analytics report rows which don't have a value set.
 *
 * Site Kit by Google, Copyright 2024 Google LLC
```

2025-01-06 09:48 UTC, techanvil requested changes
Thanks @ankitrox! A couple of last tweaks and this should be good to go.

2025-01-06 09:48 UTC, techanvil commented on assets/js/modules/analytics-4/utils/report-rows-with-set-values.js
> + * Analytics 4 filter rows having (not set) values.
Let's tweak the description to be a bit clearer:

```suggestion
 * Utility to filter out Analytics report rows which don't have a value set.
 ```

2025-01-06 09:48 UTC, techanvil commented on assets/js/modules/analytics-4/utils/report-rows-with-set-values.test.js
> + * Site Kit by Google, Copyright 2022 Google LLC
As above, and also fix the date:

```suggestion
 * Tests for utility to filter out Analytics report rows which don't have a value set.
 *
 * Site Kit by Google, Copyright 2024 Google LLC
```

2025-01-06 09:48 UTC, techanvil commented on assets/js/modules/analytics-4/utils/report-rows-with-set-values.test.js
> +	];
Let's define this in a `beforeEach()` to make the tests more robust. As things stand, if we consider `reportRowsWithSetValues()` as a black box, it could in theory mutate this data structure between tests.

```suggestion
	let mockRows;

	beforeEach( () => {
		mockRows = [
			{ dimensionValues: [ { value: 'value1' } ] },
			{ dimensionValues: [ { value: '(not set)' } ] },
			{ dimensionValues: [ { value: 'value2' } ] },
			{ dimensionValues: [ { value: 'value3' } ] },
			{ dimensionValues: [ { value: 'value4' } ] },
		];
	} );
```

2025-01-06 15:12 UTC, ankitrox commented
Thanks for reviewing the PR @techanvil . I've updated the PR as per your suggestions and assigning it to you for reviewing the changes.

Thanks

2025-01-06 15:27 UTC, techanvil approved these changes
LGTM, nice one @ankitrox!

I've confirmed the failing tests are unrelated to the changes in this PR.

2025-01-06 15:28 UTC, merged